### ISSUE TITLE
Clean up `root_user`, `ancestry`, and `copy_of`

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1032]
We need to be able to report the "original author(s)" of a casebook, even when it's a clone of a clone of a clone.

With the current data model, the correct way to do so would be to look up the root node in the casebook's `ancestry`, and find the right `ContentCollaborator`(s): probably those with `attribution=True`? (attribution vs. ownership vs. authorship is a discussion for another time...)

In times of yore, it looks like the original author's ID was cached in the `root_user_id` field, and instead of `ancestry`, `copy_of` was used.

Presently, when cloning, we update both `ancestry` and `copy_of`. At the time of the Rails=>Django migration, the `root_user_id` was NOT being populated by the Rails app for new clones; we followed suit and are not populating it in the Django app.

The data is somewhat in disarray.

About half of our casebooks have a `root_user`:
```
>>> Casebook.objects.filter(root_user__isnull=True).count()
351
>>> Casebook.objects.filter(root_user__isnull=False).count()
378
```

## Two answers... that don't match, type A
Of those with `root_users`, many also have `ancestry`, and the "original author" as calculated using the ancestry differs from that cached in `root_user` more often than not:
```
>>> root_user_and_ancestry = ContentNode.objects.filter(root_user__isnull=False, ancestry__isnull=False)
>>> root_user_and_ancestry.count()
232
>>> len(list(filter(lambda book: book.root_user_id == book.version_tree__root().owner.id, root_user_and_ancestry)))
178
```

## Two answers... that don't match, type B
Many casebooks with `root_user` lack both `ancestry` and `copy_of`, which would seem to mean that they are originals.... but their `root_user` does not match their present owner:
```
>>> root_user_no_ancestry = ContentNode.objects.filter(root_user__isnull=False, ancestry__isnull=True)
>>> root_user_no_ancestry.count()
146
>>> root_user_no_ancestry.filter(copy_of__isnull=True).count()
146
>>> len(list(filter(lambda book: book.owner == book.root_owner(), root_user_no_ancestry)))
109
>>> weird_ones = list(filter(lambda book: book.owner != book.root_owner(), root_user_no_ancestry))
>>> len(weird_ones)
37
```
They all have `playlist_id`s, from old-H2O; a sample shows that many have duplicate `playlist_ids`:
```
33595, 1923, Anonymous, Holger Spamann
73483, 1923, Anonymous, Holger Spamann
16066, 1923, Brett Johnson, Holger Spamann
36817, 1923, Anonymous, Holger Spamann
38070, 1923, Anonymous, Holger Spamann
79502, 1923, Brett Johnson, Holger Spamann
71805, 11114, Tobias Schonwetter, Prof. William T. Fisher III
```
Maybe these are actually clones from old-H2O, that had problems during import, or even that were buggy there?

## The Project
I'm not seeing a quick programmatic way to sort this out.

We should sort this out.... 

- calculate "original author(s)" via ancestry and contentcollaborator, exclusively
- migrate the info from `root_user` as necessary to make that happen accurately, constructing or repairing `ancestry` as necessary, with special care for the books that have conflicting answers
- make sure there is a `copy_of` field for every book with an `ancestry`, and vice versa, and that the two always match up
```
>>> Casebook.objects.filter(copy_of__isnull=False).count()
336
>>> Casebook.objects.filter(ancestry__isnull=False).count()
350
```
- ....and when all is said and done, let's drop `root_user_id` and `copy_of` (unless there's a convincing performance reason to cache them... which.... maybe there is), or, at least, write some code to keep things in sync and repair things when broken, using `ancestry` and `contentcollaborators` as the source of truth

**Comment by holtchesley** [comment]
#1083 #1084 #1085 cleared this up.
