### ISSUE TITLE
Editors, owners, and attribution

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1033]
In 40 instances, owners do not have attribution:
```
>>> ContentCollaborator.objects.filter(role='owner', has_attribution=False).count()
40
```
The `editor` role is only used 5 times, and in all 5 instances, editors do not have attribution.
```
>>> ContentCollaborator.objects.filter(role='editor', has_attribution=True).count()
0
>>> ContentCollaborator.objects.filter(role='editor').count()
5
```

What does it mean to be an owner that lacks attribution? What would it mean to be an editor that has attribution (and how would/should that look in the UI)? 

I think that these concepts should be combined and tracked by `role` only: I think "attribution" should be part of the defintion of particular `role`s, rather than its own field.

Proposed:  'owner' => 'author', which comes with full permissions and attribution. 'editor' lacks attribution and comes with... whatever permissions deemed appropriate. If necessary, a third role, 'admin' or 'super_editor' or whatever could be created that lacks attribution and comes with full permissions.

**Comment by holtchesley** [comment]
#1083 #1084 #1085 cleared this up.
