### ISSUE TITLE
Case model & import-related tweaks

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1041]
TODOs in the code remark:
```
parties = JSONField(blank=True, null=True)  # TODO: this should be deleted. It's just the `name` field with uncorrected typos.
```

```
header_html = models.CharField(max_length=15360, blank=True, null=True)  # TODO: no longer used? delete?
```

```
# TODO: copying a Rails bug. Using a dict here is incorrect, as the same data-type can appear more than once:
opinions={el.attr('data-type'): el('.author').text() for el in parsed('.opinion').items()},
```
This last suggests we may need to re-import some cases.

**Comment by holtchesley** [comment]
Just a note that ```SELECT count(*) FROM main_case WHERE header_html IS NOT NULL and header_html !~ '\s*'``` returns no rows, so there's no useful info in the column that we _could_ be taking advantage of (unless we've done some weird whitespace encoding scheme in the past).
