### ISSUE TITLE
Move publishing functionality to /publish

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1047]
Instead of publishing casebooks by issuing a dataless PATCH request to the same URL as we use to GET it, let's switch to a /publish route, as with /export. I don't think it's particularly helpful for publication logic to live in the same view, and since other kinds of edits, like changes to title/subtitle/headnote, aren't handled here, it isn't particularly RESTful.

**Comment by lizadaly** [comment]
The current state definitely tripped me up. 

As part of this I think it would make sense to make the publish button a normal POST with its own form. There's not much point in rendering it in JS when it ends up just redirecting anyway.
