### ISSUE TITLE
Add page/view titles

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#105]

**Comment by abziegler** [comment]
![h2o-titles](https://user-images.githubusercontent.com/2140548/39430292-6fbbc1ea-4c5b-11e8-8749-978af961d84a.png)

**Comment by bjohnson747** [comment]
-Sections/casebooks show up in the browser tab title as: "H2O | Read | [Casebook name]"

-Resources show up with no name just "translation missing"

-Cases appear as "H2O | Cases"

-Other users' dashboard appear as "H2O | Users,' ones own appears as "H2O | base."

Should determine what's the desired display for each of these, though the Resources 'translation missing' is the most urgent of these.

**Comment by abziegler** [comment]
Some more specification of what we want titles to say:

- Casebooks: `H2O | Casebooks | [Casebook title]`

- Casebook section: `H2O | Casebooks | [Casebook title] | [Section title]`

- Case: `H2O | Cases | [Case shortname]`

- Text: `H2O | Texts | [Text title]`

- Link: `H2O | Links | [Link title]`

- Author Dashboard: `H2O | Dashboard`

- Search: `H2O | Search`

**Comment by leppert** [comment]
@abziegler PR here: https://github.com/harvard-lil/h2o/pull/417

Right now, Text and Link are nested under Resources, so they have the same title that any resource would have (ex: H2O | Resources | Link to www.example.com) which makes sense given the url structure but I'm happy to revise to what you spec'd above.

**Comment by abziegler** [comment]
Makes sense. No point in revising. Thanks.
