### ISSUE TITLE
Modals and redirects

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1050]
From https://github.com/harvard-lil/h2o/blob/develop/web/frontend/legacy/lib/requests.js#L35-L45
```
      // This code actually expects successful AJAX requests to receive
      // a redirect as a response. Axios follows the redirect, performing
      // a GET of the page we want the browser to display next. Here, we
      // examine the URL of we just retrieved, and compare it to the URL
      // of the page we are presently on. If we are already on that page,
      // we perform a refresh. Otherwise, we direct the browser there.
      // In all cases, this performs a duplicate GET.
      //
      // Let's have a think on how we might redesign this in the future.
      // Probably a mix of more Vue, and switching from AJAX to standard
      // form submissions.
```

**Comment by lizadaly** [comment]
Good to clean up when working with the JS again in a major way.

**Comment by rebeccacremona** [comment]
Re-opening because we just got very confused by this behavior, when trying to add a flash message after the publication of book. (PATCH -> reload; which looks a lot like, but is not, a normal top-level form submission)

**Comment by lizadaly** [comment]
There are likely more instances of this than the publish endpoint, but I think now that we have some examples we can open specific tickets for any additional cases we want to modify.
