### ISSUE TITLE
Allow Text Blocks with no body

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#1056]
Currently cannot add/save a Text Block with a "Title" field and empty "Body" field. We should enable this. Use case is authors who want to build out the basic structure of book and then go back through and fill in content/body.

(also, if we are going to require fields, we should indicate to user in UI so failure to save/add isn't mysterious)

**Comment by rebeccacremona** [comment]
See also related https://github.com/harvard-lil/h2o/issues/830
