### ISSUE TITLE
TinyMCE 404 errors

### ISSUE THREAD

**Issue by holtchesley** [harvard-lil/h2o#1068]
TinyMCE import results in a couple of (inconsequential except that they show up on the console) 404 errors:

https://opencasebook.org/static/dist/js/skins/content/default/content.css
https://opencasebook.org/static/tinymce_skin/skin.min.css.map
https://opencasebook.org/static/tinymce_skin/content.min.css.map

**Comment by jcushman** [comment]
In case it saves a minute when working on this, I remember causing this bug -- it had to do with giving up on https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/#webpackfile-loader after a brief attempt, and manually copying skins as described in static/tinymce_skin/README.txt to a place where TinyMCE could eventually find them. Figuring out the correct webpack config would hopefully also avoid these 404s.
