### ISSUE TITLE
DOCX export - markup for case headers

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#108]
Case headers/metadata should be tagged something other than "Normal." 

Ideally we'd be able to do some fine-grain tagging, so that Word editors can style case-name, case-citation, case-date, etc. differently. 

At a minimum, we should tag it as "case-header" rather than "Normal" 

![case-header](https://user-images.githubusercontent.com/2140548/29363378-c1bf2ffe-825d-11e7-9f46-7347658e6d82.png)

**Comment by bjohnson747** [comment]
Another example of "case header" that should have it's own style separate from "Case Text" or "Normal" :
<img width="485" alt="screen shot 2017-08-23 at 1 03 42 pm" src="https://user-images.githubusercontent.com/12850389/29630973-0b42c362-880c-11e7-87cf-705f4b83afbe.png">

**Comment by emmalemma** [comment]
I'll add a style, at least. For existing data we can't do much else, all we know is there is a `<center>` tag.

For new data, it's easy to add an individual word style for any HTML tag.
