### ISSUE TITLE
Remove origin authors from attribution list

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#1102]
In view of Credits tab, which gives attribution to original authors of cloned books/resources, we should remove origin author from attribution lists

Here (on Casebook contents view) ....

![image](https://user-images.githubusercontent.com/2140548/75474742-87045b00-5965-11ea-84e0-d5724cd13fb2.png)

Here (on Dashboard view) ...

![image](https://user-images.githubusercontent.com/2140548/75474771-94214a00-5965-11ea-9d65-36b13fba2f58.png)

We also need to make sure origin author is ignored/unattributed for purposes of search. For example, if I (not a verified prof) clone a book by Prof. Q (a verified prof), then that currently that book will show up in search, with only the name of Prof. Q as author:

![image](https://user-images.githubusercontent.com/2140548/75475020-0003b280-5966-11ea-96b1-22e436703f16.png)

**Comment by holtchesley** [comment]
I think this is a matter of updating some possibly stale/incorrect data in the adminterface and a judicious application of `REFRESH MATERIALIZED VIEW` to update the search index.
