### ISSUE TITLE
Stand-alone case display rendering only case name

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#1134]
We allow stand-alone case display. We also allow search on the cases table.

When we render a stand-alone case, we should display the whole case. Currently, we display only the case name, e.g.: https://opencasebook.org/cases/8359/. 

![image](https://user-images.githubusercontent.com/2140548/79766652-43d7c000-82f6-11ea-887b-64d7a546a08c.png)

**Comment by holtchesley** [comment]
Fix deployed to prod.
