### ISSUE TITLE
Allow blank provenance field in new casebooks

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#1151]
When updating new casebooks (e.g. to add collaborator) django-admin throws error when `provenance` field is blank. This field is blank on all new casebooks that weren't cloned from some other origin.

We should allow this field to be blank for fresh casebooks. 

Note: this is blocking admin ability to add collaborators.

![image](https://user-images.githubusercontent.com/2140548/81805177-62416d80-94e8-11ea-95f9-a4326e121b84.png)

**Comment by holtchesley** [comment]
Resolved in #1153
