### ISSUE TITLE
Default to 'Edit' rather than 'Preview' when navigating private/draft casebooks

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#1152]
When navigating among sections, resources, etc. in a draft casebook, H2O always defaults to the "Preview" view. We should default to the "Edit" view instead. Implicit intent of author's navigation within a draft casebook is to make changes, so we should make that immediate rather than extra hop away.

![h2o-default-edit](https://user-images.githubusercontent.com/2140548/81807975-0c22f900-94ed-11ea-9af2-fb4b50c6439d.png)

**Comment by holtchesley** [comment]
Resolved in #1155
