### ISSUE TITLE
Enable view casebook resources/sections in django admin

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#1154]
Admin casebook view includes links to view sections and resources within casebook, but right now when you click it renders empty lists

Admin casebook view:
![image](https://user-images.githubusercontent.com/2140548/81817878-47c4bf80-94fb-11ea-9eae-d75520c3321f.png)

Admin casebook > resources view
![image](https://user-images.githubusercontent.com/2140548/81817961-67f47e80-94fb-11ea-812c-45dd9549ddf4.png)

**Comment by holtchesley** [comment]
Resolved in #1156
