### ISSUE TITLE
font normalization 

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#116]
https://h2o-dev.lil.tools/casebooks/23066-federal-budget-policy-january-2016-playlist-26271/resources/5.1.1-train-administrator-environmental-protection-agency-v-city-of-new-york-et-al 
[37] MR. JUSTICE WHITE... is a more arial-like font than the rest of the text

**Comment by bjohnson747** [comment]
Added to Trello

**Comment by bjohnson747** [comment]
Also experienced in block quotes

**Comment by cgruppioni** [comment]
Appears Atlas Grotesk isn't loading problem -- read old convos back

**Comment by abziegler** [comment]
Closing b/c confusing as hell
