### ISSUE TITLE
Annotation dialogue not appearing

### ISSUE THREAD

**Issue by ktfhale** [harvard-lil/h2o#1173]
New user to H2O/opencasebooks here. I'm unable to highlight, elide, or make other forms of annotation to casebook text, both on my own and any other casebooks. Highlighting text does not cause the right-hand annotations menu to appear, [as depicted in the video on annotation.](https://vimeo.com/292818922) I've tested this on both Safari 13.0.5 and Chrome 81.0.4044.138, on three different machines. JavaScript is enabled in both browsers. I tried disabling any sort of ad-blocker that might be confounding things, but that has had no effect. Am I missing something obvious?

**Comment by abziegler** [comment]
Hi. Thanks. We're not able to recreate this bug. Testing on our end confirms annotations working across FF, Chrome, Safari. If you're logged in and working on a case within one of your draft casebooks, annotation should be working. If the problem persists, please email our support team at info@opencasebook.org and we'll take a closer look at this on Monday morning. For now I'm going to close this issue. Thank you.
