### ISSUE TITLE
Larger text that's highlighted overlaps itself

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#118]
ex. https://h2o-dev.lil.tools/casebooks/30538-untitled-casebook-30538/resources/2.1-chloline/annotate
<img width="687" alt="screen shot 2017-08-04 at 11 53 19 am" src="https://user-images.githubusercontent.com/12850389/29632010-94d4140c-880f-11e7-9535-6a952f5c48eb.png">

**Comment by bjohnson747** [comment]
added to ticket #140

**Comment by abziegler** [comment]
believe fixed
