### ISSUE TITLE
Running without production data

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1208]
This is probably so rare that it's not worth spending any time on, but just noting: 

Today, I tried to spin up a fresh H2O dev environment from https://github.com/harvard-lil/h2o/tree/v20200803-01 without importing any prod data.  I couldn't: the migrations get stuck, if run on an empty DB. To work around, I deleted all the migration files, ran `makemigrations`, and then edited the initial migration it produced to replace the auto-generated, incorrect references to `models.LifeCycle` with `models.Casebook.LifeCycle`. 

There's not necessarily any point in supporting what I was trying to do, but it might be worth thinking about squashing migrations or similar at this point.

**Comment by lizadaly** [comment]
This must've happened at some point because a fresh environment works fine!
