### ISSUE TITLE
Broader email whitelisting and improve sign-up form copy

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#1212]
Add .gov emails and update copy on sign-up form to invite people to reach out to us if they are not .edu or .gov

![image](https://user-images.githubusercontent.com/2140548/90244401-afdab880-ddfe-11ea-8e96-89e4673dd842.png)

Propose changing "Registration is restricted to email addresses belonging to an educational institution. If your email address doesn't work and you believe it should, please Let us know."

to

"If you have an EDU or GOV email address, your account will be approved automatically. For others, please email us at info@opencasebook.org[active email link] to request an account."

**Comment by lizadaly** [comment]
This was done.
