### ISSUE TITLE
Annotation icons rendering 

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#1280]
As author, in edit mode, annotation icons in the right margin start getting wonky with heavy use, which happens with elisions especially.

![image](https://user-images.githubusercontent.com/2140548/104013927-2b5b4e80-5180-11eb-948a-65e5f6bba109.png)

In edit mode, there's some duplication in having both the ellipsis and the annotation icon. It may be worth considering using the ellipsis to trigger the edit menu.

**Comment by abziegler** [comment]
And at a certain point, the edit icons no longer render, which makes the annotations uneditable.

**Comment by holtchesley** [comment]
Fix deployed.
