### ISSUE TITLE
Collaborative authoring 

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#1294]
Just leaving an example of asynchronous comment-annotations being used in the wild to hack this, similar to google doc notes

![image](https://user-images.githubusercontent.com/2140548/105232025-cadff000-5b35-11eb-9c22-38a49cb43056.png)

**Comment by cath9** [comment]
I think we should get some data from people who have recently done some collaborative authoring to figure out what to do in this area more generally. so I'll add that to my to do's.
