### ISSUE TITLE
Elisions export improvements

### ISSUE THREAD

**Issue by holtchesley** [harvard-lil/h2o#1298]
Elisions/Annotations

How best to handle elision in export? Maybe give option of non-display. Although Word user can restyle, including to designate “hidden” style, which preserves space/paragraph but makes characters invisible. 

Elision/ellipsis of italicized content (e.g. citations) are rendering in export file with italics. We should discard any styling implied by elided text. 

Replacement text has hyperlink styling (though not linked). We should render as normal text.

**Comment by holtchesley** [comment]
Elisions/Annotations

How best to handle elision in export? Maybe give option of non-display. Although Word user can restyle, including to designate “hidden” style, which preserves space/paragraph but makes characters invisible. 

Elision/ellipsis of italicized content (e.g. citations) are rendering in export file with italics. We should discard any styling implied by elided text. 

Replacement text has hyperlink styling (though not linked). We should render as normal text.

**Comment by abziegler** [comment]
I did some testing of Word restyling "elision" as hidden, and it seems to do the trick.
