### ISSUE TITLE
Collapse All button

### ISSUE THREAD

**Issue by cath9** [harvard-lil/h2o#1301]
suggested by a user to make it easier to work with long casebooks

**Comment by lizadaly** [comment]
Is this "collapse all sections"?

**Comment by lizadaly** [comment]
@cath9 Do you have a sense of whether they really want "collapse literally all sections on this page", or do people want "collapse all above this section" or "collapse all below this section"? If it's the first thing, what are they trying to do?

Do you think people expect the expand/collapse state to persist between page navigation?

**Comment by lizadaly** [comment]
Answered offline: we're just going to do "collapse all" for the scope of the whole page.
