### ISSUE TITLE
More guiding language on quick add window in H2O

### ISSUE THREAD

**Issue by cath9** [harvard-lil/h2o#1305]
I have found that when I explain this window to people they are blown away by the functionality, but that not a lot of people intuit what it does just by looking at it. I wonder if we could label it as "Quick Add", and change the text in the box to read "Enter resource here", or even be more specific and say "Enter case, heading, link, or outline here".

**Comment by lizadaly** [comment]
@cath9 Do you want to keep it where it currently lives, or move it up on the page more?

**Comment by cath9** [comment]
Update copy around this field (which, yes, can stay at the bottom for now). 

In the field: Enter case, heading, link, or outline here

In slightly larger font above the field: Add an individual resource or multiple items by pasting them into the field below. 

In smaller font below the field: Items could include section headings, text resource titles, links, and citations for caselaw or sections of the federal code. Multiple items may be in a flat or nested list. Review our documentation to learn more. 

(May edit copy based on space)
