### ISSUE TITLE
Export: unable to open DOCX of casebook

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#131]
https://h2o-dev.lil.tools/casebooks/31541-torts-spring-2016-full-version-playlist-25022/ 
Downloaded DOCX version, received the following error and was unable to open:
<img width="406" alt="screen shot 2017-08-30 at 4 13 04 pm" src="https://user-images.githubusercontent.com/12850389/29892940-68169ef0-8d9e-11e7-9099-6eed8ae081e1.png">

**Comment by emmalemma** [comment]
This should be fixed now. I'll refactor and run another scan to make sure all docx exports load, it's possible that the way I implemented the BlockQuote style created some other edge cases.
