### ISSUE TITLE
Newsletter and signup questionnaire

### ISSUE THREAD

**Issue by holtchesley** [harvard-lil/h2o#1312]
Add newsletter opt-in and primary use question to signup form. 

Something along the lines of:
"I am primarily interested in:
[] Publishing my own book with H2O
[] Creating course materials like syllabi and reading lists with H2O
[] Finding material already published in H2O that I can use or adapt for my class
[] Reading content in H2O
"

**Comment by lizadaly** [comment]
Superseded by #1718
