### ISSUE TITLE
Enable adding sections that are only available to other verified professors

### ISSUE THREAD

**Issue by cath9** [harvard-lil/h2o#1318]
Professors have asked me fairly regularly about ways to add notes to their books that would only be visible to other professors. This would include any information, guidance, notes about pedagogy, etc. that helps a professor adopt another's open casebook.

**Comment by lizadaly** [comment]
* The section should be clearly marked differently from other sections
* Visiting the section as a non-verified-professor user should (probably?) return a 404.
* To avoid hassles with gaps in numbering, the sections should probably only be available at the front or back of the casebook. [edit: this is fine, they should marked as `does_display_ordinals=False`]

**Comment by cath9** [comment]
Consider including attachments. Some folks have mentioned including a syllabus, exams, course proposal for the Dean, etc.

**Comment by lizadaly** [comment]
Collaborators should probably be able to add and see this material, especially since that's the kind of thing an RA might be in charge of entirely.
