### ISSUE TITLE
Improve Editions/Search interaction by limiting search results to most-recent edition

### ISSUE THREAD

**Issue by holtchesley** [harvard-lil/h2o#1349]

**Comment by lizadaly** [comment]
@cath9 Do you have ideas here?

**Comment by cath9** [comment]
Ideally only the most recent version of a casebook that has been arranged as part of a series would show up. For example, this author has arranged two books they teach into two separate series, but all published versions are surfaced in search, not just the most recent. If we're building out more search options, we could also allow people to search for series. 
https://opencasebook.org/users/420/

**Comment by varun-magesh** [comment]
We have 5,444 casebooks, and 8 series by my count. Unfortunately. It seems like, as @lizadaly mentioned in #1471, this is an underutilized feature.

Maybe a nudge to bundle casebooks when authors copy/have another casebook with an identical /similar title would help?

**Comment by cath9** [comment]
Yes! was thinking the same, that when an author clones their own casebook they should be asked if they want to add it to a Series. the problem this doesn't solve for is what if an RA creates a clone for a professor. But I still think its a good start.

**Comment by lizadaly** [comment]
@cath9 could you supply an example here? I will remove duplicate versions from the search index but we'll still hold on promoting the series feature for now.

**Comment by cath9** [comment]
Yep, sounds great. Here is an example, the Ball/Oberman casebook is another. It could be as simple as it's showing the two most recent versions, but I'm not completely sure. I think ideal state would be to only show the most recent and also to indicate somehow that it it part of a series, but we can save the second half of that. 

<img width="1162" alt="Screenshot 2023-03-20 at 9 27 21 AM" src="https://user-images.githubusercontent.com/77024527/226354565-1c3615c9-a517-41ff-a66c-fd8daf1198d3.png">
