### ISSUE TITLE
"Text" notes in QuickAdd reverting to "Section" 

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#1382]
https://www.loom.com/share/aaecd7be57414ddba64be34bfed72e82

**Comment by cath9** [comment]
@lizadaly this issue still exists, only now "text" is "custom content". video is helpful. I'm not sure if its a bug or a UI issue where the intention is that somebody will type in the window and then select the type of content if they need to override what the platform suggests. if they do it the other way around, though, things get wonky.

**Comment by lizadaly** [comment]
Fixed by the recent refactor.
