### ISSUE TITLE
More descriptive resource labels?

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#1388]
All texts are labeled `Text` even if they contain only image or video. Should we consider more descriptive labels based on contents type? e.g. Image, Video, Mixed.

![image](https://user-images.githubusercontent.com/2140548/124119955-2a292100-da41-11eb-8a76-628f4e630dc1.png)

**Comment by cath9** [comment]
Had a similar thought and wondered whether there would be a way to add icons after the title or something to indicate those types of content.
