### ISSUE TITLE
Need way to migrate notes field from H2Ov1

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#139]
Some instructors have used the notes field for relevant info for their courses, including Jake Gersen. (https://h2o.law.harvard.edu/users/101023) Will need to make sure this migrates: perhaps merge the notes field into the casebook section headnote field, adding a linebreak and the header "NOTES: " ?

**Comment by abziegler** [comment]
@bjohnson747 is this still a problem in V2?

**Comment by bjohnson747** [comment]
@abziegler yes - the 'Notes' were not imported on the last round of data import into Alpha.

Example:
https://h2o.law.harvard.edu/playlists/52513 - each case in this playlist has both an author-made 
'headnote' , and 'notes' (the original use case of notes I believe was that they would be set to Public after the given case had been gone over in class.)
For new H2O, only the headnote was imported, so in this case (https://alpha.opencasebook.org/casebooks/29980-zittrain-torts-playlist-spring-2018/sections/1.1-righting-or-punishing-the-wrong) Sam manually wrote in the Notes weren't pulled from old H2O -I just confirmed with her that this she did this manually.
