### ISSUE TITLE
Improve reading navigation by adding next/previous controls while viewing  

### ISSUE THREAD

**Issue by cath9** [harvard-lil/h2o#1393]
Create a navigation path between consecutive resources (arrows on the right and left?)

**Comment by lizadaly** [comment]
For example:

https://opencasebook.org/casebooks/726-administrative-law-372/resources/3.1-extracts-procedural-fairness-baker/ should make it possible to move to the next or previous section of the casebook without returning to the table of contents. The controls should be available to the reader regardless of where they are in the text (i.e. not just pinned to the top or bottom of the scrollable page).

In many online reading environments, the forward/back arrow keys will also trigger this behavior.

**Comment by lizadaly** [comment]
Completed with #1640 !
