### ISSUE TITLE
Allow non-numbered sections

### ISSUE THREAD

**Issue by holtchesley** [harvard-lil/h2o#1420]
Some professors have requested non numbered sections for casebooks.

An example structure: 
 - Introduction
 - 1. Free Speech
   - What is speech anyway?
   - 1.1 US. Vs. Fractious Telecom
   - 1.2 In. Re. Baked Goods
   - Conclusion
 - 2. Libel
   - Calling people names in print. 
   - 2.1. Crichton vs. You-know
   - Conclusions
 - Epilogue
 
The current section numbers are derived directly from the tree structure, and we'd need to likely augment the data structure to keep track of another number.

**Comment by lizadaly** [comment]
This exists.
