### ISSUE TITLE
Collect example documents for targeting exports to

### ISSUE THREAD

**Issue by holtchesley** [harvard-lil/h2o#1422]
Collect example documents for exporting to a format that requires very little manipulation to get it to work with 

https://kdp.amazon.com/en_US/
https://www.lulu.com
University bookstores (not sure how thoroughly we'll be able to collect examples here).
Other direct publishing sources.

**Comment by holtchesley** [comment]
Harvard Book Store might use Espresso for printing books.

**Comment by rebeccacremona** [comment]
Ooh, look at all these formatting details: 
https://kdp.amazon.com/en_US/help/topic/GLRF8JDXY5LPE3TX
https://kdp.amazon.com/en_US/help/topic/GDDYZG2C7RVF5N9J#frontmatter
