### ISSUE TITLE
Cache exports on publish

### ISSUE THREAD

**Issue by holtchesley** [harvard-lil/h2o#1425]
Set up a caching system for exports of entire casebooks. 

 - Casebook export generated once on publish, and then cached. 
 - Cache can be overridden, or supplemented with additional docs supplied by authors.

**Comment by rebeccacremona** [comment]
Porting over some related discussion from Slack:

https://hlslil.slack.com/archives/C4FE9FL56/p1646759363245329
> chefandy
thought: html gets generated pretty quickly and is deterministic. We could hash the html every time someone hits the export button, compare that to a stored hash, and if unchanged, see if we have a local cached docx to serve them. Much lower overhead than generating every time, kills the possibility that someone w/o edit access could batter our AWS instance via our app, and would have no complicated cache expiration logistics (well, generating the HTML isn’t simple but it also already exists).
> Put in an example draft PR: https://github.com/harvard-lil/h2o/pull/1536

> jcushman
> love this hash-the-html sketch. one thing that could make it even simpler is to stick the docx right onto a field rather than into a file (which in general is good architecture since it gets your external resources into postgres transactions, but takes thinking about not blowing up the size of queries). would also want to handle the case where generation fails, so it doesn’t endlessly try to regenerate a failing casebook
>
> Thread for a sketch of how I would approach caching in the database: https://hlslil.slack.com/archives/C4FE9FL56/p1647273085537009

The linked thread includes some draft code.

**Comment by lizadaly** [comment]
One strategy could be:

- Don't delete HTML exports from S3 at export completion, set a lifecycle policy for objects in the bucket of N hours (24?) and let AWS handle that for you.
- Use the ETag AWS gives you for the object(s) in the bucket as your hash. 
 
The exports would need to be guaranteed the same for the same unchanged content, so no dynamically computed timestamps at this step. If you want an "exported on" timestamp in the generated book, either compute it further downstream in the HTML -> docx pipeline, or make it granular to the calendar day, so most repeated exports should be the same.
