### ISSUE TITLE
Cap API integration 

### ISSUE THREAD

**Issue by cgruppioni** [harvard-lil/h2o#143]
-

**Comment by abziegler** [comment]
From H2O, an author making a casebook should be able to search for an arbitrary CAP case by name or citation and ingest it into H2O for inclusion in the casebook and annotation.

**Comment by cgruppioni** [comment]
Think about how to clean up data from old cases

**Comment by abziegler** [comment]
@leppert here is a working doc with some more detail/context for what we're after here (may be better than slack for keeping this sane)

https://docs.google.com/document/d/14sNtw_Qavzf2p2fKweAyRCvcSusBelQDWAwyZRYIb4A/edit?usp=sharing

**Comment by abziegler** [comment]
closed as resolved
