### ISSUE TITLE
Verify Footnote styles work in export

### ISSUE THREAD

**Issue by holtchesley** [harvard-lil/h2o#1432]
Make sure that exports are properly styling Footnote References and Footnotes.

Add a test or two.

**Comment by rebeccacremona** [comment]
Looks like we don't presently apply `Footnote Text`: https://github.com/harvard-lil/h2o/blob/6ed792207e364f22ecab9f4af00281f07de0cc29/web/main/models.py#L2393, called by https://github.com/harvard-lil/h2o/blob/develop/web/main/templates/export/node.html#L36.

I bet I dropped that by accident in the transition to pandoc.

**Comment by rebeccacremona** [comment]
Note: this is about author-supplied annotations on TextBlock and LegalDocuments that are, in our present setup, exported in a footnote-like manner (note and link annotations). This is NOT about any of the other [varieties of footnotes](https://docs.google.com/document/d/1PBokZayYrgs4pZv0FyjlJMaJYCXnJoGJ_Gc_AH1B5TM/edit#heading=h.vr9qspjqwb95).
