### ISSUE TITLE
'Related' tab performance

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1433]
I clicked into the 'related' tab for `2566-torts`, which I imagine has one of the most complex histories in the application, and it was slow enough to load that I was a little worried I might get a 504 (like when something too expensive happens in the Perma admin, which can and does happen). Might be worth looking into whether this tab should load quickly with a 'loading' spinner for the user and then retrieve relationship data in an ajaxy way, and/or profiling?

**Comment by holtchesley** [comment]
This tab is superuser only for now (in part because of the performance uncertainties).

**Comment by rebeccacremona** [comment]
Oh cool! Sorry for stumbling into it!

**Comment by holtchesley** [comment]
I think the related tab, in some form, would be good to open up once it looks performant enough. This is a good ticket for it.
