### ISSUE TITLE
Maybe? Enable JSON viewer in LegalDocument admin

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1441]
`django-json-widget` is installed to provide an admin widget with nice formatting for viewing and editing model JSON fields, including views with syntax highlighting, etc. But, when the JSON field is `readonly`, the widget doesn't get used: the JSON in printed in the admin interface as a blob of text. That blob is easy to copy/paste, but hard to read.

If desired, we could use [this workaround](https://github.com/jmrivas86/django-json-widget/issues/38#issuecomment-927175031) to enable the widget in "view" mode for individual read-only fields, for instance, the `metadata` field in the LegalDocument admin. It would look like this:
![image](https://user-images.githubusercontent.com/11020492/138943140-943da850-8f02-4540-a30d-a7097709be3e.png)
instead of:
![image](https://user-images.githubusercontent.com/11020492/138943341-43bc7124-baa4-437c-b362-fe4869c59a8a.png)

Desirable? TBD at an appropriate time.

**Comment by holtchesley** [comment]
Implemented in 48c5ce1df09ee3b354d51c0a3c8e8a8f73ee8367
