### ISSUE TITLE
New section reports "this casebook is empty"

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1443]
Probably just wants s/casebook/section/, if showing a section?

- Add a new section
- Click into it
- Scroll beneath the title/subtitle, headnote fields
![image](https://user-images.githubusercontent.com/11020492/139277203-73c61417-7f2b-4386-8f1c-e6bcc82a2776.png)

**Comment by lizadaly** [comment]
Looks like this was done:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/19571/178070399-e54b46c5-62c3-434b-bc12-c108fdfc9007.png">
