### ISSUE TITLE
Activate account emailer 

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#145]

**Comment by bensteinberg** [comment]
Is h2o-dev not sending email? That is, is this a config/deployment problem, or something else?

**Comment by abziegler** [comment]
Certainly not receiving email (e.g. account verification emails) from h2o-dev. Don't know why.

**Comment by bensteinberg** [comment]
OK, thanks. Will take a look.

**Comment by bensteinberg** [comment]
Fixed, and email config overhauled in https://github.com/harvard-lil/h2o/pull/156
