### ISSUE TITLE
AWS Lambda budget exceeded error page

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1483]
Once it's configured, find out what it looks like from the application's perspective when we exceed our export budget. Then, try and catch for that behavior so that we don't get fifty gazillion stack trace emails under those conditions.

**Comment by lizadaly** [comment]
From archaeology it looked like this experiment didn't work as desired; are you still considering exploring making this work?

**Comment by bensteinberg** [comment]
After a little drama last month with a casebook recursively exporting itself, @rebeccacremona wrote
> I was wondering if we would get a huge bill because of last week's adventure with that book that was recursively exporting itself.... Glad we didn't break the bank, even though $30 is not small, compared to $0. Glad this showed up at all... but good to know that no: the alerts will not be sent in a way that will help us intervene if lambda use is out of control.

**Comment by lizadaly** [comment]
We are more likely to shift away from using Lambda here than to further refine it.
