### ISSUE TITLE
Stray `;`?

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1507]
I noticed that sometimes we have [`_h2o_keep_element`](https://github.com/harvard-lil/h2o/blob/develop/web/test/files/export/export-casebook-no-annotations.html#L49) and sometimes we have [`_h2o_keep_element;`](https://github.com/harvard-lil/h2o/blob/develop/web/test/files/export/export-casebook-no-annotations.html#L81), with a semi-colon.

When we have a moment, let's see if there's a stray `;` or two in a template (and whether it makes it into export), or whether it serves a purpose.

**Comment by jcushman** [comment]
Ah, this explains why docx2txt.sh showed extra semicolons! They are in fact coming through to the export, as tiny white text. Following select, change text to black, increase size:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/376272/153494420-21cf50cb-484f-4450-8cec-bc59e53ed413.png">
