### ISSUE TITLE
Improve Django admin performance for specific model pages

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1540]
Needs re-thinking, subsequent to the decision to remove proxy models. Not performant at present: for instance, attempts to load the resource list 504.

**Comment by lizadaly** [comment]
Pages that work for me locally, if slowly, but do time out on prod:

* Resources
* Content annotations
* Content nodes

**Comment by rebeccacremona** [comment]
I suspect something like this will might come in handy https://github.com/harvard-lil/perma/pull/2926/commits/a2e02f69c7bf017c4d8809a8e0c236ee49a41c16
