### ISSUE TITLE
Swallowed stack traces

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1542]
We sometimes get error emails of the form:
```
Internal Server Error: <path>

Report at <path>

Request Method: POST
Request URL: <full URL>
```

No traceback, exception type, etc. Let's see if we can figure out where these internal server errors are being triggered, and what it is we are doing that results in the trace being swallowed.

**Comment by lizadaly** [comment]
Closing because I think Sentry will capture these errors better going forward.
