### ISSUE TITLE
Filter by collaborator in admin uses an invalid through model

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1551]
Filtering by collaborator name in the admin returns:

> Cannot resolve keyword 'casebook' into field. Choices are: casebookfollow, collaborators, common_title, common_title_id, contentcollaborator, contents, created_at, draft, draft_id, draft_of, edit_log, export_fails, headnote, id, old_casebook, old_casebook_id, provenance, state, subtitle, title, title_name, updated_at

from:

```python
return queryset.filter(casebook__collaborators__in=users)
```

Presumably the through model here changed at some point.

**Comment by rebeccacremona** [comment]
Looks like this query got updated from `casebook__collaborators__in` to `collaborators__in` for `CollaboratorIdFilter` in https://github.com/harvard-lil/h2o/commit/3cdb55552066f9916e258cb820bc3e2384bbb1e2, but the matching change was not made for `CollaboratorNameFilter`.
