### ISSUE TITLE
Idea: create PDFs with paged.js

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1555]
https://pagedjs.org/about/
> Paged.js is a free and open source JavaScript library that paginates content in the browser to create PDF output from any HTML content. This means you can design works for print (eg. books) using HTML and CSS!
>
> Paged.js follows the Paged Media standards published by the W3C (ie the Paged Media Module, and the Generated Content for Paged Media Module). In effect Paged.js acts as a [polyfill](https://en.wikipedia.org/wiki/Polyfill_(programming)) for the CSS modules to print content using features that are not yet natively supported by browsers.

See https://github.com/harvard-lil/h2o/pull/1529 for a first swing at this.

**Comment by lizadaly** [comment]
This is done as the PDF export, still in testing, but definitely a viable way forward.
