### ISSUE TITLE
Add full-text search endpoint to the API

### ISSUE THREAD

**Issue by varun-magesh** [harvard-lil/h2o#1568]
There is no way for students or professors to search through the entire text of a casebook. This is a significant advantage of a digital casebook that is currently under-supported. The first step in enabling this functionality is to create an API endpoint that returns the results of a full-text search through a given casebook.

From @lizadaly, casebook metadata search (which is what you can do through the search box on opencasebook.org) is done by:
1. indexing metadata using this sql (https://github.com/harvard-lil/h2o/blob/develop/web/main/create_search_index.sql)
2. recalling metadata using this Django Model (https://github.com/harvard-lil/h2o/blob/develop/web/main/models.py#L752-L881)

On first glance, it doesn't seem like the Model needs to change to do the indexing.

Right now, it seems like the steps here are:
- [x] Expand `create_search_index.sql` to index casebook full-text.
- [x] Write a method that will query casebook texts in the SearchIndex for a given query string
- [x] Expose this method through the h2o API

**Comment by varun-magesh** [comment]
It appears that `create_search_index.sql` is autogenerated by Ruby (now long gone). My options here are probably: attempt to follow the Ruby generation pattern, or experiment with moving searching and indexing both to Django (https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/search/).

**Comment by rebeccacremona** [comment]
If memory serves, @jcushman wrote `create_search_index.sql` by hand. (...and if memory serves, he wrote it on his phone :joy:)

**Comment by varun-magesh** [comment]
that's incredible :joy:

I took: `    -- via app/models/user.rb` to suggest generation by/based on that file --- which I guess is true, in a sense. I'll try to puzzle the straight SQL together then!

**Comment by varun-magesh** [comment]
I have successfully added full-text indexing to legal documents! Unfortunately, in order to make a query like "For all legal documents referenced in X casebook, search Y," it seems like we will need to add some more information to the search indexing. Right now, the data that is in the SearchIndex is purely what is needed to render a search result on the website. There is a result_id that corresponds to the id of the specific resource that is associated with the index. Unfortunately, result_id need not be unique. result_id 10 could correspond to the 10th LegalDocument and also the 10th Casebook, depending on the type of the item in the index. Because result_id does not always point to the same table, it is difficult to use it for joins and potentially impossible to register it as a ForeignKey and get all of the nice Django helpers.

The rest of the information in the SearchIndex is buried in JSON metadata and therefore not easily usable for db operations (as far as I know).

I'm currently trying to find the cleanest way to solve this predicament...

**Comment by varun-magesh** [comment]
Okay! So, I think I realized that this is a limitation of Django ORM and not the DB itself. Django ORM can't register resource_id/result_id as a ForeignKey (and thus select_related) because it points to different tables. However, if we have the right filters, we can still use them to JOIN in SQL as follows:

```sql
SELECT count(*) FROM
    main_contentnode
    INNER JOIN internal_search_view
        ON internal_search_view.result_id=main_contentnode.resource_id
        AND internal_search_view.category='legal_doc'
        AND main_contentnode.casebook_id=CASEBOOK_ID_HERE
        AND main_contentnode.resource_type='LegalDocument'
    WHERE internal_search_view.document @@ to_tsquery('english', 'search query here')
;
```

For example,
```sql
postgres=# SELECT main_contentnode.title FROM
    main_contentnode
    INNER JOIN internal_search_view
        ON internal_search_view.result_id=main_contentnode.resource_id
        AND internal_search_view.category='legal_doc'
        AND main_contentnode.casebook_id=523
        AND main_contentnode.resource_type='LegalDocument'
    WHERE internal_search_view.document @@ to_tsquery('english', 'nonprofit')
;
                                     title
--------------------------------------------------------------------------------
 Universal City Studios, Inc. v. Reimerdes
 Equal Employment Opportunity Comm'n v. R.G. &. G.R. Harris Funeral Homes, Inc.
 Prager Univ. v. Google LLC
(3 rows)
```

This seems really slow on the first try, I'm not sure if the query plan is correct.
```sql
postgres=# EXPLAIN SELECT main_contentnode.title FROM
    main_contentnode
    INNER JOIN internal_search_view
        ON internal_search_view.result_id=main_contentnode.resource_id
        AND internal_search_view.category='legal_doc'
        AND main_contentnode.casebook_id=523
        AND main_contentnode.resource_type='LegalDocument'
    WHERE internal_search_view.document @@ to_tsquery('english', 'nonprofit')
;
                                                        QUERY PLAN

----------------------------------------------------------------------------------------------------------
----------------
 Nested Loop  (cost=0.42..592.91 rows=1 width=53)
   ->  Seq Scan on internal_search_view  (cost=0.00..221.97 rows=30 width=8)
         Filter: ((document @@ '''nonprofit'''::tsquery) AND (category = 'legal_doc'::text))
   ->  Index Scan using main_conten_resourc_697521_idx on main_contentnode  (cost=0.42..12.35 rows=1 width
=61)
         Index Cond: (((resource_type)::text = 'LegalDocument'::text) AND (resource_id = internal_search_v
iew.result_id))
         Filter: (casebook_id = 523)
(6 rows)

```

**Comment by lizadaly** [comment]
I think my local data is slightly different because that exact query returns zero results for me, but `to_tsquery('english', 'law')` returns two results for me in 43 ms, which seems OK to me?

**Comment by varun-magesh** [comment]
Thanks for giving it a run! Good to know. On @rebeccacremona's recommendation, I am moving towards two seperate Indexes --- a full text index and a metadata index --- and using some `prefetch_related` code Jack wrote instead of the raw SQL, but I think the database load should be the same.

**Comment by varun-magesh** [comment]
Ah hah, after much puzzling and Django docs-diving I think I found the Right™ way to do this!

GenericForeignKeys and GenericRelations (along with some magic numbers generated from ContentTypes) let you use a single column as keys for multiple columns, and relate back. This means you can relate LegalDocuments and their associated SearchIndex entries, so you can filter the SearchIndex by information in the LegalDocument before beginning a search on SearchIndex.document.

*see* https://buildatscale.tech/how-to-use-genericforeignkeys-in-django/

I think, unfortunately, that it might take some more puzzling. Only ContentNodes have casebook id's, and ContentNode.resource_category and ContentNode.resource_id are not listed as GenericFKs to LegalDocuments, so it will be tricky to relate LegalDocuments and Casebooks.

**Comment by varun-iyer** [comment]
For now, this is a query that uses GenericRelations to join across LegalDocument and SearchIndex:  LegalDocument.objects.get(id=100).index.all()

**Comment by varun-iyer** [comment]
However, as per https://github.com/harvard-lil/h2o/issues/1035,

jcushman

  

>   Ok, my favorite clean slate polymorphism refactor idea so far is to factor out all the treeish stuff into a TreeNode model
>     Which is just an empty model with whatever django tree library
>     Then things that can be tree nodes (Casebook, Section, Textblock, Link, CaseRef) get a onetoone field pointing to TreeNode
>     No generic relationships, every key is an actual foreign key
>     You can fetch the whole mess efficientlyish with TreeNode.select_related(list of possible node types)
>     I dunno, I think a heterogenous tree is always going to make some things annoying to do efficiently, but having real foreign keys, no inheritance, and tree operations factored out to their own model might help


So maybe we don't want generic relationships? But this was like, October 2019 so....

**Comment by varun-iyer** [comment]
Okay, so I think the best solution for the ContentNode->LegalDocument join is to use the current solution that's already written in (no migration) which looks like this:

```python
legal_docs = [node.resource for node in Casebook.objects.get(id=523).contents.filter(resource_type="LegalDocument").prefetch_resources()]
```
and the prefetch_resources makes the for loop not be a million queries.

**Comment by varun-iyer** [comment]
Argh, this can produce a list of indices but not a QuerySet of indices, which is what needs to be passed into _search. Turning the list back into the query set requires a bunch of __in lookups which seems rather much,
