### ISSUE TITLE
Link search quality is poor because Postgres’ automatic tokenizer handles URLs poorly

### ISSUE THREAD

**Issue by varun-magesh** [harvard-lil/h2o#1605]
Searching for links right now is pretty bad. For example, try searching through casebook #726. Searches for ‘canlii’ in the URL should give you a whole bunch of hits because nearly every url points to canlii.org, but we actually only get a handful of hits because they have CanLII in the title. This is because the tokenizer that Postgres’ search indexing uses is built for English and not URLs. 'www.canlii.org' yields all the expected results. Postgres tokenizes on the '/' correctly but not the dots.

Postgres' parser is pretty inflexible, so he best solution is probably to split the string and then rejoin it on a token-seperating character like " ".

**Comment by varun-magesh** [comment]
I think it's more complex than this because if we turn "www.canlii.com/stuff/more" into "www canlii com/stuff/more" I think we get www and canlii as tokens but we lose postgres' nice URL tokenization for the rest of the url parts.

Either way, problem for later.

**Comment by lizadaly** [comment]
I think this is a good candidate for student-facing user research! Would they expect to search on URLs? If so, what are they looking for?
