### ISSUE TITLE
Add Link needs a title field

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#161]
Currently Add Link doesn't let you custom title the item - needs a field to be able to title it.

**Comment by bjohnson747** [comment]
(also, as of creation of this ticket, 9/21, there's no edit button for editing resources)

**Comment by cgruppioni** [comment]
editing a resource is solved

**Comment by cgruppioni** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix text editor on add-resource, add-text](https://trello.com/c/eobfcaoT/61-fix-text-editor-on-add-resource-add-text)
