### ISSUE TITLE
Investigate absence of exceptions from Sentry reporting

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1637]
A couple error emails came through with no corresponding report in Sentry. We know that Sentry's python SDK is configured correctly after some initial manual testing, but it's possible that Django-level errors are bypassing it. 

* Temporarily configure Sentry reporting in local dev
* Verify that an exception thrown from within a Django request appears in Sentry with the expected stack trace
* If not, look into whether the custom error reporting in `reporter.py` is interfering.

**Comment by lizadaly** [comment]
Resolved by @bensteinberg !

**Comment by bensteinberg** [comment]
Ha and also caused by @bensteinberg
