### ISSUE TITLE
"Search Inside" doesn't appear in Read Resource and Section View

### ISSUE THREAD

**Issue by varun-magesh** [harvard-lil/h2o#1649]
![2022-07-20-193226_841x438_scrot](https://user-images.githubusercontent.com/7690541/180100335-5dbe6a60-4983-414e-8621-f77e25faf0e4.png)

**Comment by varun-magesh** [comment]
Do we want it to show? I can't remember if this decision was intentional --- "Search Inside" is misleading if it seems like it refers to a specific resource.

**Comment by lizadaly** [comment]
I think we don't want it to show in this case since it's an external link.

**Comment by varun-magesh** [comment]
Closing!
