### ISSUE TITLE
Add suggestions for institution

### ISSUE THREAD

**Issue by dongkyunc** [harvard-lil/h2o#1651]
`SELECT affiliation FROM main_user WHERE verified_professor=true;` returns 141 different values for 228 verified professors. Some of the affiliations are 

```
Harvard University
Harvard Law School
Harvard Law School, Berkman Center
HLS/HBS
hls
HLS
Berkman Klein Center for Internet & Society
Berkman Klein Center

Professor, George Washington University

None

[redacted professor1's cv]
[redacted professor2's website]

Magistrate Judge

Financial Regulation: Law and Policy
```

This makes grouping by university kind of hard (unless we want to do it via user email domain?). Providing options assuages the issue somewhat and it seems to be possible from either the [Django](https://django-autocomplete-light.readthedocs.io) end or from [Vue](https://github.com/darrenjennings/vue-autosuggest). I tried wrangling the form for a couple hours but got nowhere.

**Comment by lizadaly** [comment]
@cath9 As a first step, what do you think about cleaning these up manually? We could export these values as a CSV and then make changes in the admin.

**Comment by cath9** [comment]
yep I think that's the only way. Need to think a bit about how to communicate these changed to profs who have already been using the platform. but we should move forward!

**Comment by lizadaly** [comment]
This is fixed; the list of schools in search is now reasonable.
