### ISSUE TITLE
Unpin importlib-metadata

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#1668]
[This python package](https://github.com/harvard-lil/h2o/blob/develop/web/requirements.in#L47) was pinned in a commit called "[Update javascript deps](https://github.com/harvard-lil/h2o/commit/9103342c17a93228a52a1b399c305cb5f1d2348f#diff-e729f1139ce8f2fb9cd2f15b118916790fbad84c557acbd87c734caeefb26df1R33)", with the comment, "Who knows?"

Let's find out.

And, probably, unpin.

**Comment by lizadaly** [comment]
I'm not even sure it's in use at all. It's part of the standard library as of 3.8 and I don't see any references to `importlib` in the source code to begin with.

**Comment by lizadaly** [comment]
I manually uninstalled this locally and tests still pass 100%, so 🤷‍♀️
