### ISSUE TITLE
Ask for user info at sign up

### ISSUE THREAD

**Issue by cath9** [harvard-lil/h2o#1718]
As we are building out more features that are specific to certain types of users, it would be helpful to begin to understand who folks are at sign up. For now, we could just add a multi-select check box on the sign up page, under the email field and above the button, that says:

"I am a
Professor
Student
Librarian
Other"

It would also be helpful to subscribe them to the newsletter. Underneath the "Sign Up" button, please add a pre-checked box that says:

“I would like to receive occasional emails from H2O and its developer, the Harvard Library Innovation Lab.”

**Comment by cath9** [comment]
(You could check CAP sign up flow for how the automatic mail chimp subscription works)

**Comment by lizadaly** [comment]
I'm going to split the newsletter signup into a separate ticket because that will involve help from Ben on an API key, and I have some questions about the signup flow.
