### ISSUE TITLE
Identify restricted content in TOC

### ISSUE THREAD

**Issue by cath9** [harvard-lil/h2o#1746]
Teaching notes are great! I think it would be helpful to add some sort of signifier in the table of contents that a piece of content has been restricted to other verified professors. I'm thinking just a lock that would show up next to the title.

**Comment by lizadaly** [comment]
Here's what I've got on the TOC page: 

<img width="864" alt="image" src="https://user-images.githubusercontent.com/19571/189686502-46b516ce-8ec6-42d6-aa42-4335edb37803.png">


Do you want a notice on the actual content page too? If so, what should it say?

**Comment by cath9** [comment]
Oh this is great. Yea I guess a lock icon somewhere on the page viewable to author and all verified profs might be helpful. Could we drop that where the Resource order is currently listed? It looks like what is shown there is the location of the resource right before it. 

![image](https://user-images.githubusercontent.com/77024527/189690955-30f3d27e-7e54-4e9b-8709-ae45b23b3660.png)

**Comment by cath9** [comment]
The other "nice to have" would be some way to indicate at the point of creation that this resource is a teaching note/restricted content. ie a checkbox in this window. 

![image](https://user-images.githubusercontent.com/77024527/189691433-8b17e5f3-7b9e-4285-97e1-646108ec0b74.png)

**Comment by lizadaly** [comment]
> Could we drop that where the Resource order is currently listed? It looks like what is shown there is the location of the resource right before it.

The behavior of that heading is kinda weird in general since those nodes shouldn't be displaying section numbers at all; see the sections in https://opencasebook.org//casebooks/5959-advanced-evidence-fall-2022/ which were all tagged with "don't display section numbers". I'll see what's going on there.
