### ISSUE TITLE
Collection stats in search UI should reflect the total number of items in the public search index, not the number of items returned

### ISSUE THREAD

**Issue by cath9** [harvard-lil/h2o#1759]
The circled phrase updates based on the number of casebooks surfaced in a specific search. This doesn't quite make sense given how the sentence is written - I think we should just make it a static sentence. 

![image](https://user-images.githubusercontent.com/77024527/190477559-795e42a3-3f1e-419c-aabb-f2c1ed9ced8b.png)

**Comment by lizadaly** [comment]
What should it say? It would be possible to base it on the total number of public casebooks (regardless of the current search), or just be generic.

**Comment by cath9** [comment]
"Static" was probably not the right word - would be great for it to reflect changes in the entire collection as they go. I just don't think it should be responsive to the current search.

**Comment by lizadaly** [comment]
Makes sense, I agree!
