### ISSUE TITLE
A ContentNode should probably always belong to a Casebook

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1777]
Currently, `ContentNode` has:

```python
    casebook = models.ForeignKey(
        "Casebook", ... null=True
    )
```

which means it could potentially have no associated `Casebook` instance.

It's not clear what this would mean in practice. Since `mypy` is configured to understand the Django ORM, this means a lot of potentially-spurious checks are required to ensure that `node.casebook` is non-null.

* Confirm that there's no use case for a null Casebook
* Verify how many, if any, ContentNodes in production have null Casebooks
* Address them or remove orphaned nodes.
* Change the foreign relationship through a migration.

**Comment by rebeccacremona** [comment]
This is another relic of the half-done refactor: there didn't used to be a `Casebook` model: `ContentNode` objects where `node.casebook is None` are the root nodes of those old casebooks. TBD: see this convo in [Slack](https://hlslil.slack.com/archives/C4FE9FL56/p1654269362328759) for a little more detail.

**Comment by lizadaly** [comment]
There are 819 content nodes which don't point back to a `Casebook` out of 737,590 content nodes total: 

```sql
select count(*) from main_contentnode where casebook_id is null; -- returns 819
```


Here's the breakdown by last-mod time:

```sql
select to_char(updated_at, 'YYYY-MM') as date, count(*) as count from main_contentnode 
where casebook_id is null group by date order by date desc;
```
```
  date   | count 
---------+-------
 2020-03 |    31
 2020-02 |   408
 2020-01 |    21
 2019-12 |    31
 2019-11 |    18
 2019-10 |    16
 2019-09 |    15
 2019-08 |   186
 2019-07 |     1
 2019-06 |    82
 2019-05 |     2
 2019-04 |     3
 2019-03 |     4
 2019-02 |     1
```

Most of these seem to be "real" casebooks but are likely clones?

```sql
select title, count(*) as count from main_contentnode where casebook_id is null 
group by title order by count desc;
```

```
----------------------------------------------------------------------------------------------------------------------------------------+-------
 Untitled                                                                                                                               |    51
 Corporations                                                                                                                           |    32
 Constitutional Law                                                                                                                     |    22
 Constitutional Law: Separation of Powers, Federalism, and Fourteenth Amendment - Spring 2018                                           |    18
 Financial Regulation: Law and Policy (2d edition, Foundation Press 2018) by Michael S. Barr, Howell E. Jackson, and Margaret E. Tahyar |    12
 Zittrain Torts Playlist Spring 2018                                                                                                    |    12
 Criminal Law Spring 2017                                                                                                               |    11
 Contracts                                                                                                                              |    10
 Property - Fall 2015 (Bruce Mann)                                                                                                      |     9
 Legislation and Regulation                                                                                                             |     8
 Contracts: Cases and Materials                                                                                                         |     8
 Food Law Casebook                                                                                                                      |     7
 International Law and Human Rights (Fall 2016)                                                                                         |     6
...
```

with a long tail of single instances, many of which are clearly tests (one is titled "Are there 2 of these casebooks?")

I don't see how these content nodes could ever be accessed, and given that they constitute only 0.1% of the content nodes on the site, I think they should be safe to drop them with a data migration, and then update the code to make the field not-nullable. What do other people think?

**Comment by lizadaly** [comment]
Oh I understand the Slack excerpt now; all these content nodes are pointed at by `old_casebook_id` on the `Casebook` model.

**Comment by rebeccacremona** [comment]
I think dropping these would result in broken links for people with old casebooks, those that existed before there was a dedicated `Casebook` model, when `ContentNode`s where `node.casebook is None` were the top of the content tree. (There's a bit more discussion [here](https://hlslil.slack.com/archives/C4FE9FL56/p1654269362328759) but might be confusing).

I think people used to be able to get to these casebooks using the ContentNode id of the root node, and that there is still a mechanism for making those urls work, via [`old_casebook`](https://github.com/harvard-lil/h2o/blob/develop/web/main/models.py#L2012) and, I think, [this stanza](https://github.com/harvard-lil/h2o/blob/8475e51fb2876b70d1cabbf73be6c9beb5a9ce4e/web/main/views.py#L177-L195).

If we want to drop the `ContentNode` objects, which I too think we should, I think we should alter this redirection/lookup so that people can still access old casebooks at their original URLs.

**Comment by rebeccacremona** [comment]
Ah whoops, I drafted my comment before seeing your followup 😄

**Comment by lizadaly** [comment]
Here's the breakdown for affected casebooks by their publication status and whether the author is a verified professor:

```sql
select u.verified_professor, c.state, count(*) from main_contentnode cn 
  join main_casebook c on c.old_casebook_id = cn.id 
  join main_contentcollaborator cc on cc.casebook_id = c.id 
  join main_user u on u.id = cc.user_id 
where cn.casebook_id is null group by c.state, u.verified_professor;
```

```
 verified_professor |  state   | count 
--------------------+----------+-------
 f                  | Archived |    11
 t                  | Archived |    20
 f                  | Clone    |   208
 t                  | Clone    |   130
 f                  | Draft    |    28
 t                  | Draft    |    24
 f                  | Fresh    |   167
 t                  | Fresh    |    44
 f                  | Public   |   112
 t                  | Public   |   232
 f                  | Revising |     3
 t                  | Revising |     2
```

Of note, there are 232 that are public and by verified professors are probably discoverable in search.

**Comment by lizadaly** [comment]
Those URLs generated in search would be the new-style, not affected by any changes. But they might be otherwise linked out in the universe.

**Comment by lizadaly** [comment]
One option for resolving this would involve generalizing the feature that allows a single casebook to have multiple identifiers—either its real `Casebook.id` field, or `old_casebook_id` today—into a more explicit alias function.

I'm wondering about introducing a Casebook string field like `url_alias`, that gets  initially populated for the 831 legacy casebooks with their legacy-style slug (e.g. '[200118-federal-rules-of-evidence](https://opencasebook.org/casebooks/200118-federal-rules-of-evidence/)') and issues a 301 redirect to the canonical URL when visited.

The `url_alias` could accept a regular expression, so if expressed as `200118.*`, both `200118` and `200118-federal-rules-of-evidence` would resolve.

As part of this work, we'd drop the code that tries to resolve a casebook identifier via the `old_casebook` field and instead rely only on `url_alias`.

In subsequent PRs:

* drop the `old_casebook` field from the model
* change the `ContentNode` model to require a non-null `Casebook` id
