### ISSUE TITLE
Handle links in printable HTML view

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1783]
We have 5 possible ways to make links:

1.  The link resource type, which appears as a standalone item in the table of contents
2.  The link annotation type, which is added using the annotation tool
3.  Adding a link via the WYSIWYG editor tool
4.  Adding a link by pasting existing content with links into the editor
5.  Importing content that has existing links (unsure if this happens in practice with our imported content, but it's certainly possible)

It's tricky to get a count of the number of uses of 3-5, but there are 275,023 link resource types and only 4,000 uses of #2. 

Examples from the Word export:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/19571/192840262-11720b58-479e-49af-bf5c-9d5c0ed59189.png">

The URL then appears as a footnote:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/19571/192842039-25bbd47e-4c87-4cb4-bd86-4acf41cafe26.png">

Link resource:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/19571/192840302-790854b1-d9b3-4519-b613-232e06e3b0fd.png">

It's probably not ideal that these all behave differently, though the link resource type does have special weight and may have associated metadata. The remaining cases should probably all be treated the same.

I think the main decision points are:

* Should the URL be inline with the linked content, or footnoted like the current export?
* Should the link target (the underlined bit) be visually represented in the text?

Should look into how other publishing guidelines handle links in print, especially in a book context.

**Comment by lizadaly** [comment]
[Bluebook](https://www.legalbluebook.com/bluebook/v21/quick-style-guide) footnote citation style for URLs (see also [this video](https://www.youtube.com/watch?v=06hkkPtNS4Q&list=PLdMU7nuDBQKT_U5yPYzONxVgVwXp1OPN8&index=5)):

```
Ben & Jerry’s, http://www.benjerry.com/ (last visited Oct. 6, 2008).
```

We could inject a date from when the link was created, though it seems a stretch to call it "last visited" since we can't be sure the author actually did so. We also won't have a reliable title.

[Pressbooks](https://opentextbc.ca/accessibilitytoolkit/chapter/links/#provide-links) recommends putting the URL inline.

I did an informal survey of about 5 recent non-fiction books in my house (both academic and trade) and URLs were universally presented as footnotes or endnotes.

**Comment by cath9** [comment]
I think we do our best to intuit how the author intends this material to fit into the book, and use that to decide how to handle. In my mind that means:

Link resource types - the link is included in line and fairly prominently. 
Links as annotations - the link is surfaced in a footnote
Links in the editor - this one is tricky but I think I'd vote for a footnote at least as the platform is currently configured. 

In terms of how to format the footnote, I would vote that we format it a bit differently to prioritize visibility of the link itself. I imagine the author is including the link in annotations/text editor as options for further reading, not a citation, so I don't feel that we need to follow the traditional citation format for links. Something like the below, perhaps?

http://www.benjerry.com (Ben & Jerry’s, link created Oct. 6, 2008)

**Comment by lizadaly** [comment]
I agree with all this! 

Getting the page titles is tricky for a mix of boring technical reasons and because many HTML page titles are non-sensical or generic. But I like "link created" and that's easy to add.

I think when we can do this with Perma integration we'll have more options for adding additional info.
