### ISSUE TITLE
Revisit the inclusion of headnotes with every resource

### ISSUE THREAD

**Issue by cath9** [harvard-lil/h2o#1785]
Understand how headnotes and text fields behave differently and make some choices about what kinds of resources really need both. I also think it might be worth considering renaming headnotes to something that better describes their functionality within H2O. I understand the terminology and placement is meant to echo traditional casebooks, but I'm not sure it makes sense for us, at least anymore.

**Comment by lizadaly** [comment]
What kind of analysis would be helpful in making a decision here?

**Comment by cath9** [comment]
some data on how frequently headnotes are used across resource type would be helpful - but I think the key though would be to put less stock in how they _are_ being used and more in how they _should_ be used. I think people drop text there because its the first text box, without understanding that text there behaves a bit differently. So I think the main analysis will be our own in terms of what kinds of content should go where. I'm happy to lead that (though would be interested in your take based on past experience) once somebody is ready to work on this.

**Comment by lizadaly** [comment]
Here are some counts:

```sql
select count(*) as count, resource_type, (case when headnote is null then false else true end) as has_headnote from main_contentnode group by resource_type, has_headnote;
```

```
 count    | resource_type | has_headnote 
----------+---------------+--------------
  118,349 | LegalDocument | f
   61,451 | LegalDocument | t
   48,263 | Link          | f
  226,760 | Link          | t
   18,403 | Section       | f
   15,501 | Section       | t
    2,916 | Temp          | f
   47,706 | TextBlock     | f
  136,492 | TextBlock     | t
   37,325 |               | f
  114,110 |               | t
```

I'm not actually sure what the last two items represent; those appear to be sections but I'm not sure why they aren't labeled as such.

**Comment by cath9** [comment]
oh dang, lots of headnotes. I think this is going to take some manual review to understand what's going on (ie if people are using headnotes for a different thing than text fields, or if they're just using headnotes because its the first text field they encounter). If you're looking to work on this soon I can prioritize that review this week. The other thing that would be helpful from the code side is to confirm when/how the two fields behave differently - I have a general idea but I'm sure there are things that aren't top of mind.

**Comment by lizadaly** [comment]
It's harder to look at the text fields in aggregate because they're stored in different places, but here's links:

```sql
postgres=# select count(*) as count, (case when headnote is null then false else true end) as has_headnote, (case when
 description is null then false else true end) as has_description from main_link inner join main_contentnode c on 
c.resource_id=main_link.id where c.resource_type = 'Link'  group by has_description, has_headnote;
```

```
 count  | has_headnote | has_description 
--------+--------------+-----------------
  13353 | f            | f
 220317 | t            | f
  34910 | f            | t
   6443 | t            | t
```

**Comment by lizadaly** [comment]
I was not planning on working on this soon, just wanted to provide some raw data!
