### ISSUE TITLE
Don't display the pre/post publication messages more than once per casebook

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1833]
Right now the pre-publication check comes up each time a book is published, even if it has been published before.

The messaging is somewhat verbose, so let's only show it the first time.

**Comment by lizadaly** [comment]
@cath9 Should we have no confirmation at all if you are re-publishing, or still have a confirmation popup but just with minimal text?

**Comment by cath9** [comment]
Short answer - no confirmation, please

Long answer - a complication here is that the button people push when they want to "publish" their revision probably shouldn't say "publish" but rather "update" or something similar. Nobody considers what they're doing when they push that button from a revision draft to be publishing in any formal way, they're just making edits. When I think we could introduce a pop-up again is if somebody fully unpublishes their book and then publishes it again. But, my understanding is that those two functions aren't differentiated in the code so for now let's just say one set of pop ups after the initial publication.
