### ISSUE TITLE
Write exported PDF to block storage

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1890]
The Playwright-driven endpoint should be modified to write its file output to block storage (S3 or minio).

Should this be a new bucket? 

Advantages:

* Can set specific lifecycle and access control policies for this bucket 
* Less likely to interfere with existing export flow

**Comment by bensteinberg** [comment]
My perhaps low instinct was to reuse the existing buckets in minio and S3, but it's trivial to set up new ones.

**Comment by lizadaly** [comment]
I'd certainly feel a lot more confident with a separate bucket that was isolated from the existing one, but it's true it's still possible to set up most policies at the object rather than bucket level. Your call!

**Comment by bensteinberg** [comment]
I'm very happy to set up new buckets -- I think the first step is to set up the new minio bucket in dev, and then I'll make S3 buckets and configure settings in salt. That is, whoever's writing the feature should probably set up the minio bucket. @rebeccacremona may know most about doing so.

**Comment by rebeccacremona** [comment]
Yeah, I am happy to add a new bucket to the minio setup. IIRC this is not the DRYest thing we have set up.

**Comment by lizadaly** [comment]
This is done!
