### ISSUE TITLE
Poll or wait for completion of async PDF generation job

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1891]
Generating a PDF title will trigger the following workflow:

* An HTTP request to the "generate PDF" endpoint 
* A celery job will be queued to start the Playwright (#1801) 

The job will either write a completed PDF, error, or time out.

If the job succeeds: 

* A PDF will be available on block storage.
* A URL to the PDF should be delivered to the end user that they have permission to access.

If the job errors: 

* The user should be notified and the error should be propagated.

If the job times out:

* The user should be notified and the timeout should be raised as an error.

**Comment by lizadaly** [comment]
There are lots of implementation options for polling for job completion. What do the other projects do?

**Comment by rebeccacremona** [comment]
> There are lots of implementation options for polling for job completion. What do the other projects do?

Perma tracks every request to make a Perma Link in a [CaptureJob](https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/models.py#L1835) table. As the job runs, we update its [status](https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/models.py#L1842) field, along with some [progress indicators](https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/models.py#L1855). That info is exposed in an [API route](https://github.com/harvard-lil/perma/blob/develop/perma_web/api/views.py#L259). The frontend's JS hits that route [every so often](https://github.com/harvard-lil/perma/blob/develop/perma_web/static/js/create-link.module.js#L70) and advances a progress bar; we've heard some feedback that the progress bar isn't the best design choice. 

The [prototype capture service](https://github.com/harvard-lil/perma-capture/tree/new-arch-with-vue) is set up the same way, but is tidier, including a [Vue frontend](https://github.com/harvard-lil/perma-capture/tree/new-arch-with-vue/web/frontend).

As far as I know, CAP doesn't have any user-facing tasks or polling; probably worth confirming that with someone else.

**Comment by lizadaly** [comment]
This is done!
