### ISSUE TITLE
Improve performance and responsiveness of "add content" button when selecting cases

### ISSUE THREAD

**Issue by lizadaly** [harvard-lil/h2o#1933]
When adding new case content using the Quick Add or Add Content feature, the user is prompted to do a search for a case, then select the matching case by clicking on it.

The behavior of this feature could be improved:

* Some UI hints are missing that the region is clickable
* There is no visible response from the UI after you click
* There is a significant delay between clicking and loading the case

The last two items together mean users often click repeatedly and overall the app looks buggy and not responsive.

**Comment by cath9** [comment]
note this issue is more apparent when adding cases through the "Add Content" window, because for some reason the load times there are longer, though both would benefit from the UI work outlined above.
