### ISSUE TITLE
Give permission for Research Assistants to add image/video

### ISSUE THREAD

**Issue by cath9** [harvard-lil/h2o#2016]
Currently, we restrict the ability to upload images and embed videos to Verified Professors. However, many professors work with RA's to create their books, and ideally those RA's would also have permission to upload images and add videos. To solve this problem, we need to:

- Create a new Group called Research Assistants (done)
- Give that group image and video permissions

**Comment by lizadaly** [comment]
Group name is "Research Assistant" (this will have to be an exact string match in the template).
