### ISSUE TITLE
Dashboard: display only title, author, school and attribution

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#285]
Either we should not display subtitles or we should limit characters or handle overlap

![h2o-funky-dashboard](https://user-images.githubusercontent.com/2140548/39432111-a21c91c8-4c60-11e8-9cf5-ed1aac49774e.png)

**Comment by leppert** [comment]
Okay to broaden the scope of this ticket to deal with text truncation generally? 
<img width="1253" alt="screen shot 2018-06-19 at 9 15 35 pm" src="https://user-images.githubusercontent.com/26643/41632155-84657938-7406-11e8-8345-3ea63b960d83.png">

**Comment by leppert** [comment]
@abziegler @cgruppioni bump

**Comment by abziegler** [comment]
Yes, absolutely @leppert. Let me know if you need any add'l input from us on how this might affect more than dashboard/bookshelf display.
