### ISSUE TITLE
Enable authors to delete and to depublish their casebooks

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#287]
**Story**

Authors should be able to remove (unpublish) casebooks or delete them entirely.

**Background**

Authors should have full control over their casebooks, including ability to delete and to depublish. Right now, once authors publish a book, they can't delete or depublish. 

**Goals**

Enable casebook deletion and depublishing by authors. 

**Requirements/Constraints/Gotchas**

- Guardrails - UI should caution author about deleting or depublishing casebook (look at deleting a repo in github or heroku for reference)
- Soft Delete and Recovery - Use delete flag rather than hard delete, to ensure h2o team can recover soft deleted casebook if needed
- Make sure to handle all nested resources of a deleted / depublished casebook
- Make sure to handle pending revision drafts of a deleted / depublished casebook
- Make sure no impact on clones of deleted / depublished casebook (and consider how to display a disappeared casebook in ancestry/attribution)

**Comment by cgruppioni** [comment]
https://github.com/jhawthorn/discard

**Comment by cgruppioni** [comment]
Can potentially use /`h2o/lib/deleted_item_extensions.rb`
