### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#288]
See trello list

**Comment by rebeccacremona** [comment]
@cgruppioni  got the ball rolling on this via the mammoth task of removing turbolinks, which improved things drastically!

Over the past couple of weeks, I made a first pass through the student-facing pages. See Trello for an updated state-of-affairs. There's still a bunch to do, TBD whether any cards are considered show stoppers. If time allows, I think there are maybe 2 things it would really be best to address pre-launch, both related to annotations: notes and highlights.
