### ISSUE TITLE
Annotations: textblocks: deleted text leads to error

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#289]
For annotating a textblock - if you delete text that has an annotation you get an error page when trying to view the textblock (because it's searching for the coordinates of an annotation that doesn't exist anymore)

**Comment by cgruppioni** [comment]
This error ```An ActionView::Template::Error occurred in resources#annotate:

  undefined method `each_with_index' for nil:NilClass
  app/models/content/resource.rb:78:in `block in annotated_paragraphs'``` only happens now when all of the text in a textblock has been deleted. 

The real issue is if a user deletes text that has been annotated the annotation will stick to the line number that is original was assigned, and will then annotate other text.

**Comment by cgruppioni** [comment]
see #348 for next steps
