### ISSUE TITLE
Elisions moving by a character

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#290]
- [x] Elisions moving over by 1 or more characters. [Info in this comment](https://github.com/harvard-lil/h2o/issues/290#issuecomment-399560616).

- [x] Removing an elision higher up in a paragraph moved a elision later in that paragraph _back_ a character. [Info in this comment ](https://github.com/harvard-lil/h2o/issues/290#issuecomment-407478922) Ex: Create an elision, second elision must be created one character later, third elision must be 2 characters later. 
-----
check out #392 - styled text might be the issue here, causing elisions to move over a few characters.

**Comment by bjohnson747** [comment]
Good test example, based on a case I just ingested: [This case](https://alpha.opencasebook.org/casebooks/60627-constitutional-law-separation-of-powers-federalism-and-fourteenth-amendment-spring-2018/resources/13-james-obergefell-et-al-petitioners-v-richard-hodges-director-ohio-department-of-health-et-al-valeria-tanco-et-al-petitioners-v-bill-haslam-governor-of-tennessee-et-al-april-deboer-et-al-petitioners-v-rick-snyder-governor-of-michigan-et-al-and-gregory-bourke-et-al-petitioners-v-steve-beshear-governor-of-kentucky/annotate) - 

Can't re-create this issue in the body of the case, but the case title (the long title of 'Obergefell v Hodges') continually moves the elision over by two, or more, characters, when characters are elided.

It FELT like it occurred less frequently times when i changed the header's (center) tag to (h2 style="text-align: center;") but still occurred. I think something about the annotate javascript on the header seems to be causing it.

**Comment by bjohnson747** [comment]
Adding a comment to check out #392 - styled text might be the issue here, causing elisions to move over a few characters.

**Comment by bjohnson747** [comment]
_tags affecting annotations_

 This work was put in to see if a data issue in cases was prompting this, on behalf of issue #310. It does not appear to be a data issue but instead how H2O's annotator is treating tags. I've put a good chunk of time into testing this but still can't state with full confidence what causes elisions to be slightly off. Here are my findings so far.

In these examples, the elision is currently moving over by one character.
Original HTML:

<img width="381" alt="screen shot 2018-06-22 at 11 52 00 am" src="https://user-images.githubusercontent.com/12850389/41786439-7a7690a6-7613-11e8-8bac-60be5c6e4fd9.png">
My desired elision (only 't' excluded):

<img width="394" alt="screen shot 2018-06-22 at 11 53 20 am" src="https://user-images.githubusercontent.com/12850389/41786440-7a829108-7613-11e8-8d26-bfb440c59c10.png">
actual elision (excludes both 'r' and 't'):

<img width="325" alt="screen shot 2018-06-22 at 11 53 30 am" src="https://user-images.githubusercontent.com/12850389/41786441-7a91f224-7613-11e8-9157-f30b5bcb5e53.png">

(I use this example in all my tests, with the same elision as my goal: "No " through "court", excluding the t in court.)

-----------------------------
When this phrase was tagged with JUST < center> tags: 
<img width="419" alt="screen shot 2018-06-22 at 12 25 56 pm" src="https://user-images.githubusercontent.com/12850389/41794206-9f5b7bfc-762c-11e8-841b-2a067070072f.png">
it elided fine.
When this phrase was tagged with JUST < p> tags, it elided fine.
When this phrase was tagged with < p> tags and < b> tags, it elided fine.

-----------------------
It seems like if there is a tag or tag set within the section's being elided, that can affect elisions, but this isn't always consistent.

Here, i added four < br> tags:
<img width="575" alt="screen shot 2018-06-22 at 2 54 46 pm" src="https://user-images.githubusercontent.com/12850389/41794903-f19e9ed8-762e-11e8-8748-ae4314bcf984.png">

And it moved the elision over one character: 
<img width="376" alt="screen shot 2018-06-22 at 2 55 25 pm" src="https://user-images.githubusercontent.com/12850389/41795061-80491f50-762f-11e8-92b2-c1e34edda378.png">

Here I added three more < br> tags, and it moved the elision over seven (eight?) characters:
<img width="435" alt="screen shot 2018-06-22 at 2 56 32 pm" src="https://user-images.githubusercontent.com/12850389/41795117-a7336bb6-762f-11e8-8892-e55d36d73fe4.png">

-------------------------------
I discovered a few contexts where annotation sidebar doesn't appear:

EXAMPLE 1: Each sentence had their own < center> tag originally.When i removed one set of the < center> tags, ex.:

<img width="353" alt="screen shot 2018-06-22 at 12 13 22 pm" src="https://user-images.githubusercontent.com/12850389/41787444-782464e2-7616-11e8-8e79-c1d7e62428fd.png">

The annotation sidebar does not appear when i select beyond the < center> , into the next line's < p> text:

<img width="559" alt="screen shot 2018-06-22 at 12 16 03 pm" src="https://user-images.githubusercontent.com/12850389/41787582-d3c19ab8-7616-11e8-84e6-5bb6abdcdb9b.png">


EXAMPLE 2: I added a < br/> tag to text that was eliding fine:
<img width="326" alt="screen shot 2018-06-22 at 3 10 08 pm" src="https://user-images.githubusercontent.com/12850389/41795544-266781c8-7631-11e8-81b5-4a9ef4258cdb.png">

 and now when I try to click-and-drag past the first line, the annotation sidebar disappears:
<img width="912" alt="screen shot 2018-06-22 at 3 10 40 pm" src="https://user-images.githubusercontent.com/12850389/41795547-28f22a42-7631-11e8-909e-1d3ef8627890.png">

(BUT when I click-and-drag beyond this phrase, annotation sidebar reappears:
<img width="928" alt="screen shot 2018-06-22 at 3 33 26 pm" src="https://user-images.githubusercontent.com/12850389/41795698-adc3dc52-7631-11e8-9a32-2563e1a2b0c1.png">

**Comment by bjohnson747** [comment]
Another example found by a user - it was mostly case headers in various cases that were affected by this. I corrected the affected headers, and examples in case body text, best I could. Here's an example they found that I've since manually done my best to correct.

[PELL v KILL in old H2O](https://h2o.law.harvard.edu/collages/41403):
<img width="766" alt="screen shot 2018-07-12 at 1 44 06 pm" src="https://user-images.githubusercontent.com/12850389/42668750-48116754-8620-11e8-87d0-537db45d281a.png">

[PELL v KILL](https://alpha.opencasebook.org/casebooks/72837-an-introduction-to-the-law-of-corporations-cases-and-materials/resources/7.2.5-lewis-c-pell-plaintiff-v-robert-c-kill-kenneth-h-paulus-kevin-h-roche-and-james-p-stauner-defendants-and-cogentix-medical-inc-nominal-defendant/annotate) in NEW H2O:
<img width="845" alt="screen shot 2018-07-12 at 1 44 42 pm" src="https://user-images.githubusercontent.com/12850389/42668751-4bcdd17a-8620-11e8-92d8-5d6bb6d1a45c.png">

**Comment by bjohnson747** [comment]
More findings:

When i deleted an elision annotation above another elision in the same paragraph, the below elision moved back one character. 
Originally:
<img width="712" alt="screen shot 2018-07-24 at 12 56 12 pm" src="https://user-images.githubusercontent.com/12850389/43154241-b3048ce2-8f41-11e8-9c31-3266c8e0f65f.png">

After deletion: 
<img width="783" alt="screen shot 2018-07-24 at 12 57 05 pm" src="https://user-images.githubusercontent.com/12850389/43154253-b7a91c5e-8f41-11e8-89a1-b59664c8d6dd.png">

**Comment by cgruppioni** [comment]
Issue 2: create an elision, second elision must be created one character later, third elision must be 2 characters later.

**Comment by cgruppioni** [comment]
( This ticket could've used links to casebooks with this active issue )
