### ISSUE TITLE
Dashboard: author name not rendering on same casebooks

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#292]
![image](https://user-images.githubusercontent.com/2140548/39441274-612854c0-4c7b-11e8-971c-dd1ae89c3877.png)

**Comment by bjohnson747** [comment]
@abziegler was this my screengrab that you added arrows to? I believe I corrected it for this user on the admin side by adding their name into the Attribution field (https://alpha.opencasebook.org/users/101023)

**Comment by abziegler** [comment]
Not your screengrab. But the broader point is that if we are missing the data we should adjust the template rather than show begging space

**Comment by abziegler** [comment]
closed as resolved
