### ISSUE TITLE
Authors without an attribution do not show up in search results 

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#293]
Not all authors are showing in results - e.g. author of this book: https://alpha.opencasebook.org/casebooks/16339-law-and-rhetoric

**Comment by bjohnson747** [comment]
@abziegler this I also believe was corrected by me entering the author's name in the Attribution field via admin interface

**Comment by cgruppioni** [comment]
When `verified_professor` is set to true on a user, the search index needs to be reindexed so that the user shows up in the results. So @bjohnson747 or @abziegler need to let Ben know so he can reindex Solr.

**Comment by abziegler** [comment]
I don’t follow. Are you saying we have to reminded every time we verify a new prof?

Adam

Sent from my iPhone

On Jul 16, 2018, at 4:21 PM, Casey <notifications@github.com<mailto:notifications@github.com>> wrote:


When verified_professor is set to true on a user, the search index needs to be reindexed so that the user shows up in the results. So @bjohnson747<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bjohnson747&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=L2BFIPrkBo01CizbIgIpehtskIAYV-lPEg8panTt9AA&m=5x_uI0lS8VpqQhw3GYd8XkETA4FUeXHN7_yUCnCwJS8&s=hmTJgoiTfwexSKqWP9agOwWtxH1cev4Uy7tg2Drnjjs&e=> or @abziegler<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_abziegler&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=L2BFIPrkBo01CizbIgIpehtskIAYV-lPEg8panTt9AA&m=5x_uI0lS8VpqQhw3GYd8XkETA4FUeXHN7_yUCnCwJS8&s=0KzdUvmT7ST-hNjB_ZrGbfPkGUVeUtoS8cgtGs1I2DQ&e=> need to let Ben know so he can reindex Solr.

**Comment by cgruppioni** [comment]
@abziegler If you want it to show up in search, you would need to tell Ben after you verify a professor. 

It would be a good chunk of work to automate this

**Comment by cgruppioni** [comment]
Partially solved by #798

**Comment by cgruppioni** [comment]
To prevent authors not having their attribution filled in, do we want to add the field to the sign up page and make it mandatory?

**Comment by abziegler** [comment]
Attribution should be mandatory for verified authors ... but we can enforce that w/o code right?

**Comment by cgruppioni** [comment]
@aziegler I could see that on the Set Password page

**Comment by cgruppioni** [comment]
Closing ticket because some of the issue has been solved, remaining work in #833
