### ISSUE TITLE
Annotations: after annotation, should not jump to top of document

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#295]
I made an elision in a case. After submitting the annotation, page reloaded and jumped to top of document, losing my location. 

What should happen is window should stay at location of annotation after annotation is submitted

This may be related to Turbolinks and/or to this commit: https://github.com/harvard-lil/h2o/commit/51f8ecb3b98ace35620fe52419016572845204aa

**Comment by cgruppioni** [comment]
- Doesn’t jump on Chrome (very smooth) (edited)
- Doesn’t jump on Safari (with some slightly weird page reload behavior) (edited)
- Does jump on Firefox Developer edition incognito
- No annotation menu at all on regular Firefox

**Comment by cgruppioni** [comment]
![screen shot 2018-05-31 at 11 05 28 am](https://user-images.githubusercontent.com/14900328/40790297-8ded346c-64c2-11e8-83cf-4b345597ee1c.png)
I'm getting the menu on regular firefox

**Comment by bjohnson747** [comment]
@abziegler @cgruppioni based on my work on yesterday #362 , Firefox 36.0.1 gave me no menu but when i uninstalled FF and reinstalled it from the web (v60.0.1), i got a menu. For some reason my automatic update didn't work, i had to reinstall FF.

Looks like right now, having an un-updated Firefox (and possible Safari) browser can prevent full H2O functionality.

**Comment by cgruppioni** [comment]
Waiting on a PR from Becky

**Comment by rebeccacremona** [comment]
As of https://github.com/harvard-lil/h2o/commit/ce09ef4a0bc5db7c78d144d76d652bd3501be5e2, this should work now...... Let's hope and let's test!

**Comment by rebeccacremona** [comment]
That is to say, the focusing on replacement annotations part. No idea what's up with the missing menu on Safari, didn't look at that.
