### ISSUE TITLE
CSS: use consistent font families in resources

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#297]
e.g. at least some `<p>` and `<blockquote>` have different font families:

https://h2o-dev-test.lil.tools/casebooks/16066-corporations/resources/6.3.2-the-yates-memo-corporate-vs-individual-criminal-liability

**Comment by rebeccacremona** [comment]
I think I fixed this in https://github.com/harvard-lil/h2o/commit/a81c3c3c68e9e00c29fcdc591995628797dda0cd. Does that link look good to you now?
