### ISSUE TITLE
Admin: give admins view and edit rights to all H2O content

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#298]
Including:
- casebooks (published and draft)
- headnotes
- texts

**Comment by cgruppioni** [comment]
Admin can only edit casebook when clicking the "edit in app button". Just by being logged in they can't see and edit a casebook.

**Comment by abziegler** [comment]
Rails admin should also allow editing of non-sensitive user info, like professor verification status

**Comment by abziegler** [comment]
Casey will fix the routing; then we'll examine functionality; if too gnarly, then we'll defer the issue
