### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#299]
Improvements/fixes to casebook nav breadcrumbs
- Add titles 
- Add more space for double-digit numbers
![h2o-breadcrumbs](https://user-images.githubusercontent.com/2140548/39443802-b1780562-4c83-11e8-903d-c2fdc487d0a9.png)

**Comment by rebeccacremona** [comment]
Room added for breadcrumbs of any digits here: https://github.com/harvard-lil/h2o/commit/27969f53538d99dc717a3ad23e152ca40be1dcd0#diff-cdf8f71ed28044bc975267383bc27340L239.

**Comment by abziegler** [comment]
closed as resolved
