### ISSUE TITLE
Annotations: handle paragraph numbers on elided text

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#300]
Paragraph numbers disappear on elided text, when that text is displayed. Paragraph numbers should display if the text displays.

![image](https://user-images.githubusercontent.com/2140548/39443900-e86a949a-4c83-11e8-84f2-1d8bce1ef990.png)

**Comment by rebeccacremona** [comment]
Actually, it looks like I forgot to reveal paragraph numbers for replacements. Will fix shortly.

**Comment by rebeccacremona** [comment]
Extra handling for replacement elisions on author-facing views https://github.com/harvard-lil/h2o/pull/381.
