### ISSUE TITLE
Annotations: replace text

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#303]
Cursor should change to show action available or should auto-click into field

**Comment by cgruppioni** [comment]
Status notes:
* cursor changed 
* I'm not sure if auto-clicking into field is possbile because it's a `<span>` not a form or input box

**Comment by cgruppioni** [comment]
PR #365 solves changing the cursor and passing in the annotation_id to the URL params. 
The issue will be fully resolved in combination with another ticket
