### ISSUE TITLE
Export: Notes and Links

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#307]
On export, notes and links added to a resource via annotation are not present in the export file.  They should be present, though not sure where/how. Possibly as ** following the resource?

**Comment by cgruppioni** [comment]
Notes/links show up on bottom of page or bottom of document?

**Comment by abziegler** [comment]
Page is preferred.

**Comment by cgruppioni** [comment]
- [ ] notes and links show an asterick where the annotation lives (maybe have to do numbers?) 
- [ ] notes and links show on bottom of page, full text with the same number of astericks

show up on bottom of the case

**Comment by cgruppioni** [comment]
/Users/cgruppioni/lil/h2o/lib/htmltoword/xslt/h2o/export.xslt
/Users/cgruppioni/lil/h2o/lib/htmltoword/xslt/base.xslt

https://www.mulberrytech.com/quickref/XSLT_1quickref-v2.pdf
https://docstore.mik.ua/orelly/xml/xmlnut/ch08_07.htm
https://www.w3schools.com/xml/xsl_elementref.asp
