### ISSUE TITLE
Data: resolve all duplicate cases

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#311]
We want H2O to contain 1 and only 1 canonical version of any case; unfortunately, under old H2O, multiple versions of cases were allowed. Those multiple versions are baked into casebooks now, and they propagate with clones, new editions, etc. It would be good to assess all of the duplicate cases and choose 1 to be the canonical going forward; then to “de-publish” the rest, which will not disrupt existing uses but will prevent their addition to future casebooks. A starting point might be to generate a spreadsheet of all cases with non-unique citations or casenames, with links to the cases in H2O, then we can plow through and anoint one version as canonical and depublish the rest?

At a minimum we should make it impossible for authors to use duplicates going forward.

**Comment by cgruppioni** [comment]
duplicate cases

**Comment by cgruppioni** [comment]
Think about private cases

**Comment by rebeccacremona** [comment]
(transferring from Slack) jcushman says: I like the idea of using CAP ID to establish identity across duplicate cases … trickiness would be (a) any cases that aren’t in CAP and (b) would want to make sure there was still some flag to identify cases that in fact came from CAP

Now that we have more-robust annotation shifting, we could also experiment with consolidating duplicate cases! it might just work in a lot of cases.
