### ISSUE TITLE
Creating new casebook from scratch creates 2 casebooks

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#320]
When clicking Create Casebook 'From scratch,' it creates two new casebooks.

Clicked Create Casebook -> From Scatch. Named it My New Casebook:
<img width="1028" alt="new casebook from scratch" src="https://user-images.githubusercontent.com/12850389/39641840-99c8882a-4f9d-11e8-9359-47495ea25088.png">

When i returned to dashboard, there was both Untitled #56609 and 56610 ('My New Casebook') created.
<img width="502" alt="new casebooks" src="https://user-images.githubusercontent.com/12850389/39641881-c8a6ec0e-4f9d-11e8-822f-9a2ff31f5b8c.png">

links to these: 
https://alpha.opencasebook.org/casebooks/56609-untitled-casebook-56609/layout
https://alpha.opencasebook.org/casebooks/56610-my-new-casebook/layout

**Comment by abziegler** [comment]
I reproduced this bug.
