### ISSUE TITLE
Clicking 'Revise' in Preview mode creates additional casebook clone

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#321]
When in the Preview view (casebook is a draft), there's a Revise button that a user can click on. 

Clicking Revise should return user to preview mode, but instead it activates the Creating Draft modal, and another draft is created.

PREVIEW VIEW: of #56610 My New Casebook
 :
<img width="1036" alt="preview view of draft" src="https://user-images.githubusercontent.com/12850389/39642100-8061f5c8-4f9e-11e8-8cb0-a1c2524f81f0.png">

'Building Draft' modal that appears when Revise is clicked:

<img width="700" alt="screen shot 2018-05-04 at 1 21 52 pm" src="https://user-images.githubusercontent.com/12850389/39642113-8c4cf662-4f9e-11e8-8394-c52eff9100e2.png">

This created new casebook #57026 (https://alpha.opencasebook.org/casebooks/57026-my-new-casebook/layout), 
alongside the #56610 i had been working on (https://alpha.opencasebook.org/casebooks/56610-my-new-casebook/layout).

**Comment by abziegler** [comment]
Reproduced this bug.

**Comment by abziegler** [comment]
I think maybe "Preview" should open a Read version of the casebook in a new browser tab. That Read version should not have any of the action buttons available to a non-author. This is related to Issue #315
