### ISSUE TITLE
Can't delete items (sections/resources)

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#322]
1) Created new sections in a new casebook. When i clicked the (X) on a section, it didn't remove it.

Tried to delete: 

<img width="853" alt="deletion attempt" src="https://user-images.githubusercontent.com/12850389/39642565-211e639c-4fa0-11e8-86e1-23ff47350130.png">

Clicked delete, section remains:

<img width="939" alt="section remains" src="https://user-images.githubusercontent.com/12850389/39642564-210d282a-4fa0-11e8-9fbe-3325bceb0cc4.png">

Examples from: https://alpha.opencasebook.org/casebooks/57032-fresh-casebook/layout
I was also unable to delete a resource I added.

**Comment by abziegler** [comment]
Reproduced bug.
