### ISSUE TITLE
Remove "click here to add section/resource" link

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#324]
When there's no content in a casebook, or section, the field at the bottom that reads 'This section has no content' + 'click here to add [section][resrouce]' -- the latter can be removed.

<img width="826" alt="click here to add" src="https://user-images.githubusercontent.com/12850389/39643671-7fb0cd20-4fa3-11e8-97a0-d5b8743c45a9.png">

**Comment by abziegler** [comment]
Let's simplify by eliminating the link and link text. Leave it to the action buttons.
