### ISSUE TITLE
Remove code supporting disabled 'barcode' feature

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#33]
'Barcode' is a disabled feature of H2Ov1. When it was enabled, it provided a visual signal of the "influence" of a given object (playlist, case, text, etc.) based how that object was used, remixed, annotated. 

Here's what it looked like:
![h2o-barcodes](https://cloud.githubusercontent.com/assets/2140548/24455046/3c7c1844-145c-11e7-9a1b-6550cd2a92b8.png)
 
We disabled 'barcodes' two years ago because it was a major contributor to slow load times, which was a top user complaint.

We can remove this from the H2Ov2 codebase. The barcode concept is a good one, which we should revisit in the future, but the existing implementation is problematic, and we should not carry the code forward.

**Comment by emmalemma** [comment]
done in rails-5 branch
