### ISSUE TITLE
Remove code supporting 'defect' [aka error reporting] feature

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#34]
Based on nature and timing of commits, the 'defect' feature appears to reflect an attempt 1.5 years ago to give users the ability to report content errors (e.g. typos) or provide other feedback to an author.

This feature is currently enabled, at least partially, in H2Ov1. Assigning issue for now to me and @bjohnson747 for further analysis.

**Comment by emmalemma** [comment]
If this is specifically for content feedback, I assume I can roll it into the commenting refactor. If it's for site feedback more generally, I'm sure there's a gem for that.

In either case I'd like to delete the existing code, unless we'll need to migrate them.

**Comment by abziegler** [comment]
@cgruppioni will take a look to see if I'm right that 'defect' = feedback. And I'm definitely talking about content feedback.

**Comment by abziegler** [comment]
Turns out 'defect' != feedback. We can remove this 'defect' code.

**Comment by emmalemma** [comment]
done in rails-5 branch
