### ISSUE TITLE
Annotations to text-blocks should be sticky

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#348]
If an author annotates a text, then wants to edit that text (e.g. by removing lines), the annotations shift and lose their context. 

Annotations should stick to their textual context, even after deletions/additions/etc. As a second-best, we could consider alerting authors who seek to edit annotated text that their edits will alter the annotation placement.

**Comment by rebeccacremona** [comment]
Closing in favor of https://github.com/harvard-lil/h2o/issues/503, soon to be fixed.
