### ISSUE TITLE
Feature request: "bookmark" casebooks

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#357]
As a student, I'd love to be able to click a button when viewing a casebook that would make a link to the published book show up in "My Casebooks"

**Comment by abziegler** [comment]
Indeed, it's in the designs but we de-prioritized it as feature at this stage. Lots of potential in this feature

**Comment by rebeccacremona** [comment]
Implemented in https://github.com/harvard-lil/h2o/pull/1412
