### ISSUE TITLE
Remove existing CMS

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#36]
We should consider replacing the existing CMS with the native Text interface.

**Comment by abziegler** [comment]
@emmalemma can you clarify what you mean by existing CMS? Is this the rails-admin, which we've used for doing static pages (e.g. help docs)? Or are you talking about something user-facing?

**Comment by emmalemma** [comment]
Yes, this was meaning the `Page` model and related code. I'd eventually like to replace it with a proper CMS gem which would bring i18n support and so on.

On a second look though, this is a used feature and there's nothing wrong with the existing code, so this isn't a target for removal. In fact, I need to add it to the list for testing :)
