### ISSUE TITLE
'Replace text' working rarely in Safari

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#364]
Text can be selected for replacement-text annotation fine, but it rarely saves the replacement text that was entered.

*Attempt:*
<img width="719" alt="replacing text attempt" src="https://user-images.githubusercontent.com/12850389/40751011-60fca928-6437-11e8-90db-430c5a0e536e.png">

*After hitting Save:*
<img width="692" alt="after hitting save text not saved" src="https://user-images.githubusercontent.com/12850389/40751019-68b5b6aa-6437-11e8-9e96-2dec69884c06.png">

It very intermittently works, 7 out of 8 times it doesn't stick though. Recreated in Safari v10.0 and v11.0

**Comment by leppert** [comment]
@bjohnson747 I’m having trouble recreating this. Any chance you could confirm it’s still an issue with the current codebase? Maybe another change affected it?

**Comment by bjohnson747** [comment]
@leppert I also am not able to re-create. Closing ticket (barring issue reappearing)
