### ISSUE TITLE
Some case content may've imported w/o <p> tags

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#371]
EDIT: this comment (https://github.com/harvard-lil/h2o/issues/371#issuecomment-399622165) contains a straightforward example of this.

----
Notified via a user, it appears to primarily (only?) affect text that was meant to be quote-text.
using Griswold v Connecticut as example (https://h2o.law.harvard.edu/cases/1267).

_This case should have all of the displayed here (via old H2O):_
<img width="789" alt="original h2o" src="https://user-images.githubusercontent.com/12850389/40810164-015a6bbc-64fb-11e8-91b2-7403713439ff.png">

_Instead, those middle portions are missing, as shown in this SS from a user:_
![valentina ss](https://user-images.githubusercontent.com/12850389/40809952-387f3772-64fa-11e8-8d61-0cc01a12e5eb.png)

As shown in the old H2O source (below), these paragraphs don't have paragraph tags; 

<img width="953" alt="screen shot 2018-05-31 at 5 50 26 pm" src="https://user-images.githubusercontent.com/12850389/40810556-21aed7f8-64fc-11e8-90f5-8db7df7e7289.png">

when they were originally imported into old H2O, I assume the quote-text tag got messed up but still displayed in old H2O, even without quote or paragraph tags. Once imported into new H2O, it stopped displaying.

**Comment by bjohnson747** [comment]
Here's something strange: the affected cases we've found, I set to private and reimported a cleaner version of the case. When i set the problematic case back to public and viewed it, the missing content (as shown in the user screenshot above) is now displaying:

<img width="763" alt="current ss" src="https://user-images.githubusercontent.com/12850389/40810701-a586fb96-64fc-11e8-861a-c08c0b382988.png">

I believe new H2O's case text editor automatically added paragraph tags to these when I opened the case in https://alpha.opencasebook.org/admin/case .

**Comment by bjohnson747** [comment]
Here's a straightforward example of this issue.

Boutilier v INS in old H2O:
<img width="645" alt="screen shot 2018-06-22 at 9 45 04 pm" src="https://user-images.githubusercontent.com/12850389/41804566-cc5a2aec-7666-11e8-8096-5674c42d9d00.png">

The html of that section in old H2O:
<img width="896" alt="screen shot 2018-06-22 at 9 44 58 pm" src="https://user-images.githubusercontent.com/12850389/41804567-d5d28bd2-7666-11e8-9e8d-36fceafad8cf.png">

The same section in new H2O, **before** i opened it in the case text editor (what should be a block-quote is missing):
![unknown](https://user-images.githubusercontent.com/12850389/41804575-f16aef4c-7666-11e8-87f9-8af86069a419.png)

Here's it after being opened in new H2O's text editor:
<img width="954" alt="screen shot 2018-06-22 at 9 50 22 pm" src="https://user-images.githubusercontent.com/12850389/41804577-f4a8bfe0-7666-11e8-88e0-b0918e92b5ac.png">

**Comment by bjohnson747** [comment]
There are also some cases that are simply missing their block-quotes, in both H2O's. Ex. Palmore v Sidoti (https://h2o.law.harvard.edu/cases/1013) does not have the blockquote that is showing in paragraph 18 of this newly ingested version: https://opencasebook.org/cases/7926 .

**Comment by cgruppioni** [comment]
- completely missing text is from the original data dump ( Dec 2017 ) 
-

**Comment by cgruppioni** [comment]
Brett and I talked about this and it's not widespread amongst cases and he can easily fix it in Admin -- and it would be very complex to try to find all cases that have this issue. Especially since we now have the cap integration, we're going to close this ticket.
