### ISSUE TITLE
Replace landing page font

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#376]
@anastasia says "Lora, a free google font, is a good alternative for the headline font: https://fonts.google.com/specimen/Lora".

Headline font-size should become much smaller on mobile at the same time :-)

**Comment by anastasia** [comment]
Would it be possible to give it a little more breathing room?


<img width="1440" alt="screen shot 2018-06-26 at 3 03 23 pm" src="https://user-images.githubusercontent.com/1494102/41933543-3aefc15e-7952-11e8-875e-13868f4b82db.png">


versus 

<img width="1440" alt="screen shot 2018-06-26 at 3 04 39 pm" src="https://user-images.githubusercontent.com/1494102/41933574-4d96b5a6-7952-11e8-8173-d8233d56e859.png">
