### ISSUE TITLE
Clunky drag-n-drop experience in draft casebook mode

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#387]
- [ ] Drag and drop can be very sensitive, overly precise, making it difficult to drop in desired location 
- [ ] Shadow effect for drop-target and ghost image can both be funky, including multiple drop targets, and drop-targets taking on blue left-border (which is wrong color for a draft casebook - should be yellow) 

![h2o-dragndrop](https://user-images.githubusercontent.com/2140548/41664734-633d8a70-7474-11e8-9080-619f2066410c.png)

**Comment by cgruppioni** [comment]
empty call continues being called until dropped
