### ISSUE TITLE
Elisions on styled text causing elided text to (temporarily) disappear

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#392]
When an elision contains < em> tagged text, and the elided text is revealed, it's incomplete/missing characters.

Eliding:

<img width="807" alt="screen shot 2018-06-13 at 10 05 03 am" src="https://user-images.githubusercontent.com/12850389/41356209-682b743a-6ef1-11e8-8b37-99aa1eca3ff7.png">

Elided text revealed: 

<img width="783" alt="screen shot 2018-06-13 at 10 05 15 am" src="https://user-images.githubusercontent.com/12850389/41356223-7187e040-6ef1-11e8-8951-2eb3de93b2c1.png">

The text around elisions is also _sometimes_ affected, but I'm not sure if this is due to the bug in #290. Example in this same case: the last 's' in Steffens isn't selected, but it's getting included in the elision:

<img width="729" alt="screen shot 2018-06-13 at 2 25 05 pm" src="https://user-images.githubusercontent.com/12850389/41371536-a8805a7e-6f18-11e8-94d7-dbe272345c87.png">
-->
<img width="690" alt="screen shot 2018-06-13 at 2 25 16 pm" src="https://user-images.githubusercontent.com/12850389/41371559-bb7904dc-6f18-11e8-8bba-25f42b90080b.png">

(and also, missing characters in the elision b/c of the em tag :

<img width="708" alt="screen shot 2018-06-13 at 2 25 20 pm" src="https://user-images.githubusercontent.com/12850389/41371707-34552d72-6f19-11e8-9bb2-140d3d4fbafd.png">

*I ingested a new version of the case that brought this to our attention; I've also kept the one _with_ italics in H2O for temporay testing and troubleshooting purposes - it's been renamed "do not use".

**Comment by bjohnson747** [comment]
I believe this occurs whenever the text has any special styling - it appeared to happen with bolded text as well. This header is bolded and is affected when elision happen on it, but not the H2 tagged text later in the case. Bold text:

<img width="673" alt="screen shot 2018-06-14 at 5 18 42 pm" src="https://user-images.githubusercontent.com/12850389/41442058-7370364c-7003-11e8-9c49-509511a40a85.png">

<img width="545" alt="screen shot 2018-06-14 at 5 20 11 pm" src="https://user-images.githubusercontent.com/12850389/41442059-737c35a0-7003-11e8-94a6-ca0e997fbe8c.png">

<img width="613" alt="screen shot 2018-06-14 at 6 43 38 pm" src="https://user-images.githubusercontent.com/12850389/41442060-738b0e90-7003-11e8-8a01-b36e5c87842f.png">

**Comment by bjohnson747** [comment]
Further confirmation this appears to only occur when done to text that has some special formatting.
Text selected for eliding:
<img width="809" alt="screen shot 2018-06-21 at 3 32 31 pm" src="https://user-images.githubusercontent.com/12850389/41796065-0047f3ae-7633-11e8-8cf5-8ced8e4b7055.png">
What's displayed when the elision is snapped open:
<img width="696" alt="screen shot 2018-06-21 at 3 32 17 pm" src="https://user-images.githubusercontent.com/12850389/41796075-0c8c0060-7633-11e8-9971-b54e654c72b1.png">

**Comment by rebeccacremona** [comment]
Can you see whether this happens for students (not logged in), or only for authors?

**Comment by bjohnson747** [comment]
@rebeccacremona still happens for not-logged-in users (tested here - https://opencasebook.org/casebooks/58552-constitutional-law-separation-of-powers-federalism-and-fourteenth-amendment-spring-2018/resources/20-state-of-new-mexico-plaintiff-appellee-v-angel-martinez-defendant-appellant - paragraph 17, the elision towards the end of it isn't displaying all that elided when clicked)

**Comment by rebeccacremona** [comment]
Idea 1) https://github.com/harvard-lil/h2o/blob/master/app/assets/javascripts/lib/ui/content/annotations/elide.js#L22 is toggling those nodes off, but not toggling them on. 

Idea 2) Other JS/CSS is hiding them, and they are NOT being handled by this function (and they should be)

**Comment by rebeccacremona** [comment]
Yep. I think the JS I wrote to toggle the paragraph numbers on/off with elided text had the side effect of breaking the toggling of these nested elements. On toggling: `TypeError: el.parentElement.previousElementSibling is null`, which to say, "Hey! you aren't immediately preceded by a page number, which Becky's code assumes you are!", which stops the javascript from finishing, which stops the rest of the text from being revealed. I'll add an `if` to the line in question on Monday, should fix that.

**Comment by rebeccacremona** [comment]
@cgruppioni I keep breaking stuff :-)

**Comment by abziegler** [comment]
@rebeccacremona are you working on this or know why you self-assigned? If not, can you put it back in the unassigned pool? Thanks

**Comment by rebeccacremona** [comment]
@abziegler sincere apologies, I forgot about this...... Since I broke it, I think I should fix it.
