### ISSUE TITLE
Imported casebook(s?) have wrong link resources

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#395]
At least one casebook imported from old H2O to new H2O has been corrupted, such that some of its links were replaced by links that come from other playlists in old H2O. Details below from specific example.

Intisar's casebook was imported into new H2O, and all her sections are labelled correctly, but all* the items Week 4 and above are different resources than the ones she actually put into her casebook. See below:

Weeks 1-3 (correct, old H2O): https://h2o.law.harvard.edu/playlists/13034
Weeks 1-3 (incorrect, new H2O): https://opencasebook.org/casebooks/17493-advanced-legistlation-theories-of-statutory-interpretation-spring-2015/sections/1-part-i-interpretive-theories
Week 4 (correct): https://h2o.law.harvard.edu/playlists/13132
Week 4 (incorrect): https://opencasebook.org/casebooks/17493-advanced-legistlation-theories-of-statutory-interpretation-spring-2015/sections/2.1-week-4-textual-canons-realist-critiques
Full casebook in old H2O: https://h2o.law.harvard.edu/playlists/13034

It looks like most of the wrong resources are from other casebooks, not a different location in Intisar's.
The one exception is  the link in Week 10 Supplemental is swapped with the link in Week 1 Supplemental - Heydon's case switched with Justin Hughes Philosophy of IP.  This is also the only incorrect item after Week 4.

(*all, except item 1.1.5., Church of the Holy Trinity v. the United States)

**Comment by cgruppioni** [comment]
<img width="1139" alt="screen shot 2018-06-14 at 12 43 20 pm" src="https://user-images.githubusercontent.com/12850389/41426813-cf277882-6fd2-11e8-8375-2e7793c16b05.png">

**Comment by cgruppioni** [comment]
Deleting the casebook and remigrating it works. We can also individually change the resources. 

These are the casebook ids of casebooks that have mismatched resources 
[16066, 16723, 17493, 17751, 18331, 18560, 18672, 19006, 19353, 19750, 20234, 20414, 20611, 20926, 23303, 23416, 24172, 24799, 25610, 26562, 26936, 27225, 27674, 28325, 32567, 32667]

They only include 1st gen casebooks - so if someone cloned one of these casebooks it's not in the list. 

Most of them have been updated since Jan 3rd.

**Comment by cgruppioni** [comment]
Need someone to:

- Look at these resources and determine if you want the resource deleted completely and remigrated or if you need it manually matched. 
- Are any of the descendants important or can those be deleted?

**Comment by bjohnson747** [comment]
Thank you Casey @cgruppioni ! Do we know when the wrong resources were swapped in? 

The couple I have marked as needing manual updating are those that I believe were worked on during the semester; most of the rest can be dumped + reimported.

16066, trash it + doesn't need replacing
16723, can be dumped + reimported
17493, dump + reimport
17751, dump + reimport
>>>>>>18331 - Howell, 
18560, dump + reimport
18672, if this is identical to 34088 (descendant), both can be dumped and reimported
19006, dump + reimport
19353, dump + reimport
19750, correct manually
20234, correct manually
20414, dump + reimport
20611, dump + reimport
20926, dump + reimport
23303, dump + reimport
23416, dump + reimport
24172, dump + reimport
24799, dump + reimport
25610, dump + reimport
26562, dump + reimport
26936, dump + reimport
27225, dump + reimport
27674, dump + reimport
28325, dump + reimport
32567, dump + reimport
32667, dump + reimport

_descendants_
40868 not opening for me - 
35607 can be deleted and reimported
34088 if this is identical to 18672 (parent?), both can be dumped and reimported

**Comment by cgruppioni** [comment]
@bjohnson747 Here are the 2 casebooks we want manually re-migrated. Can you verify that these ordinals look incorrect? 

20234
["2.1.1", "3.3.3", "3.3.4", "3.3.5", "3.3.6", "4.1.1", "4.2.1", "6.3.1", "6.3.2", "6.3.3", "7.3.1", "7.3.3", "7.3.4", "7.3.5", "9.3.1", "9.3.2", "10.2.1", "10.2.2", "12.3.1", "12.3.2", "12.3.3", "12.3.4"]

19750
["6.1.1", "6.1.2", "6.1.3", "6.1.4", "9.2.1", "9.2.2", "9.3", "9.4.1", "12.2.1", "12.3.1", "12.3.2", "14.3", "14.4", "14.5", "14.6", "15", "16.1", "16.2", "16.3.1", "16.3.2", "16.4", "17.1.1", "17.1.2", "17.2.1", "17.2.2", "17.2.3.2", "17.2.3.3", "17.3.2", "17.3.3"]

**Comment by bjohnson747** [comment]
@cgruppioni yep, both have wrong ordinals. 20234 can actually be deleted altogether (her casebook is one that has been changed and we're going to import it again after the next data dump). 19750 we should correct.

is there an easy way for you to see if 34088 is identical to 18672?

**Comment by cgruppioni** [comment]
@bjohnson747 yes 34088 and 18672 are identical

**Comment by bjohnson747** [comment]
@cgruppioni ok thanks - those can be dump/reimported!

**Comment by cgruppioni** [comment]
@bjohnson747 can you take a look at casebooks [33947, 35359, 34231, 35950] as well? Those are descendants that I didn't have in my local db

**Comment by cgruppioni** [comment]
@bjohnson747 nevermind  35950] doesn't have an owner so going to delete it. The last three are all clones of the same casebook that we're already deleting + reimporting

**Comment by bjohnson747** [comment]
@cgruppioni 33947 might be identical to 34088 and 18672 - it looks that way at first glance - if so that can be dumped/reimported.

35359 and 34231 look like they've been updated by the user; let me contact him and see which of all these is actually the one he's used, so we know which to manually fix. pls hold!

**Comment by bjohnson747** [comment]
@cgruppioni 
18672 can be dumped + reimported,
34321 he wants saved, so if that has data issues we can clean that up,
i'm going to delete 35359, 33947 and 34088.  - sound good?

**Comment by bjohnson747** [comment]
I looked through 34231, which looked all good. So, we have that list that can all be dumped and reimported (including 18672), and just 19750 needs to be manually corrected.

**Comment by cgruppioni** [comment]
Just confirming @bjohnson747 

Casebooks to delete: [16066, 20234, 35607, 35950]
Casebooks to delete and then reimport: [16723, 17493, 17751, 18331, 18560, 18672, 19006, 19353, 20414, 20611, 20926, 23303, 23416, 24172, 24799, 25610, 26562, 26936, 27225, 27674, 28325, 32567, 32667]
Casebooks to manually re-set resources: [19750]

**Comment by bjohnson747** [comment]
@cgruppioni I swapped two casebooks in that list one from the no-reimport to the delete-and-reimport list, and one in the other direction. I checked the rest and those are ready to be moved on.
Thank you!

Casebooks to delete and not reimport: [16066, 20234, 35950, 16723]
Casebooks to delete and then reimport: [35607, 17493, 17751, 18331, 18560, 18672, 19006, 19353, 20414, 20611, 20926, 23303, 23416, 24172, 24799, 25610, 26562, 26936, 27225, 27674, 28325, 32567, 32667]
Casebooks to manually re-set resources: [19750]

**Comment by cgruppioni** [comment]
Code that was used to get list of mismatched casebooks: https://github.com/cgruppioni/h2o-1/blob/236ee5cf30dbb4d07d18c6a2da87363a8ec8e947/lib/verify_single_playlist.rb

17493 was the casebook this ticket was initially based off of

Results of mismatched casebooks, there were deleted & reimported [24353, 12865, 66, 10007, 11114, 22235, 9504, 17493] 
Deleted casebook that is being reimported with h2ov1 data dump: 20234
Casebook that was a descendant and was deleted and not reimported 24353

No casebooks needed to be manually re-matched. But if it did, this code would fix them:  https://github.com/cgruppioni/h2o-1/blob/236ee5cf30dbb4d07d18c6a2da87363a8ec8e947/lib/rematch_casebooks_to_playlists.rb
