### ISSUE TITLE
Casebook import from Word

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#398]
Crude version of this in the old-H2O codebase; used markdown. Concept is author can take a word outline or syllabus, and with a little markdownification, H2O will parse into structure of casebook, pulling in designated cases, links, etc.

**Comment by bjohnson747** [comment]
mockups of potential easy-section-maker, and how a user might be able to markdown an imported syllabus:
![easy section creator mockup](https://user-images.githubusercontent.com/12850389/45380298-60672e80-b5d0-11e8-9bdd-aa951ba6c7ba.png)

![imported syllabus- create sections](https://user-images.githubusercontent.com/12850389/45380302-62c98880-b5d0-11e8-801c-ac620cf95a6b.png)
