### ISSUE TITLE
Summer 2018 data transfer 

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#405]
As discussed in our meeting Tuesday the 12th, we'll be moving data into H2O:

1) Relevant data that's been changed or created since our the last database dump we received (Oct/Nov 2017)

2) Additional content that was uncovered since last import - see @bjohnson747 google doc

- [x] Check for new users

**Comment by bjohnson747** [comment]
(I'm thinking this would in "pre-launch" but i'll let you drop it in a project adam)

**Comment by cgruppioni** [comment]
- [ ] Check for new users
