### ISSUE TITLE
When adding a case to a casebook, clicking the case to be added multiple times causes a 500 (solr) error 

### ISSUE THREAD

**Issue by cgruppioni** [harvard-lil/h2o#412]
The UI behavior should probably be changed to prevent this. The form freezes after a user selects a casebook, modal goes away, etc......

**Comment by bjohnson747** [comment]
This is also the case when clicking "Make a new casebook", after first clicking Create Casebook - Make a new Casebook can be clicked several times and this creates several new casebooks when it should just make one.

**Comment by cgruppioni** [comment]
Dupe of #443
