### ISSUE TITLE
Clicking 'Revise' button as admin sometimes creates admin-authored clone 

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#416]
When in admin mode, admin clicks 'Revise' on a user's casebook @ casebook view; seems to work fine.

When admin hits 'Revise' when viewing one of their resources, however, it creates a clone of their casebook and takes admin to their own clone of that resource.

THEIR RESOURCE. 
<img width="1151" alt="screen shot 2018-06-19 at 6 19 21 pm" src="https://user-images.githubusercontent.com/12850389/41627216-5c7f462e-73ed-11e8-9b66-2b05d613a140.png">

HIT REVISE, WHICH CREATES MY OWN COPY OF IT:
<img width="1206" alt="screen shot 2018-06-19 at 6 19 37 pm" src="https://user-images.githubusercontent.com/12850389/41627217-5c8da9d0-73ed-11e8-9101-e8366ab9886e.png">

NEW CASEBOOK IN MY DASHBOARD:
<img width="295" alt="my casebook" src="https://user-images.githubusercontent.com/12850389/41627218-5c9a2bd8-73ed-11e8-9fb1-7cdc4d1ba85f.png">

**Comment by abziegler** [comment]
@bjohnson747 will check this today and close issue if already resolved

**Comment by bjohnson747** [comment]
@cgruppioni Tested this and it was still occurring for me - not resolved

**Comment by bjohnson747** [comment]
I tested this on stage and it did not occur.  @cgruppioni
