### ISSUE TITLE
Drag-n-drop pulling in neighbor items in draft casebook mode

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#419]
Drag and drop sometimes pulls along neighbor items - see description below 

Tested in this casebook (https://alpha.opencasebook.org/casebooks/60627-constitutional-law-separation-of-powers-federalism-and-fourteenth-amendment-spring-2018/layout)

section 1.3 had 2 items, Classic and Olmstead:

<img width="884" alt="buggy scrrenshoe" src="https://user-images.githubusercontent.com/12850389/41301219-8eddffb0-6e35-11e8-94e7-214b2977fc40.png">

When EC Knight dragged in, Sosa came with it.

<img width="976" alt="buggy screenshort 2" src="https://user-images.githubusercontent.com/12850389/41301242-9d9bb97a-6e35-11e8-9a81-f9fa1a6266ef.png">

**Comment by cgruppioni** [comment]
Don't think this is an issue anymore, but will test in staging once #526 is merged in

**Comment by cgruppioni** [comment]
This happens when moving an item up. When dragging one to a lower section, it does now.
