### ISSUE TITLE
Chrome browser print-to-PDF bug

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#42]
Discovered at the end of 2015: When printing this playlist (https://h2o.law.harvard.edu/playlists/1923) in-browser, to PDF, some text was cut off at the bottom of a page. 
![screen shot 2015-09-23 at 5 33 38 pm](https://cloud.githubusercontent.com/assets/12850389/24682810/add5ad72-1969-11e7-9904-61dd480bd348.png)

At the time, phunk wrote: "I experimented with setting the "@page" CSS directive to manipulate margins and paper page size, but I didn't find any conclusive fix. I may have the settings working to reduce the amount of lines of text that get cut-off, but that could just be chance based on how the text happens to flow for this playlist. I also experimented with the margin settings in Chrome's print preview, but even the Custom settings didn't seem to prevent text cut-offs completely. In fact, it looks like changing margins really just changes the location and possibly the number of the text cut-offs."

And later, this: "Here are a few links I've looked up again that seem relevant, but I wouldn't take these as canonical necessarily.

https://productforums.google.com/forum/#!msg/chrome/dthnoDWRSQ0/XD6fBioGk9YJ
https://code.google.com/p/chromium/issues/detail?id=448809
http://stackoverflow.com/questions/26327371/chrome-print-preview-cutting-text-off-in-the-middle-if-it-reaches-the-bottom-mar
http://stackoverflow.com/questions/19920141/google-chrome-cutting-off-bottom-of-long-pages

You'll notice a lot of similar sounding issues linked from that last StackOverflow URL, as well.

Brett, could you reproduce this in production when using the Verdana font? I'm asking because I'm pretty sure the Verdana font is native to Macs. Beyond that, I remain stumped."

Adding this as an issue because if we keep this print-in-browser functionality, this should be on our radar.

**Comment by abziegler** [comment]
closed as outdated
