### ISSUE TITLE
Exports not showing ellipses

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#420]
Currently exported casebooks are *not* showing the ellipses - these needs to be displayed so readers can know what text was elided.

CASEBOOK ON H2O:
<img width="908" alt="screen shot 2018-06-21 at 5 21 39 pm" src="https://user-images.githubusercontent.com/12850389/41746385-2456b0fc-7578-11e8-95d2-787bd8e08ee5.png">

EXPORT IN WORD - linebreak @ elision but ellipsis itself not showing:
<img width="845" alt="screen shot 2018-06-21 at 5 22 04 pm" src="https://user-images.githubusercontent.com/12850389/41746386-24667c8a-7578-11e8-9d68-f8c4298ab3de.png">

(new H2O's export used to show ellipses- here's an example from a casebook exported months ago:
<img width="510" alt="screen shot 2018-06-21 at 5 24 59 pm" src="https://user-images.githubusercontent.com/12850389/41746421-4187b19e-7578-11e8-837a-3fbfadc5fc1f.png">

**Comment by cgruppioni** [comment]
#422
