### ISSUE TITLE
Fix signup and email confirmation flow

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#421]
Testing user clicked the link in his email, which brought him back to opencasebook.org but it failed to verify his email address.
This is the message recieved when attempted:

<img width="1202" alt="screen shot 2018-06-21 at 6 03 49 pm" src="https://user-images.githubusercontent.com/12850389/41747883-91c822ec-757d-11e8-83ee-5d9806f2506b.png">

**Comment by bjohnson747** [comment]
Also the "youve been sent a verification email" shows up half-covered, at least in Chrome 
<img width="752" alt="screen shot 2018-06-21 at 5 44 42 pm" src="https://user-images.githubusercontent.com/12850389/41747483-27058ffe-757c-11e8-89e9-847934208ad8.png">

**Comment by bjohnson747** [comment]
Additionally - Display Name (attribution) is 'optional' this should be set to required. Without a display name their casebooks display with no owner.

**Comment by cgruppioni** [comment]
Part 2: 

- [ ]  Clicking on the confirmation email link takes you to a view on which you create your password ( this is how perma works)

- [ ] "youve been sent a verification email" shows up half-covered, at least in Chrome https://user-images.githubusercontent.com/12850389/41747483-27058ffe-757c-11e8-89e9-847934208ad8.png

- [ ] confirmation email link doesn't do anything // says verification failed
