### ISSUE TITLE
Specific casebook - export attempt gives 500 error

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#427]
Cloned a user's casebook, after the dev team noticed they received an 500 error when export was attempted.
 My clone if it also returns a 500 error. -> https://opencasebook.org/casebooks/70367-torts-brett-test

**Comment by cgruppioni** [comment]
https://opencasebook.org/casebooks/69719-torts

**Comment by cgruppioni** [comment]
Brett finding problem resource and trying to fix it in Admin
