### ISSUE TITLE
Prevent authors from creating corrupt resources in the first place 

### ISSUE THREAD

**Issue by cgruppioni** [harvard-lil/h2o#431]
related to #310 

Restrict what can be into text blocks

**Comment by cgruppioni** [comment]
Ex: #427 
User tried to paste casebook into textblock, had image inside. Was corrupt

**Comment by rebeccacremona** [comment]
@rebeccacremona todo tomorrow: find out if the cut/paste of image mentioned in this issue is due to  file paths and htmltoword, or is some separate validation issue we need to handles
