### ISSUE TITLE
Links in Word export: display full URL?

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#435]
Links currently live in the Word export as a hyperlinked word (or phrase) that that link annotation was put on - not a separately displayed URL. 
Since this is in the export, do we want instead links surfaced as a displayed URL, instead of just hyperlinked text?

**Comment by abziegler** [comment]
@bjohnson747 yes we should display the URL in the export. But please add screenshots then reassign issue to me

**Comment by bjohnson747** [comment]
Currently link annotations aren't displayed in export:

 <img width="504" alt="screen shot 2018-07-18 at 4 10 52 pm" src="https://user-images.githubusercontent.com/12850389/42905948-8f6ceec6-8aa7-11e8-91ec-78cab4254f2c.png">

Links should display as a link, in-line? ex.: <img width="506" alt="screen shot 2018-07-18 at 4 10 57 pm" src="https://user-images.githubusercontent.com/12850389/42905954-94195a86-8aa7-11e8-9037-f2916ff6daf5.png">

**Comment by cgruppioni** [comment]
Updated as an issue in #835
