### ISSUE TITLE
Adjust display name handling when display name is blank

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#442]
If the display name field on user profile is blank, then we should:

For logged_in usages (e.g. account menu) - use email address
For not_logged_in usages (e.g. attribution on casebook) - use "Anonymous"

Also need to adjust pluralization

We do not want to display email addresses publicly; we do not want to display user IDs.

**Comment by cgruppioni** [comment]
Avoid code that is checking for nil all the time

**Comment by cgruppioni** [comment]
#484
