### ISSUE TITLE
Disable multiple clicks on 'create casebook' + adding case/resource

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#443]
Currently when user clicks the create casebook button (from scratch) multiple times, it creates multiple casebooks. Same with when they're searching + adding a case: clicking the case name multiple times adds it multiple times to a casebook.

Button should be set to not being able to be clicked repeatedly. (Becky mentioned HTML function 'disabled')

**Comment by cgruppioni** [comment]
Set `disabled` on button 

Perma stage button to create a permalink has all the features

**Comment by rebeccacremona** [comment]
rcremona [2:45 PM]
Re: making sure people can only click a button once:
https://www.w3schools.com/jsref/prop_pushbutton_disabled.asp
https://getbootstrap.com/docs/4.0/components/buttons/#disabled-state (edited)

If it isn’t a true button (e.g. a span, a link, etc.), let me know. (edited)
