### ISSUE TITLE
Rename 'case jurisdiction' field to 'court,' and add 'jurisdiction' field

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#444]
For cases, 'Case Jurisdiction' field has actually used for 'Court.' This needs to be renamed/reclassified as 'court' instead.

'Case Jurisdiction' then needs to be added as a field.

**Comment by abziegler** [comment]
Should be addressed as part of CAP integration #143

**Comment by abziegler** [comment]
Address in #143
