### ISSUE TITLE
Some elisions in imported casebook are in wrong location

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#446]
Notified by user - some elisions in his casebook are in the wrong location. 

[PELL v KILL in old H2O](https://h2o.law.harvard.edu/collages/41403):
<img width="766" alt="screen shot 2018-07-12 at 1 44 06 pm" src="https://user-images.githubusercontent.com/12850389/42668750-48116754-8620-11e8-87d0-537db45d281a.png">

[PELL v KILL](https://alpha.opencasebook.org/casebooks/72837-an-introduction-to-the-law-of-corporations-cases-and-materials/resources/7.2.5-lewis-c-pell-plaintiff-v-robert-c-kill-kenneth-h-paulus-kevin-h-roche-and-james-p-stauner-defendants-and-cogentix-medical-inc-nominal-defendant/annotate) in NEW H2O:
<img width="845" alt="screen shot 2018-07-12 at 1 44 42 pm" src="https://user-images.githubusercontent.com/12850389/42668751-4bcdd17a-8620-11e8-92d8-5d6bb6d1a45c.png">
***Note that only the header is affected in this case.

While there are a few cases where it looks like only case headers are affected - for example, [here](https://alpha.opencasebook.org/casebooks/72837-an-introduction-to-the-law-of-corporations-cases-and-materials/resources/5.2-frank-david-seinfeld-plaintiff-v-donald-w-slager-james-e-o-x27-connor-john-w-croghan-tod-c-holmes-david-i-foley-ramon-a-rodriguez-michael-w-wickham-james-w-crownover-nolan-lehmann-allan-c-sorensen-william-j-flynn-w-lee-nutter-john-m-trani-michael-larson-and-republic-services-inc-defendants/annotate) and [here](https://alpha.opencasebook.org/casebooks/72837-an-introduction-to-the-law-of-corporations-cases-and-materials/resources/4.3.6.1.1-william-stone-and-sandra-stone-derivatively-on-behalf-of-nominal-defendant-amsouth-bancorporation-plaintiffs-below-appellants-v-c-dowd-ritter-ronald-l-kuehn-jr-claude-b-nielsen-james-r-malone-earnest-w-davenport-jr-martha-r-ingram-charles-d-mccrary-cleophus-thomas-jr-rodney-c-gilbert-victoria-b-jackson-j-harold-chandler-james-e-dalton-elmer-b-harris-benjamin-f-payton-and-john-n-palmer-defendants-below-appellees-and-amsouth-bancorporation-nominal-defenda/annotate) in user's casebook, there are also cases where not-header items are effected. See paragraphs 13 and 14 of [this example](https://alpha.opencasebook.org/casebooks/72837-an-introduction-to-the-law-of-corporations-cases-and-materials/resources/2.2.9.1-walkovszky-v-carlton/annotate), and paragraph 26 of [this example](https://alpha.opencasebook.org/casebooks/72837-an-introduction-to-the-law-of-corporations-cases-and-materials/resources/2.2.9.2-kinney-shoe-corporation-a-new-york-corporation-plaintiff-appellant-v-lincoln-m-polan-defendant-appellee/annotate).

Not every case is affected by this, ex. [this case](https://alpha.opencasebook.org/casebooks/72837-an-introduction-to-the-law-of-corporations-cases-and-materials/resources/7.2.4-paramount-communications-inc-viacom-inc-martin-s-davis-grace-j-fippinger-irving-r-fischer-benjamin-l-hooks-franz-j-lutolf-james-a-pattison-irwin-schloss-samuel-j-silberman-lawrence-m-small-and-george-weissman-defendants-below-appellants-v-qvc-network-inc-plaintiff-below-appellee-in-re-paramount-communications-inc-shareholders-x27-litigation
) is fine.

I am confident that this is being caused by the elisions issue in #290.

**Comment by abziegler** [comment]
@bjohnson747 please add this contest to #290 and close this issue as duplicative

**Comment by bjohnson747** [comment]
Added examples from this to #290, closing this ticket since i've addressed affected areas manually.
