### ISSUE TITLE
Recieving error when trying to make imported user verified professor

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#452]
When trying to make imported user verified professor via admin interface, I get these errors : 
<img width="446" alt="screen shot 2018-07-17 at 12 15 00 pm" src="https://user-images.githubusercontent.com/12850389/42831596-c0d120c2-89bc-11e8-87ac-e74bbf29c708.png">
+
<img width="527" alt="screen shot 2018-07-17 at 12 15 06 pm" src="https://user-images.githubusercontent.com/12850389/42831597-c0df22bc-89bc-11e8-96c5-052a78d0205e.png">

I tested on stage to see if adding an image would let the imported user be set to verified professor - that did allow me to make them verified.

**Comment by bjohnson747** [comment]
this error blocks me from making updates to these users on admin

**Comment by cgruppioni** [comment]
This has already been done
