### ISSUE TITLE
User-edited case title should display in casebook layout

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#459]
We allow users to edit case titles when they add a case to a casebook. The edited case title displays on the individual resource view, like this:

![case-resource-view](https://user-images.githubusercontent.com/2140548/43003369-57d5d51e-8bfa-11e8-8efb-37362396eae1.png)

But we do not display the edited case title on the casebook layout view:

![h2o-contents-view](https://user-images.githubusercontent.com/2140548/43003442-84e45170-8bfa-11e8-999b-d9c6fb849f70.png)

If user has edited a case title for her casebook, we should display that case title in casebook layout.

**Comment by bjohnson747** [comment]
tested, looks good
