### ISSUE TITLE
Needing redirect link from old -> new H2O

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#465]
Faculty member is using H2O as the place supplemental materials for a printed book are stored. Since he will be making updates to these materials at some point, but the printed book still lists the old H2O URL, it's needing a redirect set up from: 
https://h2o.law.harvard.edu/playlists/27055
to: https://opencasebook.org/casebooks/74710

**Comment by abziegler** [comment]
handling this differently; via admin access to old h2o
