### ISSUE TITLE
Annotation sidebar disappears sometimes when annotating header

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#468]
When selecting text to annotate in a case header, the sidebar disappears once I pass a certain line, then reappears once i've selected far enough.

From this case: https://opencasebook.org/casebooks/87325-copyright/resources/11.2.2-davidson-associates-doing-business-as-blizzard-entertainment-inc-vivendi-universal-inc-plaintiffs-appellees-v-tim-jung-an-individual-rob-crittenden-defendants-appellants-intellectual-property-law-professors-amicus-curiae-internet-gateway-defendants-appellants-computer-communications-industry-association-open-source-industry-alliance-consumers-union-public-knowledge-intellectual-property-law-professors-the-institute-of-electrical-and-electronics-engineers-inc/annotate

I can select a couple lines of the header fine, with annotation sidebar staying visible:
<img width="752" alt="screen shot 2018-08-29 at 4 49 21 pm" src="https://user-images.githubusercontent.com/12850389/44814769-ade4a400-abab-11e8-9fde-d8023f1d6ea5.png">

But once I select into the next line, it disappears.
<img width="722" alt="screen shot 2018-08-29 at 4 49 39 pm" src="https://user-images.githubusercontent.com/12850389/44814789-b5a44880-abab-11e8-96f4-4a76c42eed99.png">

Finally, once I scroll far enough to make it through the Parties, the sidebar reappears:

<img width="752" alt="screen shot 2018-08-29 at 4 50 07 pm" src="https://user-images.githubusercontent.com/12850389/44814827-cbb20900-abab-11e8-96bd-fdf3f9dd27f2.png">

**Comment by bjohnson747** [comment]
**THIS IS MY ORIGINAL POST THAT STARTED THIS ISSUE. I THINK IT'S CONFUSING AND NOT HELPFUL BUT I'VE STILL INCLUDED IT HERE.**

I discovered a few contexts where annotation sidebar has issues:

**Ex. 1:** Two lines of text, each line had their own < center> tag originally. Then when i removed one set of the < center> tags ...

<img width="353" alt="screen shot 2018-06-22 at 12 13 22 pm" src="https://user-images.githubusercontent.com/12850389/41787444-782464e2-7616-11e8-8e79-c1d7e62428fd.png">

After i took that out, the annotation sidebar does not appear when i select beyond the < center> into the next line's < p> text:

<img width="559" alt="screen shot 2018-06-22 at 12 16 03 pm" src="https://user-images.githubusercontent.com/12850389/41787582-d3c19ab8-7616-11e8-84e6-5bb6abdcdb9b.png">


------------
**Example 2:** When I add a < br/> tag to text that was eliding fine...
<img width="326" alt="screen shot 2018-06-22 at 3 10 08 pm" src="https://user-images.githubusercontent.com/12850389/41795544-266781c8-7631-11e8-81b5-4a9ef4258cdb.png">

And I then click-and-drag past the first line, the annotation sidebar disappears:
<img width="912" alt="screen shot 2018-06-22 at 3 10 40 pm" src="https://user-images.githubusercontent.com/12850389/41795547-28f22a42-7631-11e8-909e-1d3ef8627890.png">

(BUT when I click-and-drag BEYOND that phrase, annotation sidebar reappears:
<img width="928" alt="screen shot 2018-06-22 at 3 33 26 pm" src="https://user-images.githubusercontent.com/12850389/41795698-adc3dc52-7631-11e8-9a32-2563e1a2b0c1.png">

**Comment by abziegler** [comment]
@bjohnson747 does this problem occur with CAPAPI cases?

**Comment by cgruppioni** [comment]
Probably from these weird `<p>` tags 

![screen shot 2018-09-06 at 11 47 52 am](https://user-images.githubusercontent.com/14900328/45169036-b8fe8c00-b1ca-11e8-9418-a7b4883a6047.png)

**Comment by cgruppioni** [comment]
@bjohnson747 Is this still happening?

**Comment by bjohnson747** [comment]
all set - closing
