### ISSUE TITLE
Subsections displaying at incorrect 'depth' when in draft mode

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#478]
When viewing a section layout (rather than entire case layout) for a draft casebook, sub-section indentation is not correct. In published mode, sub-section indentation is correct:

Published mode:

<img width="752" alt="screen shot 2018-07-30 at 3 12 33 pm" src="https://user-images.githubusercontent.com/12850389/43418212-476594ee-940b-11e8-9bfb-9de5105ad732.png">

But when in draft mode, subsections that are actually the same level appear to be subsections of each other. 
Here's the same sections in draft mode:
<img width="755" alt="screen shot 2018-07-30 at 3 12 55 pm" src="https://user-images.githubusercontent.com/12850389/43418264-5ea71bf0-940b-11e8-888a-4773c8336048.png">

**Comment by abziegler** [comment]
@bjohnson747 can you link to casebook or provide ID?

**Comment by bjohnson747** [comment]
@abziegler Not limited to just this casebook but these examples are from casebook #28258

**Comment by abziegler** [comment]
@bjohnson747 Happening only with imported/migrated casebooks, or also with new casebooks?

**Comment by bjohnson747** [comment]
-Only happens when viewing a specific section, not at full casebook view.

-Only occurs if there is a resource between one section and the next.
CORRECT:
<img width="734" alt="screen shot 2018-07-31 at 2 19 42 pm" src="https://user-images.githubusercontent.com/12850389/43480073-287e1342-94d0-11e8-822d-fa8a491c2085.png">

INCORRECT:
<img width="705" alt="screen shot 2018-07-31 at 2 20 33 pm" src="https://user-images.githubusercontent.com/12850389/43480079-2ceec7dc-94d0-11e8-818a-b0a381602efa.png">

-I can only re-create this at the first-subsection level. Red-boxed below are the ones that are wrong but the rest are correct.
<img width="700" alt="screen shot 2018-07-31 at 3 58 44 pm" src="https://user-images.githubusercontent.com/12850389/43484124-759c22f8-94db-11e8-99a2-00c46487c975.png">
