### ISSUE TITLE
Annotation-comments not visible in published cases

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#504]
If an annotation-comment exists, it should appear in the margin of a published casebook next to the selected text that the author attached the comment to. 

Currently, annotation-comments are not visible in published casebook, although the selected text attached to the comment is underlined.

Example:

This is DRAFT mode, and the annotation-comment displays correctly

![h2o-annotation-comment-draft](https://user-images.githubusercontent.com/2140548/44148111-d8a3a562-a064-11e8-9201-9c57a5c97bfb.png)
 

This is PUBLISHED mode, and the annotation-comment does not display

![h2o-annotation-comment-published](https://user-images.githubusercontent.com/2140548/44148133-eef90ac8-a064-11e8-8e66-0d4fa2831e70.png)

Note that the annotation-comment does appear correctly in the export file.

**Comment by cgruppioni** [comment]
Add test to casebooks_test#87

**Comment by bjohnson747** [comment]
Tested, and this looked good for me (annotation-comment was already revealed when I viewed the item in published mode).

**Comment by bjohnson747** [comment]
tested on prod successfully
