### ISSUE TITLE
Use CAPAPI metadata in resource details 

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#505]
Greg's work on the CAPAPI integration highlights aspects of our case templates we might should adjust.

We should expose in the template all the key metadata that an author and/or reader would want to know about a case. These include at least abbreviated name, citation, decisiondate, court, jurisdiction, and possibly full name, parties, attorneys, judges, etc.

Currently the only metadata we expose is the abbreviated name. It's just this and the casebody. Up til now, we've often used the casebody field to include some of this metadata in unstructured form, as we simply pasted the full text of a document received from another source. That often included stuff like citation, court, dates, etc. 

I'd propose the following, but obviously open to other ideas:

- The header of a case should contain (1) abbreviated name (already there), (2) citations, (3) court, (4) formatted decision date. **data is already being parsed into db**

-  The body of a case should contain only the contents of the `<opinion>` tags (plural) found in the XML ... I know our handling of these in CAPAPI's generated HTML is still work in progress

-  The "Resource Details" tab in the case view should display all the other metadata: parties, judges, attorneys, full case name + everything included in the header. It should be a complete look at the substantive metadata. **parties, attorneys are already being parsed into db. Judges are not**

- Current we do not display "Resource Details" to anyone but the casebook author. We should change this so anyone viewing the case can see these details.

I tend to think we shouldn't tie up deploying the CAPAPI integration for this, but others will know better whether this implicates much of Greg's code.

**Comment by cgruppioni** [comment]
Keep in mind export while developing

**Comment by bjohnson747** [comment]
To discuss: do we want to include (or give the user the option to include) the resource details items (attorneys, case long name, etc)

**Comment by cgruppioni** [comment]
Example case comparisons for opinion design: 

One opinion: 
https://opencasebook.org/casebooks/114149-advanced-constitutional-law/resources/7.2-okwedy-v-molinari#/
https://cite.case.law/f3d/333/339/

Two opinions: 
https://opencasebook.org/casebooks/114149-advanced-constitutional-law/resources/7.1-lombard-v-louisiana#/
https://cite.case.law/us/373/267/
