### ISSUE TITLE
Add User Create and Casebook Author Edit to Rails Admin

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#532]
1. Admins should be able to make accounts in Rails Admin
2. Admins should be able to transfer ownership/authorship of a casebook from one user to another in the Rails Admin

**Comment by cgruppioni** [comment]
- Roles should travel if anyone in that collaborator publishes then create draft
- cloning should have no previously attached collaborators

**Comment by bjohnson747** [comment]
updates per our Roles discussion:

Only two roles: Owner, and Editor. Owner role remains as-is, Editor can:
-Revise casebook (aka create new draft of existing casebook)
-Publish casebook
-Annotate items in casebook
-Edit casebook contents (add/remove/edit resources/sections, edit headnote fields + titles, etc)

Admins need ability (via checkbox, for example) to select if Editors get attribution and are displayed as additional authors.

Casebook (+ associated drafts) should appear in both Owners and Editors' dashboards.

**Comment by cgruppioni** [comment]
In staging and prod

```
Content::Collaborator.all.each do |collaborator|
  if collaborator.role == 'owner'
    collaborator.update(has_attribution: true)
  end
end
```

**Comment by bensteinberg** [comment]
@cgruppioni, did you run that, or do you want me to run it?

**Comment by cgruppioni** [comment]
@bensteinberg It's notes for the next iteration of this issue that hasn't been deployed yet. I'll run it in prod console when it is deployed though - thanks for checking!
