### ISSUE TITLE
added cases not showing up in export

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#549]
@abziegler encountered issue where he added cases to a casebook, then after exporting the whole casebook the newly added cases weren't showing up (but a different resource - link - did show up).

I can't re-create this issue on my end, but it is occurring on his machine, which makes us think it's some kind of caching issue.

**Comment by rebeccacremona** [comment]
@abziegler can you still reproduce this? If yes, can you document steps to reproduce?

If this is still an issue, see https://github.com/harvard-lil/h2o/commit/354f1879722e7c963a682501b706ca816e9a0706 for possible mitigation
