### ISSUE TITLE
Publishing draft casebook sometimes instead creates separate casebook

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#558]
Started with this casebook: https://opencasebook.org/casebooks/65582-contracts-reading-group-for-export-only/

Created a draft: https://opencasebook.org/casebooks/90960-contracts-reading-group-for-export-only/layout

Elided item: https://opencasebook.org/casebooks/91086-contracts-reading-group-for-export-only/resources/2.1-dougherty-v-salt/annotate?annotation-id=493116

Then when i clicked Publish, it took me to a separate, newly created version of the casebook (that included the change I just made): https://opencasebook.org/casebooks/91086-contracts-reading-group-for-export-only

The original casebook and casebook draft (listed at the top ^ ) remain. I made no other changes to these items, for troubleshooting's sake.

--------

I tried to re-create this issue with a couple of other casebooks - this happened on staging originally with a different casebook - but have yet to do so successfully; i.e., just eliding a item in a draft was not enough to make this issue recur. I don't know if there's a something specific that makes this happen every time, or if there's something in the publish-casebook code that's being intermittently funky.

**Comment by cgruppioni** [comment]
WIP: https://github.com/cgruppioni/h2o-1/tree/618-cloning-bug
