### ISSUE TITLE
UX for create-new-book

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#57]
Extend designs to cover create-new-book UX

**Comment by abziegler** [comment]
Based on whiteboarding by @cgruppioni and me, I've extended designs to cover most interactions needed for the create-new-book UX: https://invis.io/PFBIF4P4H

**Comment by cgruppioni** [comment]
Couple small things
- on the case page the view selections ( layout, casebook details etc.. ) it says Edit & Annotate -- You're already in edit mode at this point so it should just say annotate? 
- Adding a resource I believe cases, texts, links should all be singular -- you can only add one item at a time with 'add resource'. You would have to go back to add a second link.

**Comment by cgruppioni** [comment]
I also almost want the "this casebook is a draft" banner to be below the header instead of above it. I actually didn't really see it at first and scrolled up to make sure it was on edit mode. Something to user test or play around with? It might look bad below the header.

**Comment by abziegler** [comment]
"on the case page the view selections ( layout, casebook details etc.. ) it says Edit & Annotate -- You're already in edit mode at this point so it should just say annotate?"

Done. New designs uploaded.

**Comment by abziegler** [comment]
> Adding a resource I believe cases, texts, links should all be singular -- you can only add one item at a time with 'add resource'. You would have to go back to add a second link.

Done. New designs uploaded. Re-upload probably kills the interactivity in InDesign, but you can see all the screens and get the picture

**Comment by abziegler** [comment]
> I also almost want the "this casebook is a draft" banner to be below the header instead of above it. I actually didn't really see it at first and scrolled up to make sure it was on edit mode. Something to user test or play around with?

I kind of like it at the top, so we can maintain the UI pattern (nav, then search, then book tabs) consistently across all book-view screens. Maybe we give the banner a little more height? We'll defintely iterate on it based on user feedback, but let's take a position now and go with it for now. @phillipsm  any views?
