### ISSUE TITLE
Allow verified authors to insert links into text blocks

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#573]
Our textblock editor does not allow links. It should. This can be a spam magnet if it's wide open, so we should limit to verified authors.

**Comment by rebeccacremona** [comment]
Added in https://github.com/harvard-lil/h2o/pull/992/files, for all logged in users. 

This is how they look.
![image](https://user-images.githubusercontent.com/11020492/71021099-9ea0a700-20cb-11ea-8ed0-09b15d0aa8aa.png)
