### ISSUE TITLE
On casebook view, change "Layout" to "Contents"

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#59]

**Comment by abziegler** [comment]
Keep as is. 'Layout' is for draft mode, when user can reorder items. 'Contents' is for read mode, when user can't.

**Comment by emmalemma** [comment]
Related to this: Is there an edit-layout view for sections of a casebook? There is a read-section view, and I'd assumed therefore also an edit view, but would it be more straightforward if editing the layout always happens in the main table of contents? (Will that become unwieldy for very large casebooks?)

**Comment by abziegler** [comment]
Great Q. 

I lean toward keeping all the edit-layout activity in the Layout sub-view and all the read (or annotate) activity in the Read (or Annotate) sub-view. Let's focus all the layout actions - moving, nesting, re-ordering - in one sub-view. This probably means we do not enable any of those actions - e.g. dragging, dropping, etc. - anywhere except the Layout sub-view.

> Will that become unwieldy for very large casebooks?

It could. Definitely something to watch for as we introduce this to faculty users. I wouldn't assume this friction, or prioritize it over the likely confusion/complexity of having multiple ways to edit-layout on a section. 

Other thoughts, or does this seem sensible to you?
