### ISSUE TITLE
PDF export has a bullet point next to each item

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#6]
exported PDF has a bullet point next to each individual item's title, while the live in-browser view doesn't. These bullets should be removed from export.

![screen shot 2015-09-08 at 3 02 40 pm](https://cloud.githubusercontent.com/assets/12850389/9744573/a9400602-563a-11e5-9018-d96090ed53a7.png)

**Comment by bjohnson747** [comment]
PDF export issues remain in current iteration of H2O.

**Comment by abziegler** [comment]
Closed b/c moot
