### ISSUE TITLE
Create "Add Section" modal

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#603]
Revised by @abziegler 
______

UX for "Add Section" is clunky: (a) Loads a separate page, (b) accepts user input on title/subtitle/headnote, (c) renders just-created, empty section. Clunkiness comes from multiple page loads and the render of an empty section, which makes sense only if author's next action is to add a resource to the empty section.

Some authoring use cases will prefer an "Add Section" UX that lets them create the entire structure of the book, before adding any resources. This suggests rendering the full contents, rather than the new, empty section, after a new section is created. 

One possible approach, suggested by @cgruppioni, is to repurpose/extend the "Add resource" modal to handle sections, and then to render full contents upon creation of new section. 

Another possible approach, suggested by @bjohnson747, is to create a UI for modular section creation.

This needs design, experimentation and feedback. Lots of different ways to go here. Should approach with an eye toward vue.js enhancements in process and future work on automated ingest.

**Comment by abziegler** [comment]
@cgruppioni reports via @leppert that extending the "Add Resource" modal won't implicate Vue

**Comment by holtchesley** [comment]
Covered via QuickAdd.
