### ISSUE TITLE
Annotator issues in Firefox

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#604]
(Testing on: https://opencasebook.org/casebooks/73025-constitutional-law-demo-casebook-2/resources/1.5-childs-et-al-v-catlin-et-al/annotate)

1) Already having an annotation in a paragraph causes additional annotations to be placed incorrectly: http://recordit.co/ySQpI1BLEq
2) Can elide an individual paragraph, but attempting to elide more than one causes incorrectly placed annotation: http://recordit.co/s2TTqcAZkK
3) Annotation sidebar should follow the selected text - or jump down - as it's being clicked+dragged and the browser window scrolls; in Firefox it does not: http://recordit.co/5OtcsVvXS8

Issues not occurring in Chrome or Safari.

**Comment by leppert** [comment]
A little more info on No.2: the exception is thrown when bridging paragraphs because range.endContainer returns the outer div.case-text rather than the paragraph’s text node.

**Comment by leppert** [comment]
PR #607 fixes items 1 and 3. Item 2 has been spun out into its own ticket here https://github.com/harvard-lil/h2o/issues/609
