### ISSUE TITLE
Export issues: embedded images, bulleted + numbered lists

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#606]
1. Embedded images not showing up in export:
Images can be inserted (by URL) via the text editor into headnotes and text blocks, but do not show up in export for either.
Added image into this section's headnote + first text block for testing: https://opencasebook.org/casebooks/33563-property-fall-2015-bruce-mann/sections/1-i-possession-and-property

2. Bulleted lists in headnotes:
Bullet points do not show up - the 'unknown item' box appears in Word instead, and
-it appears to remove any regular text thats show up after styled (bold, em) text
-styled text shows up twice (once regular, and once styled), and 
-bold text adds a line-break. 
The below example shows that no standard text appears, but the 'Em' words do appear:

Original:
![screen shot 2018-11-30 at 11 50 50 am](https://user-images.githubusercontent.com/12850389/49303327-7382ef80-f497-11e8-9ae8-42951b0b2cad.png)
Export:
![screen shot 2018-11-30 at 11 53 10 am](https://user-images.githubusercontent.com/12850389/49303329-767de000-f497-11e8-9eb9-a6a4979336cb.png)

Another example:
Original: 
![screen shot 2018-11-30 at 12 56 22 pm](https://user-images.githubusercontent.com/12850389/49307180-5dc6f780-f4a2-11e8-9378-dbef3fbad08d.png)
Export:
 ![screen shot 2018-11-30 at 1 16 55 pm](https://user-images.githubusercontent.com/12850389/49307187-63bcd880-f4a2-11e8-8c30-411acc696408.png)

3. Numbered lists in headnotes:
Same as above: styled text appears twice, and it clears any regular text that comes after the styled text.
Original: 
![screen shot 2018-11-30 at 1 41 52 pm](https://user-images.githubusercontent.com/12850389/49308311-ebf0ad00-f4a5-11e8-8928-c0f10eec3a53.png)
Export:
![screen shot 2018-11-30 at 1 42 01 pm](https://user-images.githubusercontent.com/12850389/49308319-f0b56100-f4a5-11e8-8e1f-acd951b1c84c.png)

More than one type of styled text on the same line gives it more trouble.

4. Bullet + Numbered lists in text blocks, have similar issues:

Original:
<img width="547" alt="screen shot 2018-11-30 at 1 48 26 pm" src="https://user-images.githubusercontent.com/12850389/49308636-d760e480-f4a6-11e8-9e2e-95b0ea1b7e8a.png">
Export:
![screen shot 2018-11-30 at 1 48 38 pm](https://user-images.githubusercontent.com/12850389/49308640-d9c33e80-f4a6-11e8-8f8c-216ba544db6c.png)

I was testing items in this casebook (mine): https://opencasebook.org/casebooks/33563-property-fall-2015-bruce-mann/sections/1-i-possession-and-property

**Comment by bjohnson747** [comment]
**I noticed bullet points are not exporting correct in Text body, not just headnotes. For example, below is correct bullet points on the left, bullet point issue on the right:
![screen shot 2018-12-11 at 7 07 53 pm](https://user-images.githubusercontent.com/12850389/49838316-2268da80-fd78-11e8-8d6c-cbeb3966da43.png)

IMO this raises the priority of this fix

**Comment by rebeccacremona** [comment]
Uesr-supplied images in exports (or in-browser) is it's own can of worms; everything else in this ticket was resolved by switching to pandoc + our customization of pandoc.
