### ISSUE TITLE
unintentional casebook clones appearing

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#618]
Casebook that myself and others have been working on has had clones being created, even though (best that we can tell) the clone button has not been being hit.

The original casebook being worked on: https://opencasebook.org/casebooks/96420-open-source-property/layout
the clone that appeared: https://opencasebook.org/casebooks/109233-ignore-error-unwanted-clone-open-source-property/layout
@cgruppioni

**Comment by cgruppioni** [comment]
```

  def edit
    # editing a section takes you to a cloned casebook and
    # the original casebook stays published
    @casebook = @casebook.clone(owner: @casebook.owner, draft_mode: true)
    @section = @casebook.contents.find_by(copy_of_id: @section.id)
    @decorated_content = @content.decorate(context: {action_name: action_name, casebook: @casebook, section: @section, type: 'section'})
    redirect_to layout_section_path(@casebook, @section) 
  end
```
