### ISSUE TITLE
Welcome email auto-sent to users after account confirmed

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#628]
A welcome email being sent to new users, after their accounts have been confirmed.

**Comment by bjohnson747** [comment]
DRAFT TEXT:

Hello and welcome to H2O!

Your account is confirmed and all of H2O's features now are available, including access to the more than 6.4 million U.S. cases in the [case.law](case.law) database.  

Visit the [User Guide](https://about.opencasebook.org), our [blog](https://blogs.harvard.edu/h2oharvard), or view our getting started [videos](https://about.opencasebook.org/other-resources/)! Along with letting you easily make a new - or cloning an existing - casebook, H2O can be used to create a:

- Interactive, updatable syllabus

- index of cases used in the course

- Supplementary materials list

Contact us with any questions at info@opencasebook.org 

Happy H2Oing!

**Comment by cgruppioni** [comment]
Duplicate of #659
