### ISSUE TITLE
Annotations: client side rendering

### ISSUE THREAD

**Issue by leppert** [harvard-lil/h2o#629]
## Abstract

At the moment, the heavy lifting of placing annotations within the text during rendering is handled on the backend by Ruby. This works well enough today but, in order to enable annotating text without refreshing the page, we'll need this logic to exist on the front end.

## Primary Goals

1) Enable annotation CRUD actions on the front end without requiring a page refresh
2) Match current annotation functionality
3) Avoid code duplication

## Secondary Goals

4) Improve reliability and resilience of annotation placement and rendering i.e. make annotations less brittle, both in relationship to each other (squashing edge cases like #609) and in the face of changes to the underlying text
5) Improve accessibility 

## Notes on Approach

_Goal-1_ and _Goal-2_ will be addressed by continuing our Vue work, porting the Ruby logic over to JS. _Goal-3_ points to removing that Ruby logic once this JS work is complete. _Goal-4_ might call for reevaluating how the Ruby logic works and annotations are stored rather than simply doing a straight port to JS.

## Existing Code

The Ruby code that handles most of this today is located in the following files:

- https://github.com/harvard-lil/h2o/blob/master/app/models/content/resource.rb
  Functions as the entry point for the case HTML to be parsed into Ruby objects and iterated on
- https://github.com/harvard-lil/h2o/blob/master/app/services/apply_annotation_to_paragraphs.rb
  Handles the insertion annotation HTML and the bounding logic around that

## Open Questions

- Is there anything about the Ruby code that might necessitate keeping it around after the JS has been implemented? If so, is there a way to achieve the same result via another route, perhaps using server side JS rendering. For instance, is the Ruby code used to render in contexts other than a standard JS executing browser e.x. for case exports to Word files or perhaps for GoogleBot?
- Are there any low hanging items for Goal-4 that might, with proper consideration today, improve the system while also simplifying the port to JS? For instance, today we place annotations based on paragraph numbers but there are instances where the numbering of paragraphs might change; would it make sense to consider assigning UUIDs or GUIDs based on hashes of the text to these paragraphs such that they could be properly placed even after the surrounding paragraphs have been changed?

**Comment by cgruppioni** [comment]
**Open question 1:** Yes, the `annotated_paragraphs` method (https://github.com/harvard-lil/h2o/blob/master/app/models/content/resource.rb#L18) is used in exporting content (https://github.com/harvard-lil/h2o/blob/master/app/views/content/casebooks/export.haml#L28)
