### ISSUE TITLE
When elision is open/expanded, new elisions get placed incorrectly

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#633]
When an elision is opened to view hidden text, then a new elision is made in that paragraph, the new elision gets placed in the wrong location.

video: https://drive.google.com/file/d/10bNpoJAALPsJggZtgiFesA24S8nCgBWp/view?usp=sharing

**Comment by cgruppioni** [comment]
@bjohnson747 can this be closed?

**Comment by bjohnson747** [comment]
@cgruppioni still occurring :'(

**Comment by leppert** [comment]
For posterity, in this case the bug came back because the text we added for screen readers, which is only in the DOM when the elision is expanded, was being included in the offset count for the new annotation. This text is now excluded from that calculation.
