### ISSUE TITLE
Full paragraph and multi-paragraph highlights not working

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#642]
On stage, highlight-style annotations are working beautifully for text selections inside paragraphs (e.g. partial sentences, partial paragraphs, single words).

Highlight-style annotations are not working completely for full-paragraph text selections. It appears an annotation is registering (b/c the small annotation icon in margin does display), but the text is not changing background color.

Example:

![highlighting](https://user-images.githubusercontent.com/2140548/51751553-1b293200-2083-11e9-8021-ab686cc1e300.png)

**Comment by abziegler** [comment]
Update: multi-paragraph highlight attempts display an error.
![highlight error](https://user-images.githubusercontent.com/2140548/51751953-2d57a000-2084-11e9-8085-1fde7e7b4b16.png)

**Comment by leppert** [comment]
@abziegler would you mind testing on a different case as well?

**Comment by abziegler** [comment]
@leppert same results with 98 Wash. App. 662 (https://api.case.law/v1/cases/155841/)

**Comment by leppert** [comment]
@abziegler is that a case that came in from capapi as well? If so, mind trying on a non-capapi case?

**Comment by abziegler** [comment]
Yes - those were CAP. 

With not-CAP case, the highlighting works (partial, full and multi-paragraph). However, a full-para highlight removes the paragraph number (perhaps a separate bug):

![highlights - non cap](https://user-images.githubusercontent.com/2140548/51752455-8e33a800-2085-11e9-80ca-ba884d4d6ff5.png)

**Comment by abziegler** [comment]
Clarification on original bug: it's not just full-paragraph highlights that save without changing background; it appears to be any highlight that starts at beginning of paragraph:

![h2o-begin-highlight](https://user-images.githubusercontent.com/2140548/51752644-f7b3b680-2085-11e9-8507-0f5d8219b000.png)

**Comment by leppert** [comment]
The disappearing full paragraph highlighting was fixed by: https://github.com/harvard-lil/h2o/commit/0bfe51a2330ebddfb3613074a77a52d43b4daa25
