### ISSUE TITLE
Multiple annotations in one paragraph acting funky

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#647]
(re: staging/Vue annotation)
This paragraph has two highlighted sections already with one replacement text "yaya" that goes across both of them:
![screen shot 2019-01-25 at 3 54 27 pm](https://user-images.githubusercontent.com/12850389/51772323-b937ef00-20b9-11e9-9ec5-38bf2c4c79df.png)

I go to add another highlight: 
![screen shot 2019-01-25 at 3 54 35 pm](https://user-images.githubusercontent.com/12850389/51772387-dc629e80-20b9-11e9-98bf-fb7eb4a0bb3e.png)

And its placed in the wrong location:
![screen shot 2019-01-25 at 3 54 39 pm](https://user-images.githubusercontent.com/12850389/51772444-00be7b00-20ba-11e9-8ec2-0aad8eb9c8b3.png)

This from paragraph #15 in this: https://h2o-dev-test.lil.tools/casebooks/101663-food-law-casebook/resources/1.1.4-whitman-administrator-of-environmental-protection-agency-et-al-v-american-trucking-associations-inc-et-al/annotate

**Comment by leppert** [comment]
Fixed by https://github.com/harvard-lil/h2o/commit/626eab84e41e8e96df6059d945e36d2b8d93aa8c
