### ISSUE TITLE
Next steps for Vue annotations

### ISSUE THREAD

**Issue by leppert** [harvard-lil/h2o#652]
## Summary

As of d827327, Vue based annotations are working well in master, but there's always room for improvement. The following are a few improvements that would be worth making immediately after deploy:

- GUID based annotation insertion
- Shift annotation saving out of TheAnnotator
- Integrate Vue Router
- Add JS/Vue unit testing
- Factor out Ruby based annotation rendering

## GUID based annotation insertion

Annotations are rendered by Vue in reaction to annotation objects being [appended](https://github.com/harvard-lil/h2o/blob/master/app/webpacker/store/modules/annotations.js#L115-L116) to the Vuex annotations store. For the initial page render, [TheResourceBody](https://github.com/harvard-lil/h2o/blob/master/app/webpacker/components/TheResourceBody.vue#L80) calls the annotation API and gets a list of the existing annotations, including their `id`s, and appends them to this list. These `id`s are then used to instantiate Vuex [annotations_ui](https://github.com/harvard-lil/h2o/blob/master/app/webpacker/store/modules/annotations_ui.js) objects that hold UI state for the annotations on the page, mainly whether the annotations should be expanded or not. This creates a clean separation between the data that is saved to the DB as an "annotation" and the data that's only needed for the state of the UI. Various components on the page will use the annotation ID to tie these two data representations together.

However, this means that `id`s, which are managed by the DB and only exist after creation of the annotation in the DB, become critical for inserting annotations into the page. This makes it difficult to, for instance, allow optimistic insertions of annotations on the page to be displayed while the API `create` action is called in the background. We cheat this a little bit when it comes to `ReplacementAnnotation`s, which are created inline in the page, by [inserting an annotation](https://github.com/harvard-lil/h2o/blob/master/app/webpacker/components/TheAnnotator.vue#L150-L157) with `id=null`, where `null` is its own sort of unique `id`, and then updating the UI state with a proper id [when it comes back from the API](https://github.com/harvard-lil/h2o/blob/master/app/webpacker/store/modules/annotations.js#L101-L107). This works, but only when there's a single unsaved annotation on the page.

A better solution is one where we create some sort of GUID for annotations that have yet to be saved which can then be replaced once a proper `id` comes back from the DB. This could be as simple as a timestamp or as complex as a proper GUID in the formal sense. The one additional requirement is that we need a way to determine when an annotation is waiting to be saved. Today, [we use an `id == null` test](https://github.com/harvard-lil/h2o/blob/master/app/webpacker/components/AnnotationBase.vue#L36-L38) to determine this. In the future, it could be that the temporary GUID begins with the string "new". I don't like that this means `id` could be either a string or an integer, but it might be better than storing a new property on the `annotations` Vuex representation. Or perhaps we store this on the `annotations_ui` representation to keep this separation clean. Either way, it's readily solvable.

## Shift annotation saving out of TheAnnotator

Once GUIDs have been worked into the annotation system, this should allow us to factor [the logic for saving annotations](https://github.com/harvard-lil/h2o/blob/master/app/webpacker/components/TheAnnotator.vue#L137-L148) to the API out of TheAnnotator and into the respective annotation types, [as it is with the ReplacementAnnotation](https://github.com/harvard-lil/h2o/blob/master/app/webpacker/components/ReplacementAnnotation.vue#L81-L89). For annotations without `content`, like `HighlightAnnotation`s, the API logic would simply be triggered in the `created` hook from the `head` annotation template instance. For annotations with content, like `LinkAnnotation`s, this would allow us to move the [link creation context menu](https://github.com/harvard-lil/h2o/blob/master/app/webpacker/components/TheAnnotator.vue#L27-L35) out of `TheAnnotator` and into `LinkAnnotation`, thereby having all of a link's creation and editing functions happen within that component.

## Integrate Vue Router

Because we're only using Vue on a single page at the moment, there hasn't been a need for [Vue's Router](https://router.vuejs.org). However, Vue work will only expand throughout the system and it might be useful to move the somewhat rudimentary Vue bootstrapping logic from [`vue_app.js`](https://github.com/harvard-lil/h2o/blob/master/app/webpacker/packs/vue_app.js.erb) to a Vue Router route as a way to establish the convention and allow for additional routes to easily be added in the future.

## Add JS/Vue unit testing

Testing of the Vue work could be greatly improved in general (including system tests), but would be good to get a JS unit testing harness up and running, especially to test the functions in [ResourceSection.js](https://github.com/harvard-lil/h2o/blob/master/app/webpacker/components/ResourceSection.js). Vue [has a pretty good unit testing story](https://vuejs.org/v2/guide/unit-testing.html) out of the box, and we'll likely just need to plug one of those into our existing Rake tasks.

## Factor out Ruby based annotation rendering

With the integration of the Vue based annotation rendering, we now have duplication (and deviation) of the annotation rendering logic as the [Ruby annotation rendering](https://github.com/harvard-lil/h2o/blob/master/app/services/apply_annotation_to_paragraphs.rb) is still utilized for exports. Ideally this logic would be factored out in favor of the JS logic, which will require backend JS execution and, potentially, a full server side rendering (SSR) solution for Vue. While Vue has a [good SSR story](https://ssr.vuejs.org) out of the box, it's likely there will still be quite a bit of work involved in getting this up and running for exports.

**Comment by abziegler** [comment]
closing b/c broken into individual issues
