### ISSUE TITLE
Links open in a new tab/window

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#658]
I did not expect this; why override the default? If opening links in a new/ tab/window, add a labeled icon next to links https://en.wikipedia.org/wiki/Help:External_link_icons

**Comment by cgruppioni** [comment]
@leppert @rebeccacremona You are both correct. It sounds like adding a labeled icon is best practice so let's do that

**Comment by rebeccacremona** [comment]
Totally; just thought I'd leave a note while I was thinking of it 🙂

**Comment by leppert** [comment]
@cgruppioni I added this in https://github.com/harvard-lil/h2o/commit/bcbff3484eba116a6ee317d94dfbb172e2585712, which includes a wikimedia icon licensed under GNU. Do we keep a record of things in the codebase that have various open source licenses? /cc @abziegler
