### ISSUE TITLE
Exporting resource note annotation text shows inline 

### ISSUE THREAD

**Issue by cgruppioni** [harvard-lil/h2o#660]
Note annotations should show up like link annotations, with an asterick as a footnote indicator and the content bottom of the resource. 

![screen shot 2019-02-11 at 2 16 47 pm](https://user-images.githubusercontent.com/14900328/52587333-cc5ff400-2e07-11e9-96d9-8fff163f453c.png)
![screen shot 2019-02-11 at 2 17 00 pm](https://user-images.githubusercontent.com/14900328/52587341-cf5ae480-2e07-11e9-90d7-dd1e93ad7907.png)
![screen shot 2019-02-11 at 2 17 07 pm](https://user-images.githubusercontent.com/14900328/52587345-d124a800-2e07-11e9-8f60-2d50f9e4067c.png)

----------------------------------

Currently they show up as inline
![screen shot 2019-02-11 at 2 04 39 pm](https://user-images.githubusercontent.com/14900328/52586635-ffa18380-2e05-11e9-833e-af4130290361.png)
![screen shot 2019-02-11 at 2 05 09 pm](https://user-images.githubusercontent.com/14900328/52586676-1051f980-2e06-11e9-9a68-77b6db9d738a.png)
https://h2o-dev-test.lil.tools/casebooks/101502-regulation-of-financial-institutions-fall-2015/resources/1.1.2-state-ex-rel-duffy-atty-gen-v-western-auto-supply-co/annotate#

-----------------------

Here is the PR where this feature was originally set #492 

This is what it used to look like for example: 
![screen shot 2019-02-11 at 1 48 32 pm](https://user-images.githubusercontent.com/14900328/52587197-873bc200-2e07-11e9-8b0d-0da1abcd9d02.png)
![screen shot 2019-02-11 at 1 48 34 pm](https://user-images.githubusercontent.com/14900328/52587202-899e1c00-2e07-11e9-9995-ea9110f4ec23.png)

**Comment by leppert** [comment]
@cgruppioni Looks like this was introduced in this commit, awhile back. Digging in to figure out what changed. https://github.com/leppert/h2o/commit/e82405aa7c44b303e7a363b68ed5c28234c7657d
