### ISSUE TITLE
Link resources don't show associated link when viewed

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#661]
ex., https://opencasebook.org/casebooks/114864-music-digital-media-spring-2019/resources/3.6-emi-v-premise-media-index-no-610209-08-ny-sup-ct-ny-co-order-august-13-2008-pdf-read-pp-1-3-6-19 - instead of the link being shown it just says 'undefined'

**Comment by leppert** [comment]
Fixed by c3e703c
