### ISSUE TITLE
Highlighted entire section of H2 text does not cause highlight to appear

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#663]
tagging part of h2 text works: 
<img width="751" alt="screen shot 2019-02-11 at 2 22 59 pm" src="https://user-images.githubusercontent.com/12850389/52587751-b7d02b80-2e08-11e9-8b7d-63cbf8aa458b.png">
tagging whole H2 text causes it to not appear (though the edit pencil still shows, so the annotation is being placed even if the highlight isn't showing)
![screen shot 2019-02-11 at 11 47 41 am](https://user-images.githubusercontent.com/12850389/52587831-fcf45d80-2e08-11e9-9883-f737a4842f78.png)

**Comment by leppert** [comment]
Fixed by 5f2d5c1
