### ISSUE TITLE
Factor out Ruby based annotation rendering

### ISSUE THREAD

**Issue by cgruppioni** [harvard-lil/h2o#677]
Originally brought up in #652 

With the integration of the Vue based annotation rendering, we now have duplication (and deviation) of the annotation rendering logic as the [Ruby annotation rendering](https://github.com/harvard-lil/h2o/blob/master/app/services/apply_annotation_to_paragraphs.rb) is still utilized for exports. Ideally this logic would be factored out in favor of the JS logic, which will require backend JS execution and, potentially, a full server side rendering (SSR) solution for Vue. While Vue has a [good SSR story](https://ssr.vuejs.org) out of the box, it's likely there will still be quite a bit of work involved in getting this up and running for exports.

Benefits: 

- consistency between exported and website code
- export code is confusing and hard to maintain

**Comment by cgruppioni** [comment]
* change how aside tags are processed

**Comment by abziegler** [comment]
Note related https://github.com/harvard-lil/h2o/issues/697 - per @cgruppioni this should be addressable via this enhancement

**Comment by cgruppioni** [comment]
Waiting for Pandoc contributions before closing issue
