### ISSUE TITLE
Export not showing formatting changes to headnotes (section export)

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#678]
On stage - When exporting with or without annotations, the export isn't reflecting tweaks I made to the section headnote + first resource headnote.

When I export a resource by itself that has headnote changes, these show up fine.

Example section: https://h2o-dev-test.lil.tools/casebooks/94986-quinn-clone-for-bug-test-2-3-public-corps/sections/2.2.9-piercing-the-corporate-veil
Resource: https://h2o-dev-test.lil.tools/casebooks/94986-quinn-clone-for-bug-test-2-3-public-corps/resources/2.2.9.1-children-2-k

**Comment by cgruppioni** [comment]
Seemed to be mostly a caching problem. When deleted all the cookies page worked like it was supposed to
