### ISSUE TITLE
Vue strips out whitespace from annotations that contain a single space

### ISSUE THREAD

**Issue by leppert** [harvard-lil/h2o#680]
There's a test for this, that's currently being skipped, here:
https://github.com/harvard-lil/h2o/blob/master/test/javascript/components/ResourceSection.test.js#L90-L101

This is an issue primarily when an annotation bridges elements, though it would also be an issue in the rare case that someone annotated a space character by itself. For example:

```html
<em>foo</em> <em>bar</em>
```

Creating a highlight across "oo ba" in the markup above creates results in the following pseudo code:

```html
<em>f<highlight>oo</highlight></em><highlight></highlight><em><highlight>ba</highlight>r</em>
```

Notice that the space within the second `<highlight>` is missing.

Changing the [whitespace compiler option](https://github.com/harvard-lil/h2o/blob/master/config/webpack/loaders/vue.js#L9) to its default of "preserve" would seem like the logical way to fix this, but this also removes the space. Converting the space to a `&nbsp;` while also setting `whitespace: 'preserve'` does render the space, though this will potentially introduce other whitespace problems in the templates that would need to be sorted through carefully; this might be our only option. The only other escape hatch with Vue and whitespace is with `<pre>` tags, the contents of which are left alone; perhaps there's a solution there.

Complicating the issue is that the `vue-jest` plugin doesn't let you set Vue template compilation options, so it's not currently possible to run tests with `whitespace: 'condense'` i.e. the test env doesn't match the prod output. Yet.

**Comment by cgruppioni** [comment]
"It’s just a hack and it adds characters to the resource which always feels dicey. It works because the browser collapses the double space back down to a single space.

Or rather, that’s why it doesn’t destroy offset counts for subsequent annotations."
