### ISSUE TITLE
Exporting a 2nd time via Chrome doesn't reflect changed annotations

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#684]
in Chrome, when i make a new annotation to a resource i've already exported, it doesn't show up the second time i export it. clearing my cache makes it export the updated version. This issue does not occur in Safari.

Example, from this resource: https://h2o-dev-test.lil.tools/casebooks/94986-quinn-clone-for-bug-test-2-3-public-corps/resources/2.2.5.2-dgcl-sec-245-restating-the-certificate/annotate#

Export does not have the elision after (b), which i had added after doing 1st export: 
![screen shot 2019-02-25 at 4 50 59 pm](https://user-images.githubusercontent.com/12850389/53371572-926e1200-391e-11e9-94a4-4806b1ec9748.png)

**Comment by leppert** [comment]
@bjohnson747 If this is fixed for you based on the new cache prevention headers I added, go ahead and close this ticket. I was unable to reproduce in Chrome, locally, so unable to confirm that fixed the problem.

**Comment by bjohnson747** [comment]
Confirmed! Fixed.
