### ISSUE TITLE
Eliding footnote number should elide footnote text, and vice-versa

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#688]
Eliding a footnote in the text, ex. here: 
![screen shot 2019-02-26 at 5 07 50 pm](https://user-images.githubusercontent.com/12850389/53451483-db8c9780-39ec-11e9-9fe8-f4f513066739.png)

Should elide the footnote content itself, here:
![screen shot 2019-02-26 at 5 08 10 pm](https://user-images.githubusercontent.com/12850389/53451505-e5ae9600-39ec-11e9-9d98-97410b4120be.png)

**Comment by leppert** [comment]
FWIW when implementing the Vue work, I [ported over logic](https://github.com/harvard-lil/h2o/blob/master/app/webpacker/components/FootnoteLink.vue#L28-L31) from the app that was explicit about allowing footnotes for elided passages to be clicked, thereby expanding the passage before scrolling to it. This logic also worked in the other direction. All that to say, it looked like someone had thought about this use case and decided leaving the footnote accessible was the route to go. Worth exploring that Chesterton's Fence.

**Comment by lizadaly** [comment]
Since footnote cleanup is important, this might be a nice-to-have to remove the necessity of manual footnote removal. We'll want to check whether this particular case still behaves this way.
