### ISSUE TITLE
When a capapi case doesn't have content, it doesn't save and creates an empty section instead 

### ISSUE THREAD

**Issue by cgruppioni** [harvard-lil/h2o#694]
For example. for this case https://api.case.law/v1/cases/1688775/

There should be an error message instead and it does not create an empty section

**Comment by abziegler** [comment]
That case has content: https://api.case.law/v1/cases/1688775/?full_case=true

But in general, it's true that if CAP has nothing to give H2O it should display error message rather than create empty section/resource
