### ISSUE TITLE
Footnote handling for cases ingested from CAP

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#697]
H2O consumes CAP-flavored HTML when an author wants to add a case that isn't already in the H2O database.

CAP's HTML presents footnotes like this:

`<aside data-label="2" class="footnote" id="footnote_2"><a href="#ref_2">2</a><p>[footnote text]</p></aside>`

When the case gets displayed in H2O, however, the `aside` elements gets lost, along with the `id` attribute needed to make the footnotes link internally. We should be preserving that `id` attribute so readers/authors can use footnotes to navigate.

**Comment by leppert** [comment]
Removing `aside` from these two spots will fix this:

https://github.com/harvard-lil/h2o/blob/master/app/webpacker/libs/html_helpers.js#L28
https://github.com/harvard-lil/h2o/blob/master/lib/html_helpers.rb#L10

But could have consequences for other cases that use `aside` differently and for existing annotations where leaving the `aside`s changes the paragraph count.
