### ISSUE TITLE
Footnotes should be marked up as such in export file

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#698]
Currently in our DOCX export files, in-text footnote references are styled as normal `Case Text`. They should be tagged as footnote references so user can adjust styles. Likewise for the footnotes themselves.

**Comment by rebeccacremona** [comment]
Learned today: true docx footnotes are are described by two separate xml files within the docx, unlike paragraphs, highlights, and the other elements h2o exports. Footnotes do not appear to me to be supported by the htmltodoc gem currently responsible for the export... So, while certainly achievable, this ticket is a bigger job than it sounds like.

**Comment by abziegler** [comment]
Thanks @rebeccacremona. Any ideas on smallish jobs to get us part of the way there? What we need most at this point is to have Word styles/classes automatically applied that will distinguish footnote text from other text, so authors can restyle footnotes globally in Word. It isn't essential to have the footnote text linked in-doc to footnote refs.
