### ISSUE TITLE
Modify CSS for footnotes to display num and text on same line

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#731]
Consider export implications
Consider implications for old footnotes with different (or no) structure

**Comment by abziegler** [comment]
Current:
![h2o-footnotes](https://user-images.githubusercontent.com/2140548/55893988-4a7e1400-5b87-11e9-9c28-9201563b9790.png)

**Comment by abziegler** [comment]
Seems like this has already been addressed. But period trailing footnote number isn't being handled as superscript.

![image](https://user-images.githubusercontent.com/2140548/73213547-5f2f9680-411e-11ea-9da9-757d9cdd0e0b.png)

**Comment by jcushman** [comment]
See https://github.com/harvard-lil/capstone/issues/989 -- these periods want to be stripped at the CAP level.
