### ISSUE TITLE
Remove ActsAsTaggable ( relic from old h2o )

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#752]
ActsAsTaggableOn.delimiter is deprecated and will be removed from v4.0+, use  a ActsAsTaggableOn.default_parser instead

**Comment by cgruppioni** [comment]
Remove ActsAsTaggable, other search words: taggings, tag_list, etc.. 

https://github.com/mbleigh/acts-as-taggable-on
