### ISSUE TITLE
Render vue in rails without the use of @include_vuejs variables 

### ISSUE THREAD

**Issue by cgruppioni** [harvard-lil/h2o#778]
Vue is only loaded on pages that have the @include_vuejs variable set to true. Right now, the only thing holding us back from removing this layer of logic and having Vue load on every page is an error we're getting Ckeditor:  
```
Error compiling template:
Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as s<script>, as they will not be parsed
```

Some possibly helpful resources are: 
- https://github.com/adambutler/vuejs-rails
- https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html

This could possible be fixed by having the headnote div be empty, and when the page loads vue injects Ckeditor into it

**Comment by rebeccacremona** [comment]
To be discussed: why is it desirable to have Vue load on every page?

**Comment by holtchesley** [comment]
We're loading Vue as needed on pages that require it in the Django app. Closing as outdated.
