### ISSUE TITLE
Limit conversations with solr?

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#786]
Why does solr have to be running for the app to work? Let's find out, and see if we can stop it.

suggested by @leppert

**Comment by rebeccacremona** [comment]
Escalating this because of errors like:
```
A RSolr::Error::Http occurred in resources#annotate:

  RSolr::Error::Http - 503 Service Unavailable
Error: {"responseHeader":{"status":503,"QTime":23},"error":{"metadata":["error-class","org.apache.solr.common.SolrException","root-error-class","org.apache.solr.common.SolrException"],"msg":"Error opening new searcher. exceeded limit of maxWarmingSearchers=5, try again later.","code":503}}
```
Why do we need to talk to solr to annotate something?

**Comment by cgruppioni** [comment]
@rebeccacremona This will solve your second comment https://github.com/harvard-lil/h2o/pull/803 

AFAIK Solr runs everytime a record is updated, which is needed to keep the search page up to date

**Comment by rebeccacremona** [comment]
See also https://github.com/harvard-lil/h2o/issues/332
