### ISSUE TITLE
Kennedy export issues

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#793]
Trying to export this SECTION fails: https://opencasebook.org/casebooks/122988-contracts-joy-and-heartbreak/sections/7/layout . This section has no annotations on either of its items, but when i try to open the export that is "With Annotations", Word returns this:

![Screen Shot 2019-05-20 at 6 23 29 PM](https://user-images.githubusercontent.com/12850389/58055887-37b71180-7b2d-11e9-8fde-b2c583be393e.png)

 Exporting its individual resources works fine.
I have attempted:
-removing all punctuation from section and resource titles
-removed all tags besides p tags from the two resources' contents
-removing chunks of the text of both item to see if that would change the 'Location' number on the Word error - no luck.

I have also *duplicated* this section in full in a different casebook for testing, and it _does_ open, but displays only the section title: 

<img width="647" alt="Screen Shot 2019-05-20 at 6 34 46 PM" src="https://user-images.githubusercontent.com/12850389/58056100-f6733180-7b2d-11e9-8b74-a59fe20db246.png">

Here is the duplicate I created for testing: https://opencasebook.org/casebooks/67247-criminal-law-reading-group-2016/sections/10/layout

"Export without annotations" works fine on both.

**Comment by abziegler** [comment]
@bjohnson747 I was able to export this section with and without annotations in Firefox and Chrome

**Comment by bjohnson747** [comment]
I was thinking this might be related to browser caching (since its working in Firefox for me) but it's working in my Chrome now, as well - a day later. Testing further

**Comment by bjohnson747** [comment]
It appears it is CENTER tag that prevents exporting. 
content that is instead tagged: h2 style="text-align: center;"  - do NOT prevent export.
In this section: https://opencasebook.org/casebooks/122988-contracts-joy-and-heartbreak/sections/5.8.2/layout 

-the first item does not open in Word (has center tag)
-the second item *does* open in Word.  (has the "text-align: center;")

If there is a way to tell Word to ignore center tags (or some other more graceful solution) that would  allow these exports to be openable, that would be great. Attempting to convert all center tags in existing cases into something else could be hairy, as it would have an affect annotation location on existing cases. @abziegler

**Comment by bjohnson747** [comment]
I re-created the problem section mentioned above here: https://opencasebook.org/casebooks/72834-free-as-a-bird/sections/1/layout
And *both* items, including the one with a center tag, export fine. 

This leads me to believe it may be an issue with that specific casebook, and/or it has something to do with ancestry/cloning (since the Kennedy casebook is built from a clone of Fried's casebook).

**Comment by cgruppioni** [comment]
Thanks Brett! 

Brett & I just talked and it's not a cloning issue. For this case it seems to be an annotation issue. Most likely from an issue with elisions being nested at the top.

**Comment by bjohnson747** [comment]
I believe the elisions-nesting issue was due to this specific Fried casebook getting an extra elision at the top in the case header, to make up for the existing elision moving over one character at some point. 
Kennedy's casebook resources have been checked and are all cleaned up,
I also went through the Fried casebook (Contracts - digital edition) and cleaned up all the headers in that so it would export correctly.
