### ISSUE TITLE
Section and resource (export cache?) clears at different rates (Chrome only?)

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#794]
When I change an item's annotations, then export it, the export reflects the changes.

When i export the section the item is in, the section does not reflect the annotation changes -
 unless i try it in a different browser, or something else: In one of my tests, it was next day that the section began exporting correctly. Unsure if this was time dependent, or had something to do with me putting my machine to sleep.

EXAMPLE: this section https://opencasebook.org/casebooks/72834-free-as-a-bird/sections/1/layout
I changed the edits in US v Algernon to this:
![Screen Shot 2019-05-21 at 2 01 28 PM](https://user-images.githubusercontent.com/12850389/58119424-f24c2000-7bd0-11e9-821d-2ac7ca6afa62.png)

But *(as of 5/21, 2pm EST, two minutes after making the change)* exporting the full section that resource is in reflects the old version of the annotations:
![Screen Shot 2019-05-21 at 2 02 40 PM](https://user-images.githubusercontent.com/12850389/58119511-245d8200-7bd1-11e9-8c4c-5fcb9d15ed08.png)

*if there is a more accurate way to title this issue, please feel free to change!

**Comment by bjohnson747** [comment]
**this may be Chrome specific **

**Comment by leppert** [comment]
@bjohnson747 Check out PR #797. It was a blind edit (I haven't tested it) but believe it should fix the problem.
