### ISSUE TITLE
Casebook playlist_id field should only be for casebooks originally imported from old h2o, not clones. 

### ISSUE THREAD

**Issue by cgruppioni** [harvard-lil/h2o#796]

**Comment by rebeccacremona** [comment]
To be discussed: to we want to hang on to legacy data fields like this?

**Comment by lizadaly** [comment]
Action: drop the playlist_id field from the database.

**Comment by lizadaly** [comment]
This field doesn't exist anymore, so I guess this happened? (It's referenced only in a squashed model migration.)
