### ISSUE TITLE
Define (as possible) what html we'd like from CAP

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#801]
CAP says we can define a schema for its case HTML, and then they'll validate against that schema as part of their test suite. "Could start as failure-allowed if the output isn't currently right", quoth @jcushman. @ChefAndy says it wouldn't be difficult to send H2O custom markup, so not to be shy about asking.

First step could simply be to read https://github.com/leppert/capapi-ruby and https://github.com/harvard-lil/h2o/tree/master/lib/capapi and work out what html structure and/or css selectors are currently expected.

Second step could be to discuss/decide whether article/section/aside tags are working for us, etc. 

@ChefAndy says we can hang our hat on the document being valid HTML. @jcushman says:
> there should not be arbitrary HTML like lists, tables, small in CAP HTML — it’s a defined vocabulary converted from XML
>
> the full list is … whatever can come out of the several hundred lines of code in this function :slightly_smiling_face: https://github.com/harvard-lil/capstone/blob/develop/capstone/scripts/render_case.py#L316
> but we can probably get it right just by eyeballing it — the only special features our cases have would be images, footnotes, page numbers, block quotes
> ...
> there’s also a thing called headnote marks that are like footnotes from the case text to summary paragraphs in the header — those are mostly redacted so might take a minute to find an example
> ...
> no headings, though our best guess at headings is a feature adam has asked for

**Comment by rebeccacremona** [comment]
Also I said I'd send a PR for said tests :-)

**Comment by cgruppioni** [comment]
Let's bring this up on the meeting next Tuesday and get the ball rolling
