### ISSUE TITLE
Archive legacy tables 

### ISSUE THREAD

**Issue by cgruppioni** [harvard-lil/h2o#808]
Archive the following tables
`annotations`
`collages`
`media_types`
`medias`
`playlist_items`
`playlists`
`taggings`
`tags`

Remove legacy tables that are from gems: 
`delayed_jobs`
`frozen_items`
`permission_assignments`
`permissions`

Tables that do not exist the schema and are not from gems: 
`metadata`
`playlists_user_collections`
`user_collections`
`user_collections_users`

**Comment by rebeccacremona** [comment]
Closing: we'll drop all tables unused by the Django app shortly.
