### ISSUE TITLE
Adding a new resource with no name throws an error

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/h2o#830]
There should be a user-facing validation step rather than
```
An ActiveRecord::RecordInvalid occurred in sections#create:

  Validation failed: Resource name can't be blank
  app/controllers/content/sections_controller.rb:17:in `create'
```

**Comment by rebeccacremona** [comment]
In the Django app, this no longer 500s: instead, it catches it and returns 400 Bad Request, plus a validation error message... but the JS doesn't yet handle it, and the modal just closes. Obviously we should just display the error message, instead :-)
