### ISSUE TITLE
Eliding pre tags: spaces left onscreen

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#836]
Working off of this item: https://opencasebook.org/casebooks/73057-zittrain-torts-playlist-rename/resources/1.2.2-board-v-garrett/annotate#/
When eliding a table, it leaves a bar where the table was. When I elide all the tables in Board v Garrett it looks like this:

<img width="929" alt="board v garrett table extra" src="https://user-images.githubusercontent.com/12850389/61910153-d121eb80-af01-11e9-95c1-f67fd5dde43a.png">

In export, tables don't display correctly:

![Screen Shot 2019-07-25 at 5 30 02 PM](https://user-images.githubusercontent.com/12850389/61910193-eb5bc980-af01-11e9-9a9b-a4e33efc62cd.png)

**Comment by rebeccacremona** [comment]
Update: in-browser, this is still true. But, in Django-land, export of this case is now fine. Note that the "tables" are actually marked up as `<pre>` in the source: pandoc faithfully applies the style "Source Code". If we want actual tables here, we need to update the source to use table markup.

**Comment by holtchesley** [comment]
Should be addressed by #1101
