### ISSUE TITLE
Running list of data questions

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#872]
Addressed, Round 1:
- Q: There are a lot of CaseCourts with 0 associated cases. Data problem, or just unnecessary objects? A: We can delete these.
- Q: Why do "Default" objects have a "created by import" field (always false, I think)? A: Let's drop this field.
- Q: There are some Casebooks with no "owners". How can that be? Maybe users were deleted, but their casebooks weren't? A: Let's assign these to an owner.
- Q: TextBlocks have a 'version' field, currently populated with integers from 1-3. What is this? A: Unknown, and in any case no longer useful. We are free to drop.

- Q: In the Rails admin, I see newly created Defaults that belong to user 0. What are those? Also, I see some TextBlocks that aren't associated with a user. Some of them have related resources. What are those? A: These user column for both these models was a mess... nulls, 0s, no-longer-existing users... and, in any case, is redundant w/the owner of the associated resource object/casebook. Deleting. If we want to track authorship of these objects independently of casebooks in the future, we'll need new code + data anyway.

- Q: There are lots of TextBlocks and Defaults that aren't associated with any Resource objects. Why? A: We're going to delete these. We think that some (or all) of them were accidentally not deleting, during the merging of drafts. Others are likely from other deletion processes.
```
>>> Default.objects.exclude(id__in=Resource.objects.filter(resource_type='Default').values('resource_id')).count()
34590
>>> Default.objects.filter(id__in=Resource.objects.filter(resource_type='Default').values('resource_id')).count()
12361
>>> 12361 + 34590
46951
>>> Default.objects.count()
46951

>>> TextBlock.objects.exclude(id__in=Resource.objects.filter(resource_type='TextBlock').values('resource_id')).count()
21783
>>> TextBlock.objects.filter(id__in=Resource.objects.filter(resource_type='TextBlock').values('resource_id')).count()
9934
>>> 21783 + 9934
31717
>>> TextBlock.objects.count()
31717
```

- Q: Roles: can we delete all the "asker" roles? How about "rep"? A: Yes.

- Q: Can we simplify a user's name calculation? I see this (https://github.com/harvard-lil/h2o/blob/1f50f3f6b2085d0083244c820f8306137b536fe8/db/migrate/20180719190825_add_default_to_users_attribution.rb#L3), and I see lots of users whose attribution = "Anonymous".... I also see lots of users without attributions. Some have 'titles' instead. And, there's code for naming them "Anonymous" for display purposes.... I think we need another round. A: Done.

Addressed, Round 2:

- Q: Roles/Users: can we clean up the list of superusers?  A: Certainly. And.... done by Adam.)

- Q: Roles/Users: each user should now have only one role. Can we drop this whole many-to-many setup, in favor of standard Django permissions/groups? A: Certainly. And... done.

- Q: Can we add a default "untitled" titles to db for things, instead of dynamically calculating fallback titles in the ruby/python? A: in https://github.com/harvard-lil/h2o/pull/1030; deliberation there.

- Q: All nodes are marked as "cloneable". Do we need this field, against a future where certain books may not be cloned? A: Deliberation in https://github.com/harvard-lil/h2o/pull/1031/files

- Q: When is a Casebook's "root_user" field populated? I thought maybe all clones, or all non-draft clones, but nope. Sometimes populated for non-clones; not always populated for clones and drafts. Correct, or needs cleaning up? A: This is a whole can of worms. Spun into its own issue, https://github.com/harvard-lil/h2o/issues/1032

- Q: ContentCollaborators: there are a handful of "owner" roles with "has_attribution" = False. Is that in error? Should attribution be different than ownership? A: Spun into its own issue, https://github.com/harvard-lil/h2o/issues/1033

- Q: - Does it matter that there are duplicate CaseCourts? Should we clean that up? Should we try to prevent that in the future? Or, is it fine? There are a lot of Cases without CaseCourts. Same question. A: Spun into its own issue, https://github.com/harvard-lil/h2o/issues/1037

- Q: What is the difference between a TextBlock's "name" and it's "description"? A: Spun into its own issue, https://github.com/harvard-lil/h2o/issues/1045

Still pending:
- Why do "Link" objects have a "content_type" field? Do we need it?

**Comment by rebeccacremona** [comment]
Good to know: the "public" field only applies to Casebooks, not to Sections or Resources.
```
>>> ContentNode.objects.filter(casebook__public=False, public=True).count()
31512
>>> ContentNode.objects.count()
59872
>>> Section.objects.filter(public=False).count()
0
>>> Resource.objects.filter(public=False).count()
0
```

**Comment by holtchesley** [comment]
The only thing in here that hasn't been spun off yet is:
`Why do "Link" objects have a "content_type" field? Do we need it?`
So I'm spinning it off into #1109 and closing this issue.
