### ISSUE TITLE
Django proxy models and methods

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#900]
To think about:

If casebooks, sections, and resources all need certain methods, but need to implement them differently, where's the best spot to put that logic:

1) Right in `ContentNode`, with a switch based on `node.type`?
2) As independent methods in the proxy classes, `Casebook`, `Section`, `Resource`, with some strategy for accessing those methods, should you have `ContentNode` objects (e.g. the `to_proxy` method, or a switch that calls class methods as with `get_absolute_url` ((perhaps wrapped in a nice abstraction)) or......)

(Though, I'm also thinking that in the future, we may want to rethink this whole proxy model design.... We may want separate models that inherit from various abstract base classes.)

**Comment by jcushman** [comment]
After slack conversation, here's a plausible solution for `ContentNode`:

```
    def type_class(self):
        if not self.casebook:
            return Casebook
        elif not self.resource_id:
            return Section
        else:
            return Resource

    @staticmethod
    def specialize(func):
        @wraps(func)
        def wrapper(self, *args, **kwargs):
            specialize_method = getattr(self.type_class(), func.__name__, None)
            if specialize_method:
                return specialize_method(self, *args, **kwargs)
            else:
                return func(self, *args, **kwargs)

    @specialize
    def some_func(self, *args, **kwargs):
        # do fallback stuff or raise not implemented
```
