### ISSUE TITLE
Bulk Download API

### ISSUE THREAD

**Issue by malteos** [harvard-lil/h2o#916]
Hi,

thanks for your amazing work! Is there any programmatic way to download all available casebooks  (if possible including the corresponding case.law-ids)?

Best,
Malte

**Comment by holtchesley** [comment]
Hello Malte,

We haven't had a use case for this yet, but may in the future. Does the current casebook export produce a format that works for what you're planning, or are you looking for a  a different form?

**Comment by malteos** [comment]
I'm looking for a machine-readable format (MS Word is not much of a help). Anything like JSON or XML would be great. I plan to use the data for a recommender system research project.

**Comment by malteos** [comment]
Any news on this?

**Comment by mdellabitta** [comment]
Sorry, we don't have plans for this at the moment.
