### ISSUE TITLE
Case search: attempting to go to page 2 closes the search box

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#923]
When adding Resource -> Case, if the case list has multiple pages, clicking to page 2 refreshes the screen and the search window disappears.

Searching for a case:
![Screen Shot 2019-11-15 at 11 31 58 AM](https://user-images.githubusercontent.com/12850389/68959280-bb2f8380-079b-11ea-86b5-94a0d3d816b4.png)

When i clicked page 2 on the above, the search box went away and it brought me back to the casebook view.

**Comment by rebeccacremona** [comment]
@bjohnson747 Thanks! I actually have a fix for this in a momentary PR

**Comment by rebeccacremona** [comment]
@bjohnson747 Fixed!
