### ISSUE TITLE
Handle positioning and overflow text on casebook card on dashboard

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#947]
Currently, long titles, subtitles wreak havoc on dashboard display of individual casebooks. We should impose some fixed positioning for needed metadata elements and handle overflow text. Note also positioning of "unpublished changes" `div`

![image](https://user-images.githubusercontent.com/2140548/69724956-0d04d180-10eb-11ea-8e30-f1e682a36f36.png)

**Comment by holtchesley** [comment]
Addressed in #1085
