### ISSUE TITLE
On stage, a revision draft is not successfully merging/replacing published casebook

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#950]
Expected behavior when click `Publish Revisions` is to substitute the existing, published version of casebook with the new, revised version. Right now, nothing happens when click `Publish Revisions`

POST request gets a 500 error: `'NoneType' object has no attribute 'copy_of_id'`

**Comment by rebeccacremona** [comment]
Hmm. Which book are you having a problem with? I just a) cloned a book, b) published it, c) made a revision draft, d) successfully merged that draft. https://h2o-experiment.lil.tools/casebooks/195537-revised-ready-to-merge/

(We haven't set up error emails yet, which would give us details: coming soon!)

**Comment by abziegler** [comment]
Published: 195168
Revision Draft: 195189

**Comment by abziegler** [comment]
I reconfirmed the problem with that casebook. And/but I was not able to recreate problem with another casebook.
