### ISSUE TITLE
Update CSS to handle in-case images from CAP

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#954]
Example: https://h2o-experiment.lil.tools/casebooks/84994-funky-casebook/resources/1-thompson-v-boisselier/#/

Look at CAP for CSS for this, per @jcushman

**Comment by rebeccacremona** [comment]
(example link is broken. but! no css ensures that images stay in their containers. this applies to all images in headnotes, cases, and textblocks)

**Comment by lizadaly** [comment]
I added that case to a casebook and I think it looks identical to CAP and not particularly broken:

https://opencasebook.org/casebooks/5683-untitled/resources/2-thompson-v-boisselier/annotate/

https://cite.case.law/us/114/1/


<img width="401" alt="image" src="https://user-images.githubusercontent.com/19571/177376870-dc2f7a98-d1b0-4c4b-96ee-55ad522996d7.png">

(H2O)

vs.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/19571/177376987-8210d236-75bf-4938-8aac-e4fa8d6df3e5.png">

(CAP)

So closing this unless and until we find a better reproduction case.

**Comment by rebeccacremona** [comment]
I think this got fixed by https://github.com/harvard-lil/h2o/pull/1454
