### ISSUE TITLE
Deleting case from DB causes 500 error for casebook that included case as resource

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#956]
Unlikely (hopefully) scenario, but probably if an admin deletes a case from DB, that should not prevent loading of casebooks that had included that case. 

This is likely an existing situation. Not sure best way to handle. Maybe "deleting" a case should be a soft-delete, which doesn't cause casebook errors?

**Comment by abziegler** [comment]
Update: on prod, via Rails admin, deleting a case is DISALLOWED if the case is used in an existing casebook. This seems good from standpoint of avoiding careless crisis.

**Comment by rebeccacremona** [comment]
I think the deletion of cases that are included in casebooks should be made impossible: I think the code should prevent it from happening.

**Comment by jcushman** [comment]
Probly we should disable Django admin delete across the board, and re-enable as needed with testing.

**Comment by jcushman** [comment]
We have disabled object deletion and creation for most objects. Let's open new issues for object creation and deletion as needed.
