### ISSUE TITLE
Cases without citations appear in search index, but not as search results

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/h2o#961]
At least via the console/admin, it's possible to create cases that appear in the search index and in the complete case index that loads when you visit the search page, but that don't appear when you search for their names.

1) Create a new case, with a title, but no citation. Note its ID.
2) Reindex
3) Pop into the DB shell
4) Find the matching row in the search index: `select * from search_view where result_id=<id>;`
5) Search for the title -> no results
6) Add a citation for the case (e.g. `[{"cite": "1 Cremona. 1", "type": "official"}]`)
7) Reindex
8) Search for the title -> found

This may not matter in real life: making a ticket because this was flummoxing during local testing.

**Comment by holtchesley** [comment]
Addressed by #1103
