### ISSUE TITLE
Enable large paraphrases of text

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#968]
E.g. summarizing findings of fact or a dissenting opinion. Our "replace text" feature works for short paraphases of elided text, but not for long summaries.

**Comment by abziegler** [comment]
Here's an example ... the "replacement" text extends for another words or so, but everything after "for" is not displaying.

![image](https://user-images.githubusercontent.com/2140548/80371425-e5fc2880-885f-11ea-806d-77ce0239f813.png)

**Comment by holtchesley** [comment]
This was an odd issue with FFDevEdition oninput events interacting in an odd way with content editable. Work-around introduced.
