### ISSUE TITLE
Annotation save not working

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#990]
When you try to use "replace text," "note" and "link" annotation types, annotations do not save

**Comment by abziegler** [comment]
Elision and highlight annotations do save

**Comment by rebeccacremona** [comment]
Sorry, see H2O-dev slack: we just need to run migrations.

**Comment by abziegler** [comment]
All annotations are not saving (I know this will be fixed with migrations, just trying to document scope).

**Comment by rebeccacremona** [comment]
Migrations run.
