### ISSUE TITLE
CK Editor - all text looks bold in editor

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#991]
In editor for adding Text Resource, you can't distinguish between bold and regular text. But if you mark some text for bold, it is bold once you save and render the resource.

In editor:

![image](https://user-images.githubusercontent.com/2140548/70925868-01297280-1ffa-11ea-8e80-47daa41fe62a.png)

After save/render:

![image](https://user-images.githubusercontent.com/2140548/70926054-641b0980-1ffa-11ea-9c50-6fe093d0406f.png)

**Comment by rebeccacremona** [comment]
No longer applies. (Switched to MCE, which doesn't do this.)
