### ISSUE TITLE
Display multi-owner attribution in dashboard

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#995]
If a casebook has multiple owners who should get attribution, we currently display only a single author (the first?) on dashboard. We should display all owners who get attribution.

**Comment by rebeccacremona** [comment]
Instead of https://github.com/harvard-lil/h2o/blob/develop/_python/main/templates/includes/content_browser.html#L21, we can use https://github.com/harvard-lil/h2o/blob/develop/_python/main/templates/includes/collaborators.html#L1 (or something like it, maybe briefer)

**Comment by holtchesley** [comment]
#1083 #1084 #1085 cleared this up.
